//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 04:13:46 PM CDT 
//


package com.mastercard.gateway.ats.domain

import org.simpleframework.xml.Element
import org.simpleframework.xml.Root
import org.simpleframework.xml.Text
import java.math.BigDecimal

/**
 * ARTS: Amount -- a generalized monetary amount attribute
 *
 *
 * Kotlin class for Amount complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Amount"&gt;
 * &lt;simpleContent&gt;
 * &lt;extension base="&lt;http://www.nrf-arts.org/IXRetail/namespace&gt;MonetaryAmount"&gt;
 * &lt;/extension&gt;
 * &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
</pre> *
 *
 *
 */
@Root(name = "Amount", strict = false)
data class Amount(@field:Text(required = true) var value: BigDecimal)
