//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 04:13:46 PM CDT 
//


package com.mastercard.gateway.ats.domain

import org.simpleframework.xml.Element
import org.simpleframework.xml.Root


/**
 *
 * Kotlin class for ATSErrorDetailType complex type.
 *
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 *
 * <pre>
 * &lt;complexType name="ATSErrorDetailType"&gt;
 * &lt;complexContent&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 * &lt;sequence&gt;
 * &lt;element name="Error" type="{http://www.nrf-arts.org/IXRetail/namespace}ATSErrorType"/&gt;
 * &lt;element name="Response" type="{http://www.nrf-arts.org/IXRetail/namespace}ATSResponseType" minOccurs="0"/&gt;
 * &lt;/sequence&gt;
 * &lt;/restriction&gt;
 * &lt;/complexContent&gt;
 * &lt;/complexType&gt;
</pre> *
 */
@Root(name = "ATSErrorDetailType", strict = false)
data class ATSErrorDetailType(
        @field:Element(name = "Error", required = true) var error: ATSErrorType,
        @field:Element(name = "Response", required = false) var response: ATSResponseType
)
