//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 04:13:46 PM CDT 
//


package com.mastercard.gateway.ats.domain


/**
 *
 * Java class for CardRequestType.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 *
 * <pre>
 * &lt;simpleType name="CardRequestType"&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 * &lt;enumeration value="CardPayment"/&gt;
 * &lt;enumeration value="CardSwipe"/&gt;
 * &lt;enumeration value="LoyaltySwipe"/&gt;
 * &lt;enumeration value="CardPaymentLoyaltyAward"/&gt;
 * &lt;enumeration value="LoyaltyAward"/&gt;
 * &lt;enumeration value="CardPreAuthorisation"/&gt;
 * &lt;enumeration value="CardFinancialAdvice"/&gt;
 * &lt;enumeration value="CardPreAuthorisationLoyaltySwipe"/&gt;
 * &lt;enumeration value="CardFinancialAdviceLoyaltyAward"/&gt;
 * &lt;enumeration value="LoyaltyRedemption"/&gt;
 * &lt;enumeration value="CardPaymentLoyaltyRedemption"/&gt;
 * &lt;enumeration value="PaymentReversal"/&gt;
 * &lt;enumeration value="PaymentLoyaltyReversal"/&gt;
 * &lt;enumeration value="PaymentRefund"/&gt;
 * &lt;enumeration value="PaymentLoyaltyRefund"/&gt;
 * &lt;enumeration value="LoyaltyAwardReversal"/&gt;
 * &lt;enumeration value="LoyaltyRedemptionReversal"/&gt;
 * &lt;enumeration value="LoyaltyBalanceQuery"/&gt;
 * &lt;enumeration value="LoyaltyLinkCard"/&gt;
 * &lt;enumeration value="LoyaltyPointsTransfer"/&gt;
 * &lt;enumeration value="PINchange"/&gt;
 * &lt;enumeration value="TicketReprint"/&gt;
 * &lt;enumeration value="StoreValueInCard"/&gt;
 * &lt;enumeration value="RefundValueFromCard"/&gt;
 * &lt;enumeration value="CardActivate"/&gt;
 * &lt;enumeration value="CardStop"/&gt;
 * &lt;enumeration value="CardBalanceQuery"/&gt;
 * &lt;enumeration value="RepeatLastMessage"/&gt;
 * &lt;enumeration value="AbortRequest"/&gt;
 * &lt;enumeration value="RefundReversal"/&gt;
 * &lt;enumeration value="PreAuthReversal"/&gt;
 * &lt;enumeration value="CardBarTab"/&gt;
 * &lt;enumeration value="BarTabReversal"/&gt;
 * &lt;enumeration value="ETUPayment"/&gt;
 * &lt;enumeration value="ETUPaymentReversal"/&gt;
 * &lt;enumeration value="ETURefund"/&gt;
 * &lt;enumeration value="ETURefundReversal"/&gt;
 * &lt;enumeration value="CardValidation"/&gt;
 * &lt;enumeration value="CardPaymentLoyaltySwipe"/&gt;
 * &lt;enumeration value="ETUPreAuthorisation"/&gt;
 * &lt;enumeration value="ETUPreAuthReversal"/&gt;
 * &lt;enumeration value="ETUFinancialAdvice"/&gt;
 * &lt;enumeration value="CardTokenise"/&gt;
 * &lt;enumeration value="CardTokenize"/&gt;
 * &lt;enumeration value="CardValidation1"/&gt;
 * &lt;enumeration value="CardValidation2"/&gt;
 * &lt;enumeration value="CardPayment2"/&gt;
 * &lt;enumeration value="FinancialAdviceRingFenceFix"/&gt;
 * &lt;enumeration value="CardTokenPayment"/&gt;
 * &lt;enumeration value="CardTokenRefund"/&gt;
 * &lt;enumeration value="CardTokenPreAuth"/&gt;
 * &lt;enumeration value="PaymentTokenPayment"/&gt;
 * &lt;enumeration value="PaymentTokenRefund"/&gt;
 * &lt;enumeration value="PaymentTokenPreAuth"/&gt;
 * &lt;/restriction&gt;
 * &lt;/simpleType&gt;
</pre> *
 *
 */
enum class CardRequestType {
    CardPayment,
    CardSwipe,
    LoyaltySwipe,
    CardPaymentLoyaltyAward,
    LoyaltyAward,
    CardPreAuthorisation,
    CardFinancialAdvice,
    CardPreAuthorisationLoyaltySwipe,
    CardFinancialAdviceLoyaltyAward,
    LoyaltyRedemption,
    CardPaymentLoyaltyRedemption,
    PaymentReversal,
    PaymentLoyaltyReversal,
    PaymentRefund,
    PaymentLoyaltyRefund,
    LoyaltyAwardReversal,
    LoyaltyRedemptionReversal,
    LoyaltyBalanceQuery,
    LoyaltyLinkCard,
    LoyaltyPointsTransfer,
    PINchange,
    TicketReprint,
    StoreValueInCard,
    RefundValueFromCard,
    CardActivate,
    CardStop,
    CardBalanceQuery,
    RepeatLastMessage,
    AbortRequest,
    RefundReversal,
    PreAuthReversal,
    CardBarTab,
    BarTabReversal,
    ETUPayment,
    ETUPaymentReversal,
    ETURefund,
    ETURefundReversal,
    CardValidation,
    CardPaymentLoyaltySwipe,
    ETUPreAuthorisation,
    ETUPreAuthReversal,
    ETUFinancialAdvice,
    CardTokenise,
    CardTokenize,
    CardValidation1,
    CardValidation2,
    CardPayment2,
    FinancialAdviceRingFenceFix,
    CardTokenPayment,
    CardTokenRefund,
    CardTokenPreAuth,
    PaymentTokenPayment,
    PaymentTokenRefund,
    PaymentTokenPreAuth
}
