//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 04:13:46 PM CDT 
//


package com.mastercard.gateway.ats.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Specifies the card identification to be transmitted to the application
 * 
 * <p>Java class for CardValueICCType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CardValueICCType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Track1" type="{http://www.nrf-arts.org/IXRetail/namespace}CardTrack" minOccurs="0"/&gt;
 *         &lt;element name="Track2" type="{http://www.nrf-arts.org/IXRetail/namespace}CardTrack" minOccurs="0"/&gt;
 *         &lt;element name="Track3" type="{http://www.nrf-arts.org/IXRetail/namespace}CardTrack" minOccurs="0"/&gt;
 *         &lt;element name="Barcode" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="8"/&gt;
 *               &lt;maxLength value="14"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="InString" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CardPAN" type="{http://www.nrf-arts.org/IXRetail/namespace}CardPANType" minOccurs="0"/&gt;
 *         &lt;element name="StartDate" type="{http://www.nrf-arts.org/IXRetail/namespace}CardDate" minOccurs="0"/&gt;
 *         &lt;element name="ExpiryDate" type="{http://www.nrf-arts.org/IXRetail/namespace}CardDate" minOccurs="0"/&gt;
 *         &lt;element name="CardCircuit" type="{http://www.nrf-arts.org/IXRetail/namespace}CardCircuitType" minOccurs="0"/&gt;
 *         &lt;element name="IssueNumber" type="{http://www.nrf-arts.org/IXRetail/namespace}IssueNumberType" minOccurs="0"/&gt;
 *         &lt;element name="ServiceCode" type="{http://www.nrf-arts.org/IXRetail/namespace}ServiceCodeType" minOccurs="0"/&gt;
 *         &lt;element name="Token" type="{http://www.nrf-arts.org/IXRetail/namespace}CardTokenType" minOccurs="0"/&gt;
 *         &lt;element name="CV2" type="{http://www.nrf-arts.org/IXRetail/namespace}CV2Type" minOccurs="0"/&gt;
 *         &lt;element name="PostCode" type="{http://www.nrf-arts.org/IXRetail/namespace}PostCodeType" minOccurs="0"/&gt;
 *         &lt;element name="Address" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="35"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ICC" type="{http://www.nrf-arts.org/IXRetail/namespace}ICCType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CardValueICCType", propOrder = {
    "track1",
    "track2",
    "track3",
    "barcode",
    "inString",
    "cardPAN",
    "startDate",
    "expiryDate",
    "cardCircuit",
    "issueNumber",
    "serviceCode",
    "token",
    "cv2",
    "postCode",
    "address",
    "icc"
})
public class CardValueICCType {

    @XmlElement(name = "Track1")
    protected CardTrack track1;
    @XmlElement(name = "Track2")
    protected CardTrack track2;
    @XmlElement(name = "Track3")
    protected CardTrack track3;
    @XmlElement(name = "Barcode")
    protected String barcode;
    @XmlElement(name = "InString")
    protected String inString;
    @XmlElement(name = "CardPAN")
    protected String cardPAN;
    @XmlElement(name = "StartDate")
    protected String startDate;
    @XmlElement(name = "ExpiryDate")
    protected String expiryDate;
    @XmlElement(name = "CardCircuit")
    protected String cardCircuit;
    @XmlElement(name = "IssueNumber")
    protected String issueNumber;
    @XmlElement(name = "ServiceCode")
    protected String serviceCode;
    @XmlElement(name = "Token")
    protected String token;
    @XmlElement(name = "CV2")
    protected String cv2;
    @XmlElement(name = "PostCode")
    protected String postCode;
    @XmlElement(name = "Address")
    protected String address;
    @XmlElement(name = "ICC")
    protected ICCType icc;

    /**
     * Gets the value of the track1 property.
     * 
     * @return
     *     possible object is
     *     {@link CardTrack }
     *     
     */
    public CardTrack getTrack1() {
        return track1;
    }

    /**
     * Sets the value of the track1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardTrack }
     *     
     */
    public void setTrack1(CardTrack value) {
        this.track1 = value;
    }

    /**
     * Gets the value of the track2 property.
     * 
     * @return
     *     possible object is
     *     {@link CardTrack }
     *     
     */
    public CardTrack getTrack2() {
        return track2;
    }

    /**
     * Sets the value of the track2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardTrack }
     *     
     */
    public void setTrack2(CardTrack value) {
        this.track2 = value;
    }

    /**
     * Gets the value of the track3 property.
     * 
     * @return
     *     possible object is
     *     {@link CardTrack }
     *     
     */
    public CardTrack getTrack3() {
        return track3;
    }

    /**
     * Sets the value of the track3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardTrack }
     *     
     */
    public void setTrack3(CardTrack value) {
        this.track3 = value;
    }

    /**
     * Gets the value of the barcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * Sets the value of the barcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarcode(String value) {
        this.barcode = value;
    }

    /**
     * Gets the value of the inString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInString() {
        return inString;
    }

    /**
     * Sets the value of the inString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInString(String value) {
        this.inString = value;
    }

    /**
     * Gets the value of the cardPAN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardPAN() {
        return cardPAN;
    }

    /**
     * Sets the value of the cardPAN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardPAN(String value) {
        this.cardPAN = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartDate(String value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpiryDate(String value) {
        this.expiryDate = value;
    }

    /**
     * Gets the value of the cardCircuit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardCircuit() {
        return cardCircuit;
    }

    /**
     * Sets the value of the cardCircuit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardCircuit(String value) {
        this.cardCircuit = value;
    }

    /**
     * Gets the value of the issueNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssueNumber() {
        return issueNumber;
    }

    /**
     * Sets the value of the issueNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssueNumber(String value) {
        this.issueNumber = value;
    }

    /**
     * Gets the value of the serviceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceCode() {
        return serviceCode;
    }

    /**
     * Sets the value of the serviceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceCode(String value) {
        this.serviceCode = value;
    }

    /**
     * Gets the value of the token property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToken() {
        return token;
    }

    /**
     * Sets the value of the token property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToken(String value) {
        this.token = value;
    }

    /**
     * Gets the value of the cv2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCV2() {
        return cv2;
    }

    /**
     * Sets the value of the cv2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCV2(String value) {
        this.cv2 = value;
    }

    /**
     * Gets the value of the postCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * Sets the value of the postCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostCode(String value) {
        this.postCode = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress(String value) {
        this.address = value;
    }

    /**
     * Gets the value of the icc property.
     * 
     * @return
     *     possible object is
     *     {@link ICCType }
     *     
     */
    public ICCType getICC() {
        return icc;
    }

    /**
     * Sets the value of the icc property.
     * 
     * @param value
     *     allowed object is
     *     {@link ICCType }
     *     
     */
    public void setICC(ICCType value) {
        this.icc = value;
    }

}
