//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 04:13:46 PM CDT 
//


package com.mastercard.gateway.ats.domain

import org.simpleframework.xml.Attribute
import org.simpleframework.xml.Element
import org.simpleframework.xml.Order
import org.simpleframework.xml.Root

import java.math.BigInteger

import javax.xml.datatype.XMLGregorianCalendar


/**
 *
 * Java class for anonymous complex type.
 *
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 *
 * <pre>
 * &lt;complexType&gt;
 * &lt;complexContent&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 * &lt;sequence&gt;
 * &lt;element name="Terminal" minOccurs="0"&gt;
 * &lt;complexType&gt;
 * &lt;complexContent&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 * &lt;attribute name="TerminalID" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}TerminalIDType" /&gt;
 * &lt;attribute name="TerminalBatch" type="{http://www.nrf-arts.org/IXRetail/namespace}BatchCodeType" /&gt;
 * &lt;attribute name="MerchantID" type="{http://www.nrf-arts.org/IXRetail/namespace}MerchantIDType" /&gt;
 * &lt;attribute name="STAN" type="{http://www.nrf-arts.org/IXRetail/namespace}STANtype" /&gt;
 * &lt;attribute name="APACS50TN" type="{http://www.nrf-arts.org/IXRetail/namespace}APACS50TNtype" /&gt;
 * &lt;/restriction&gt;
 * &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * &lt;/element&gt;
 * &lt;element name="ErrorDetail" type="{http://www.nrf-arts.org/IXRetail/namespace}ATSErrorDetailType" minOccurs="0"/&gt;
 * &lt;element name="Tender" minOccurs="0"&gt;
 * &lt;complexType&gt;
 * &lt;complexContent&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 * &lt;sequence&gt;
 * &lt;element name="TotalAmount" type="{http://www.nrf-arts.org/IXRetail/namespace}TotalAmountType" minOccurs="0"/&gt;
 * &lt;element name="Authorisation" minOccurs="0"&gt;
 * &lt;complexType&gt;
 * &lt;complexContent&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 * &lt;attribute name="AcquirerID" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}AcquirerType" /&gt;
 * &lt;attribute name="IssuerID" type="{http://www.nrf-arts.org/IXRetail/namespace}IssuerType" /&gt;
 * &lt;attribute name="CardPAN" type="{http://www.nrf-arts.org/IXRetail/namespace}CardPANType" /&gt;
 * &lt;attribute name="StartDate" type="{http://www.nrf-arts.org/IXRetail/namespace}CardDate" /&gt;
 * &lt;attribute name="ExpiryDate" type="{http://www.nrf-arts.org/IXRetail/namespace}CardDate" /&gt;
 * &lt;attribute name="IssueNumber" type="{http://www.nrf-arts.org/IXRetail/namespace}IssueNumberType" /&gt;
 * &lt;attribute name="Token" type="{http://www.nrf-arts.org/IXRetail/namespace}CardTokenType" /&gt;
 * &lt;attribute name="TimeStamp" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 * &lt;attribute name="ActionCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 * &lt;attribute name="ApprovalCode" type="{http://www.nrf-arts.org/IXRetail/namespace}AuthorisationCodeType" /&gt;
 * &lt;attribute name="AcquirerBatch" type="{http://www.nrf-arts.org/IXRetail/namespace}BatchCodeType" /&gt;
 * &lt;attribute name="CardCircuit" type="{http://www.nrf-arts.org/IXRetail/namespace}CardCircuitType" /&gt;
 * &lt;attribute name="FiscalReceipt" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 * &lt;attribute name="TimeDisplay" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 * &lt;attribute name="LoyaltyAllowed" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 * &lt;attribute name="ReceiptCopies" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 * &lt;attribute name="Merchant" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 * &lt;attribute name="AuthorisationType" type="{http://www.nrf-arts.org/IXRetail/namespace}AuthorisationMethodType" /&gt;
 * &lt;attribute name="ReceiptNumber" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 * &lt;attribute name="CaptureReference" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 * &lt;attribute name="TrackingReference" type="{http://www.nrf-arts.org/IXRetail/namespace}TrackingReferenceType" /&gt;
 * &lt;attribute name="CardVerification" type="{http://www.nrf-arts.org/IXRetail/namespace}CardVerificationType" /&gt;
 * &lt;attribute name="CV2Result" type="{http://www.nrf-arts.org/IXRetail/namespace}AdditionalResponseType" /&gt;
 * &lt;attribute name="PostCodeResult" type="{http://www.nrf-arts.org/IXRetail/namespace}AdditionalResponseType" /&gt;
 * &lt;attribute name="AddressResult" type="{http://www.nrf-arts.org/IXRetail/namespace}AdditionalResponseType" /&gt;
 * &lt;/restriction&gt;
 * &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * &lt;/element&gt;
 * &lt;element name="RestrictionCodes" type="{http://www.nrf-arts.org/IXRetail/namespace}ProductGroupType" maxOccurs="unbounded" minOccurs="0"/&gt;
 * &lt;/sequence&gt;
 * &lt;attribute name="LanguageCode" type="{http://www.nrf-arts.org/IXRetail/namespace}LanguageCodeType" /&gt;
 * &lt;/restriction&gt;
 * &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * &lt;/element&gt;
 * &lt;element name="Loyalty" minOccurs="0"&gt;
 * &lt;complexType&gt;
 * &lt;complexContent&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 * &lt;sequence&gt;
 * &lt;element name="LoyaltyCard" minOccurs="0"&gt;
 * &lt;complexType&gt;
 * &lt;complexContent&gt;
 * &lt;extension base="{http://www.nrf-arts.org/IXRetail/namespace}CardTrack"&gt;
 * &lt;attribute name="LoyaltyPAN" type="{http://www.nrf-arts.org/IXRetail/namespace}CardPANType" /&gt;
 * &lt;/extension&gt;
 * &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * &lt;/element&gt;
 * &lt;element name="LoyaltyAmount" minOccurs="0"&gt;
 * &lt;complexType&gt;
 * &lt;simpleContent&gt;
 * &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;float"&gt;
 * &lt;attribute name="OriginalLoyaltyAmount" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
 * &lt;/extension&gt;
 * &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * &lt;/element&gt;
 * &lt;element name="LoyaltyApprovalCode" minOccurs="0"&gt;
 * &lt;complexType&gt;
 * &lt;simpleContent&gt;
 * &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 * &lt;attribute name="LoyaltyAcquirerID" type="{http://www.nrf-arts.org/IXRetail/namespace}AcquirerType" /&gt;
 * &lt;attribute name="LoyaltyAcquirerBatch" type="{http://www.nrf-arts.org/IXRetail/namespace}BatchCodeType" /&gt;
 * &lt;/extension&gt;
 * &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * &lt;/element&gt;
 * &lt;element name="Enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 * &lt;element name="CustomerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 * &lt;element name="Points" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 * &lt;element name="Bonus" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 * &lt;element name="Incentive" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 * &lt;element name="Updated" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 * &lt;/sequence&gt;
 * &lt;attribute name="LoyaltyFlag" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 * &lt;attribute name="LoyaltyTimeStamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 * &lt;/restriction&gt;
 * &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * &lt;/element&gt;
 * &lt;element name="SaleItem" type="{http://www.nrf-arts.org/IXRetail/namespace}SaleItemType" maxOccurs="unbounded" minOccurs="0"/&gt;
 * &lt;element name="OriginalHeader" minOccurs="0"&gt;
 * &lt;complexType&gt;
 * &lt;complexContent&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 * &lt;attribute name="RequestType" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}CardRequestType" /&gt;
 * &lt;attribute name="ApplicationSender" type="{http://www.nrf-arts.org/IXRetail/namespace}ApplicationType" /&gt;
 * &lt;attribute name="WorkstationID" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}WorkstationIDType" /&gt;
 * &lt;attribute name="POPID" type="{http://www.nrf-arts.org/IXRetail/namespace}POPIDType" /&gt;
 * &lt;attribute name="RequestID" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}RequestIDType" /&gt;
 * &lt;attribute name="OverallResult" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}RequestResultType" /&gt;
 * &lt;/restriction&gt;
 * &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * &lt;/element&gt;
 * &lt;element name="CardValue" type="{http://www.nrf-arts.org/IXRetail/namespace}CardValueICCType" minOccurs="0"/&gt;
 * &lt;element name="PrivateData" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 * &lt;/sequence&gt;
 * &lt;attribute name="RequestType" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}CardRequestType" /&gt;
 * &lt;attribute name="ApplicationSender" type="{http://www.nrf-arts.org/IXRetail/namespace}ApplicationType" /&gt;
 * &lt;attribute name="WorkstationID" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}WorkstationIDType" /&gt;
 * &lt;attribute name="POPID" type="{http://www.nrf-arts.org/IXRetail/namespace}POPIDType" /&gt;
 * &lt;attribute name="RequestID" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}RequestIDType" /&gt;
 * &lt;attribute name="OverallResult" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}RequestResultType" /&gt;
 * &lt;/restriction&gt;
 * &lt;/complexContent&gt;
 * &lt;/complexType&gt;
</pre> *
 */
@Root(name = "CardServiceResponse")
@Order(elements = arrayOf("terminal", "errorDetail", "tender", "loyalty", "saleItem", "originalHeader", "cardValue", "privateData"))
data class CardServiceResponse(

        @Element(name = "Terminal")
        protected var terminal: CardServiceResponse.Terminal? = null,
        @Element(name = "ErrorDetail")
        protected var errorDetail: ATSErrorDetailType? = null,
        @Element(name = "Tender")
        protected var tender: CardServiceResponse.Tender? = null,
        @Element(name = "Loyalty")
        protected var loyalty: CardServiceResponse.Loyalty? = null,
        @Element(name = "SaleItem")
        protected var saleItem: List<SaleItemType>? = null,
        @Element(name = "OriginalHeader")
        protected var originalHeader: CardServiceResponse.OriginalHeader? = null,
        @Element(name = "CardValue")
        protected var cardValue: CardValueICCType? = null,
        @Element(name = "PrivateData")
        protected var privateData: List<String>? = null,
        @Attribute(name = "RequestType", required = true)
        protected var requestType: CardRequestType,
        @Attribute(name = "ApplicationSender")
        protected var applicationSender: String? = null,
        @Attribute(name = "WorkstationID", required = true)
        protected var workstationID: String,
        @Attribute(name = "POPID")
        protected var popid: String? = null,
        @Attribute(name = "RequestID", required = true)
        protected var requestID: String,
        @Attribute(name = "OverallResult", required = true)
        protected var overallResult: RequestResultType) {

    /**
     *
     * Java class for anonymous complex type.
     *
     *
     *
     * The following schema fragment specifies the expected content contained within this class.
     *
     *
     * <pre>
     * &lt;complexType&gt;
     * &lt;complexContent&gt;
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     * &lt;sequence&gt;
     * &lt;element name="LoyaltyCard" minOccurs="0"&gt;
     * &lt;complexType&gt;
     * &lt;complexContent&gt;
     * &lt;extension base="{http://www.nrf-arts.org/IXRetail/namespace}CardTrack"&gt;
     * &lt;attribute name="LoyaltyPAN" type="{http://www.nrf-arts.org/IXRetail/namespace}CardPANType" /&gt;
     * &lt;/extension&gt;
     * &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * &lt;/element&gt;
     * &lt;element name="LoyaltyAmount" minOccurs="0"&gt;
     * &lt;complexType&gt;
     * &lt;simpleContent&gt;
     * &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;float"&gt;
     * &lt;attribute name="OriginalLoyaltyAmount" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
     * &lt;/extension&gt;
     * &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * &lt;/element&gt;
     * &lt;element name="LoyaltyApprovalCode" minOccurs="0"&gt;
     * &lt;complexType&gt;
     * &lt;simpleContent&gt;
     * &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     * &lt;attribute name="LoyaltyAcquirerID" type="{http://www.nrf-arts.org/IXRetail/namespace}AcquirerType" /&gt;
     * &lt;attribute name="LoyaltyAcquirerBatch" type="{http://www.nrf-arts.org/IXRetail/namespace}BatchCodeType" /&gt;
     * &lt;/extension&gt;
     * &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * &lt;/element&gt;
     * &lt;element name="Enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
     * &lt;element name="CustomerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     * &lt;element name="Points" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
     * &lt;element name="Bonus" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
     * &lt;element name="Incentive" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
     * &lt;element name="Updated" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
     * &lt;/sequence&gt;
     * &lt;attribute name="LoyaltyFlag" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     * &lt;attribute name="LoyaltyTimeStamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
     * &lt;/restriction&gt;
     * &lt;/complexContent&gt;
     * &lt;/complexType&gt;
    </pre> *
     */
    @Order(elements = arrayOf("loyaltyCard", "loyaltyAmount", "loyaltyApprovalCode", "enabled", "customerName", "points", "bonus", "incentive", "updated"))
    data class Loyalty(

            @Element(name = "LoyaltyCard")
            protected var loyaltyCard: CardServiceResponse.Loyalty.LoyaltyCard? = null,
            @Element(name = "LoyaltyAmount")
            protected var loyaltyAmount: CardServiceResponse.Loyalty.LoyaltyAmount? = null,
            @Element(name = "LoyaltyApprovalCode")
            protected var loyaltyApprovalCode: CardServiceResponse.Loyalty.LoyaltyApprovalCode? = null,
            @Element(name = "Enabled")
            protected var enabled: Boolean? = null,
            @Element(name = "CustomerName")
            protected var customerName: String? = null,
            @Element(name = "Points")
            protected var points: BigInteger? = null,
            @Element(name = "Bonus")
            protected var bonus: Boolean? = null,
            @Element(name = "Incentive")
            protected var incentive: BigInteger? = null,
            @Element(name = "Updated")
            protected var updated: XMLGregorianCalendar? = null,
            @Attribute(name = "LoyaltyFlag", required = true)
            protected var loyaltyFlag: Boolean = false,
            @Attribute(name = "LoyaltyTimeStamp")
            protected var loyaltyTimeStamp: XMLGregorianCalendar? = null) {


        /**
         *
         * Java class for anonymous complex type.
         *
         *
         *
         * The following schema fragment specifies the expected content contained within this class.
         *
         *
         * <pre>
         * &lt;complexType&gt;
         * &lt;simpleContent&gt;
         * &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;float"&gt;
         * &lt;attribute name="OriginalLoyaltyAmount" type="{http://www.w3.org/2001/XMLSchema}float" /&gt;
         * &lt;/extension&gt;
         * &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
        </pre> *
         */
        data class LoyaltyAmount(
                protected var value: Float = 0.toFloat(),
                @Attribute(name = "OriginalLoyaltyAmount")
                protected var originalLoyaltyAmount: Float? = null)


        /**
         *
         * Java class for anonymous complex type.
         *
         *
         *
         * The following schema fragment specifies the expected content contained within this class.
         *
         *
         * <pre>
         * &lt;complexType&gt;
         * &lt;simpleContent&gt;
         * &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         * &lt;attribute name="LoyaltyAcquirerID" type="{http://www.nrf-arts.org/IXRetail/namespace}AcquirerType" /&gt;
         * &lt;attribute name="LoyaltyAcquirerBatch" type="{http://www.nrf-arts.org/IXRetail/namespace}BatchCodeType" /&gt;
         * &lt;/extension&gt;
         * &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
        </pre> *
         */
        data class LoyaltyApprovalCode(
                protected var value: String? = null,
                @Attribute(name = "LoyaltyAcquirerID")
                protected var loyaltyAcquirerID: String? = null,
                @Attribute(name = "LoyaltyAcquirerBatch")
                protected var loyaltyAcquirerBatch: String? = null)


        /**
         *
         * Java class for anonymous complex type.
         *
         *
         *
         * The following schema fragment specifies the expected content contained within this class.
         *
         *
         * <pre>
         * &lt;complexType&gt;
         * &lt;complexContent&gt;
         * &lt;extension base="{http://www.nrf-arts.org/IXRetail/namespace}CardTrack"&gt;
         * &lt;attribute name="LoyaltyPAN" type="{http://www.nrf-arts.org/IXRetail/namespace}CardPANType" /&gt;
         * &lt;/extension&gt;
         * &lt;/complexContent&gt;
         * &lt;/complexType&gt;
        </pre> *
         */
        data class LoyaltyCard(
                @Attribute(name = "LoyaltyPAN")
                protected var loyaltyPAN: String? = null) : CardTrack()

    }


    /**
     *
     * Java class for anonymous complex type.
     *
     *
     *
     * The following schema fragment specifies the expected content contained within this class.
     *
     *
     * <pre>
     * &lt;complexType&gt;
     * &lt;complexContent&gt;
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     * &lt;attribute name="RequestType" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}CardRequestType" /&gt;
     * &lt;attribute name="ApplicationSender" type="{http://www.nrf-arts.org/IXRetail/namespace}ApplicationType" /&gt;
     * &lt;attribute name="WorkstationID" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}WorkstationIDType" /&gt;
     * &lt;attribute name="POPID" type="{http://www.nrf-arts.org/IXRetail/namespace}POPIDType" /&gt;
     * &lt;attribute name="RequestID" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}RequestIDType" /&gt;
     * &lt;attribute name="OverallResult" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}RequestResultType" /&gt;
     * &lt;/restriction&gt;
     * &lt;/complexContent&gt;
     * &lt;/complexType&gt;
    </pre> *
     */
    data class OriginalHeader(
            @Attribute(name = "RequestType", required = true)
            protected var requestType: CardRequestType,
            @Attribute(name = "ApplicationSender")
            protected var applicationSender: String? = null,
            @Attribute(name = "WorkstationID", required = true)
            protected var workstationID: String,
            @Attribute(name = "POPID")
            protected var popid: String? = null,
            @Attribute(name = "RequestID", required = true)
            protected var requestID: String,
            @Attribute(name = "OverallResult", required = true)
            protected var overallResult: RequestResultType? = null)


    /**
     *
     * Java class for anonymous complex type.
     *
     *
     *
     * The following schema fragment specifies the expected content contained within this class.
     *
     *
     * <pre>
     * &lt;complexType&gt;
     * &lt;complexContent&gt;
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     * &lt;sequence&gt;
     * &lt;element name="TotalAmount" type="{http://www.nrf-arts.org/IXRetail/namespace}TotalAmountType" minOccurs="0"/&gt;
     * &lt;element name="Authorisation" minOccurs="0"&gt;
     * &lt;complexType&gt;
     * &lt;complexContent&gt;
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     * &lt;attribute name="AcquirerID" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}AcquirerType" /&gt;
     * &lt;attribute name="IssuerID" type="{http://www.nrf-arts.org/IXRetail/namespace}IssuerType" /&gt;
     * &lt;attribute name="CardPAN" type="{http://www.nrf-arts.org/IXRetail/namespace}CardPANType" /&gt;
     * &lt;attribute name="StartDate" type="{http://www.nrf-arts.org/IXRetail/namespace}CardDate" /&gt;
     * &lt;attribute name="ExpiryDate" type="{http://www.nrf-arts.org/IXRetail/namespace}CardDate" /&gt;
     * &lt;attribute name="IssueNumber" type="{http://www.nrf-arts.org/IXRetail/namespace}IssueNumberType" /&gt;
     * &lt;attribute name="Token" type="{http://www.nrf-arts.org/IXRetail/namespace}CardTokenType" /&gt;
     * &lt;attribute name="TimeStamp" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
     * &lt;attribute name="ActionCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     * &lt;attribute name="ApprovalCode" type="{http://www.nrf-arts.org/IXRetail/namespace}AuthorisationCodeType" /&gt;
     * &lt;attribute name="AcquirerBatch" type="{http://www.nrf-arts.org/IXRetail/namespace}BatchCodeType" /&gt;
     * &lt;attribute name="CardCircuit" type="{http://www.nrf-arts.org/IXRetail/namespace}CardCircuitType" /&gt;
     * &lt;attribute name="FiscalReceipt" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     * &lt;attribute name="TimeDisplay" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     * &lt;attribute name="LoyaltyAllowed" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     * &lt;attribute name="ReceiptCopies" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
     * &lt;attribute name="Merchant" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     * &lt;attribute name="AuthorisationType" type="{http://www.nrf-arts.org/IXRetail/namespace}AuthorisationMethodType" /&gt;
     * &lt;attribute name="ReceiptNumber" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     * &lt;attribute name="CaptureReference" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     * &lt;attribute name="TrackingReference" type="{http://www.nrf-arts.org/IXRetail/namespace}TrackingReferenceType" /&gt;
     * &lt;attribute name="CardVerification" type="{http://www.nrf-arts.org/IXRetail/namespace}CardVerificationType" /&gt;
     * &lt;attribute name="CV2Result" type="{http://www.nrf-arts.org/IXRetail/namespace}AdditionalResponseType" /&gt;
     * &lt;attribute name="PostCodeResult" type="{http://www.nrf-arts.org/IXRetail/namespace}AdditionalResponseType" /&gt;
     * &lt;attribute name="AddressResult" type="{http://www.nrf-arts.org/IXRetail/namespace}AdditionalResponseType" /&gt;
     * &lt;/restriction&gt;
     * &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * &lt;/element&gt;
     * &lt;element name="RestrictionCodes" type="{http://www.nrf-arts.org/IXRetail/namespace}ProductGroupType" maxOccurs="unbounded" minOccurs="0"/&gt;
     * &lt;/sequence&gt;
     * &lt;attribute name="LanguageCode" type="{http://www.nrf-arts.org/IXRetail/namespace}LanguageCodeType" /&gt;
     * &lt;/restriction&gt;
     * &lt;/complexContent&gt;
     * &lt;/complexType&gt;
    </pre> *
     */
    @Order(elements = arrayOf("totalAmount", "authorisation", "restrictionCodes"))
    data class Tender(
            @Element(name = "TotalAmount")
            protected var totalAmount: TotalAmountType? = null,
            @Element(name = "Authorisation")
            protected var authorisation: Authorisation? = null,
            @Element(name = "RestrictionCodes")
            protected var restrictionCodes: List<BigInteger>? = null,
            @Attribute(name = "LanguageCode")
            protected var languageCode: LanguageCodeType? = null) {

        /**
         *
         * Java class for anonymous complex type.
         *
         *
         *
         * The following schema fragment specifies the expected content contained within this class.
         *
         *
         * <pre>
         * &lt;complexType&gt;
         * &lt;complexContent&gt;
         * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         * &lt;attribute name="AcquirerID" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}AcquirerType" /&gt;
         * &lt;attribute name="IssuerID" type="{http://www.nrf-arts.org/IXRetail/namespace}IssuerType" /&gt;
         * &lt;attribute name="CardPAN" type="{http://www.nrf-arts.org/IXRetail/namespace}CardPANType" /&gt;
         * &lt;attribute name="StartDate" type="{http://www.nrf-arts.org/IXRetail/namespace}CardDate" /&gt;
         * &lt;attribute name="ExpiryDate" type="{http://www.nrf-arts.org/IXRetail/namespace}CardDate" /&gt;
         * &lt;attribute name="IssueNumber" type="{http://www.nrf-arts.org/IXRetail/namespace}IssueNumberType" /&gt;
         * &lt;attribute name="Token" type="{http://www.nrf-arts.org/IXRetail/namespace}CardTokenType" /&gt;
         * &lt;attribute name="TimeStamp" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
         * &lt;attribute name="ActionCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         * &lt;attribute name="ApprovalCode" type="{http://www.nrf-arts.org/IXRetail/namespace}AuthorisationCodeType" /&gt;
         * &lt;attribute name="AcquirerBatch" type="{http://www.nrf-arts.org/IXRetail/namespace}BatchCodeType" /&gt;
         * &lt;attribute name="CardCircuit" type="{http://www.nrf-arts.org/IXRetail/namespace}CardCircuitType" /&gt;
         * &lt;attribute name="FiscalReceipt" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         * &lt;attribute name="TimeDisplay" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         * &lt;attribute name="LoyaltyAllowed" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         * &lt;attribute name="ReceiptCopies" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
         * &lt;attribute name="Merchant" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         * &lt;attribute name="AuthorisationType" type="{http://www.nrf-arts.org/IXRetail/namespace}AuthorisationMethodType" /&gt;
         * &lt;attribute name="ReceiptNumber" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         * &lt;attribute name="CaptureReference" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         * &lt;attribute name="TrackingReference" type="{http://www.nrf-arts.org/IXRetail/namespace}TrackingReferenceType" /&gt;
         * &lt;attribute name="CardVerification" type="{http://www.nrf-arts.org/IXRetail/namespace}CardVerificationType" /&gt;
         * &lt;attribute name="CV2Result" type="{http://www.nrf-arts.org/IXRetail/namespace}AdditionalResponseType" /&gt;
         * &lt;attribute name="PostCodeResult" type="{http://www.nrf-arts.org/IXRetail/namespace}AdditionalResponseType" /&gt;
         * &lt;attribute name="AddressResult" type="{http://www.nrf-arts.org/IXRetail/namespace}AdditionalResponseType" /&gt;
         * &lt;/restriction&gt;
         * &lt;/complexContent&gt;
         * &lt;/complexType&gt;
        </pre> *
         */
        data class Authorisation(

                @Attribute(name = "AcquirerID", required = true)
                protected var acquirerID: String,
                @Attribute(name = "IssuerID")
                protected var issuerID: String? = null,
                @Attribute(name = "CardPAN")
                protected var cardPAN: String? = null,
                @Attribute(name = "StartDate")
                protected var startDate: String? = null,
                @Attribute(name = "ExpiryDate")
                protected var expiryDate: String? = null,
                @Attribute(name = "IssueNumber")
                protected var issueNumber: String? = null,
                @Attribute(name = "Token")
                protected var token: String? = null,
                @Attribute(name = "TimeStamp", required = true)
                protected var timeStamp: XMLGregorianCalendar,
                @Attribute(name = "ActionCode")
                protected var actionCode: String? = null,
                @Attribute(name = "ApprovalCode")
                protected var approvalCode: String? = null,
                @Attribute(name = "AcquirerBatch")
                protected var acquirerBatch: String? = null,
                @Attribute(name = "CardCircuit")
                protected var cardCircuit: String? = null,
                @Attribute(name = "FiscalReceipt")
                protected var fiscalReceipt: Boolean? = null,
                @Attribute(name = "TimeDisplay")
                protected var timeDisplay: Boolean? = null,
                @Attribute(name = "LoyaltyAllowed")
                protected var loyaltyAllowed: Boolean? = null,
                @Attribute(name = "ReceiptCopies")
                protected var receiptCopies: BigInteger? = null,
                @Attribute(name = "Merchant")
                protected var merchant: String? = null,
                @Attribute(name = "AuthorisationType")
                protected var authorisationType: AuthorisationMethodType? = null,
                @Attribute(name = "ReceiptNumber")
                protected var receiptNumber: String? = null,
                @Attribute(name = "CaptureReference")
                protected var captureReference: String? = null,
                @Attribute(name = "TrackingReference")
                protected var trackingReference: String? = null,
                @Attribute(name = "CardVerification")
                protected var cardVerification: CardVerificationType? = null,
                @Attribute(name = "CV2Result")
                protected var cv2Result: AdditionalResponseType? = null,
                @Attribute(name = "PostCodeResult")
                protected var postCodeResult: AdditionalResponseType? = null,
                @Attribute(name = "AddressResult")
                protected var addressResult: AdditionalResponseType? = null)
    }


    /**
     *
     * Java class for anonymous complex type.
     *
     *
     *
     * The following schema fragment specifies the expected content contained within this class.
     *
     *
     * <pre>
     * &lt;complexType&gt;
     * &lt;complexContent&gt;
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     * &lt;attribute name="TerminalID" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}TerminalIDType" /&gt;
     * &lt;attribute name="TerminalBatch" type="{http://www.nrf-arts.org/IXRetail/namespace}BatchCodeType" /&gt;
     * &lt;attribute name="MerchantID" type="{http://www.nrf-arts.org/IXRetail/namespace}MerchantIDType" /&gt;
     * &lt;attribute name="STAN" type="{http://www.nrf-arts.org/IXRetail/namespace}STANtype" /&gt;
     * &lt;attribute name="APACS50TN" type="{http://www.nrf-arts.org/IXRetail/namespace}APACS50TNtype" /&gt;
     * &lt;/restriction&gt;
     * &lt;/complexContent&gt;
     * &lt;/complexType&gt;
    </pre> *
     */
    data class Terminal(
            @Attribute(name = "TerminalID", required = true)
            protected var terminalID: String,
            @Attribute(name = "TerminalBatch")
            protected var terminalBatch: String? = null,
            @Attribute(name = "MerchantID")
            protected var merchantID: String? = null,
            @Attribute(name = "STAN")
            protected var stan: Long? = null,
            @Attribute(name = "APACS50TN")
            protected var apacs50TN: BigInteger? = null)

}
