//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 04:13:46 PM CDT 
//


package com.mastercard.gateway.ats.domain;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Specifies the card identification to be transmitted to the application
 * 
 * <p>Java class for CardValueDRType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CardValueDRType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EncryptionVersion" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/&gt;
 *         &lt;element name="E2EEEncValues" type="{http://www.nrf-arts.org/IXRetail/namespace}E2EEValues" minOccurs="0"/&gt;
 *         &lt;element name="P2PEEncValues" type="{http://www.nrf-arts.org/IXRetail/namespace}P2PEValues" minOccurs="0"/&gt;
 *         &lt;element name="Track2" type="{http://www.nrf-arts.org/IXRetail/namespace}CardTrack" minOccurs="0"/&gt;
 *         &lt;element name="CardPAN" type="{http://www.nrf-arts.org/IXRetail/namespace}CardPANType" minOccurs="0"/&gt;
 *         &lt;element name="CADLuhn" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="Mod10" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                 &lt;attribute name="Mod11" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                 &lt;attribute name="MC" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                 &lt;attribute name="BPA" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                 &lt;attribute name="BPARearranged" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="StartDate" type="{http://www.nrf-arts.org/IXRetail/namespace}CardDate" minOccurs="0"/&gt;
 *         &lt;element name="ExpiryDate" type="{http://www.nrf-arts.org/IXRetail/namespace}CardDate" minOccurs="0"/&gt;
 *         &lt;element name="CardCircuit" type="{http://www.nrf-arts.org/IXRetail/namespace}CardCircuitType" minOccurs="0"/&gt;
 *         &lt;element name="IssueNumber" type="{http://www.nrf-arts.org/IXRetail/namespace}IssueNumberType" minOccurs="0"/&gt;
 *         &lt;element name="ServiceCode" type="{http://www.nrf-arts.org/IXRetail/namespace}ServiceCodeType" minOccurs="0"/&gt;
 *         &lt;element name="Token" type="{http://www.nrf-arts.org/IXRetail/namespace}CardTokenType" minOccurs="0"/&gt;
 *         &lt;element name="Contactless" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="CardType" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="Keyed"/&gt;
 *               &lt;enumeration value="Swiped"/&gt;
 *               &lt;enumeration value="SwipedKeyed"/&gt;
 *               &lt;enumeration value="ICC"/&gt;
 *               &lt;enumeration value="ICCSwiped"/&gt;
 *               &lt;enumeration value="ContactlessICC"/&gt;
 *               &lt;enumeration value="ContactlessSwiped"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ReadTLV" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Features" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Feature" type="{http://www.nrf-arts.org/IXRetail/namespace}CardFeatureType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="TerminalAttributes" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/&gt;
 *         &lt;element name="TerminalID" type="{http://www.nrf-arts.org/IXRetail/namespace}TerminalIDType" minOccurs="0"/&gt;
 *         &lt;element name="ReaderSerialNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ICC" type="{http://www.nrf-arts.org/IXRetail/namespace}ICCType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CardValueDRType", propOrder = {
    "encryptionVersion",
    "e2EEEncValues",
    "p2PEEncValues",
    "track2",
    "cardPAN",
    "cadLuhn",
    "startDate",
    "expiryDate",
    "cardCircuit",
    "issueNumber",
    "serviceCode",
    "token",
    "contactless",
    "cardType",
    "readTLV",
    "features",
    "terminalAttributes",
    "terminalID",
    "readerSerialNo",
    "icc"
})
public class CardValueDRType {

    @XmlElement(name = "EncryptionVersion")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger encryptionVersion;
    @XmlElement(name = "E2EEEncValues")
    protected E2EEValues e2EEEncValues;
    @XmlElement(name = "P2PEEncValues")
    protected P2PEValues p2PEEncValues;
    @XmlElement(name = "Track2")
    protected CardTrack track2;
    @XmlElement(name = "CardPAN")
    protected String cardPAN;
    @XmlElement(name = "CADLuhn")
    protected CardValueDRType.CADLuhn cadLuhn;
    @XmlElement(name = "StartDate")
    protected String startDate;
    @XmlElement(name = "ExpiryDate")
    protected String expiryDate;
    @XmlElement(name = "CardCircuit")
    protected String cardCircuit;
    @XmlElement(name = "IssueNumber")
    protected String issueNumber;
    @XmlElement(name = "ServiceCode")
    protected String serviceCode;
    @XmlElement(name = "Token")
    protected String token;
    @XmlElement(name = "Contactless")
    protected Boolean contactless;
    @XmlElement(name = "CardType")
    protected String cardType;
    @XmlElement(name = "ReadTLV")
    protected String readTLV;
    @XmlElement(name = "Features")
    protected CardValueDRType.Features features;
    @XmlElement(name = "TerminalAttributes", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] terminalAttributes;
    @XmlElement(name = "TerminalID")
    protected String terminalID;
    @XmlElement(name = "ReaderSerialNo")
    protected String readerSerialNo;
    @XmlElement(name = "ICC")
    protected ICCType icc;

    /**
     * Gets the value of the encryptionVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEncryptionVersion() {
        return encryptionVersion;
    }

    /**
     * Sets the value of the encryptionVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEncryptionVersion(BigInteger value) {
        this.encryptionVersion = value;
    }

    /**
     * Gets the value of the e2EEEncValues property.
     * 
     * @return
     *     possible object is
     *     {@link E2EEValues }
     *     
     */
    public E2EEValues getE2EEEncValues() {
        return e2EEEncValues;
    }

    /**
     * Sets the value of the e2EEEncValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link E2EEValues }
     *     
     */
    public void setE2EEEncValues(E2EEValues value) {
        this.e2EEEncValues = value;
    }

    /**
     * Gets the value of the p2PEEncValues property.
     * 
     * @return
     *     possible object is
     *     {@link P2PEValues }
     *     
     */
    public P2PEValues getP2PEEncValues() {
        return p2PEEncValues;
    }

    /**
     * Sets the value of the p2PEEncValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link P2PEValues }
     *     
     */
    public void setP2PEEncValues(P2PEValues value) {
        this.p2PEEncValues = value;
    }

    /**
     * Gets the value of the track2 property.
     * 
     * @return
     *     possible object is
     *     {@link CardTrack }
     *     
     */
    public CardTrack getTrack2() {
        return track2;
    }

    /**
     * Sets the value of the track2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardTrack }
     *     
     */
    public void setTrack2(CardTrack value) {
        this.track2 = value;
    }

    /**
     * Gets the value of the cardPAN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardPAN() {
        return cardPAN;
    }

    /**
     * Sets the value of the cardPAN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardPAN(String value) {
        this.cardPAN = value;
    }

    /**
     * Gets the value of the cadLuhn property.
     * 
     * @return
     *     possible object is
     *     {@link CADLuhn }
     *     
     */
    public CADLuhn getCADLuhn() {
        return cadLuhn;
    }

    /**
     * Sets the value of the cadLuhn property.
     * 
     * @param value
     *     allowed object is
     *     {@link CADLuhn }
     *     
     */
    public void setCADLuhn(CADLuhn value) {
        this.cadLuhn = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartDate(String value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpiryDate(String value) {
        this.expiryDate = value;
    }

    /**
     * Gets the value of the cardCircuit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardCircuit() {
        return cardCircuit;
    }

    /**
     * Sets the value of the cardCircuit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardCircuit(String value) {
        this.cardCircuit = value;
    }

    /**
     * Gets the value of the issueNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssueNumber() {
        return issueNumber;
    }

    /**
     * Sets the value of the issueNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssueNumber(String value) {
        this.issueNumber = value;
    }

    /**
     * Gets the value of the serviceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceCode() {
        return serviceCode;
    }

    /**
     * Sets the value of the serviceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceCode(String value) {
        this.serviceCode = value;
    }

    /**
     * Gets the value of the token property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToken() {
        return token;
    }

    /**
     * Sets the value of the token property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToken(String value) {
        this.token = value;
    }

    /**
     * Gets the value of the contactless property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isContactless() {
        return contactless;
    }

    /**
     * Sets the value of the contactless property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setContactless(Boolean value) {
        this.contactless = value;
    }

    /**
     * Gets the value of the cardType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * Sets the value of the cardType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardType(String value) {
        this.cardType = value;
    }

    /**
     * Gets the value of the readTLV property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReadTLV() {
        return readTLV;
    }

    /**
     * Sets the value of the readTLV property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReadTLV(String value) {
        this.readTLV = value;
    }

    /**
     * Gets the value of the features property.
     * 
     * @return
     *     possible object is
     *     {@link Features }
     *     
     */
    public Features getFeatures() {
        return features;
    }

    /**
     * Sets the value of the features property.
     * 
     * @param value
     *     allowed object is
     *     {@link Features }
     *     
     */
    public void setFeatures(Features value) {
        this.features = value;
    }

    /**
     * Gets the value of the terminalAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getTerminalAttributes() {
        return terminalAttributes;
    }

    /**
     * Sets the value of the terminalAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminalAttributes(byte[] value) {
        this.terminalAttributes = value;
    }

    /**
     * Gets the value of the terminalID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminalID() {
        return terminalID;
    }

    /**
     * Sets the value of the terminalID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminalID(String value) {
        this.terminalID = value;
    }

    /**
     * Gets the value of the readerSerialNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReaderSerialNo() {
        return readerSerialNo;
    }

    /**
     * Sets the value of the readerSerialNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReaderSerialNo(String value) {
        this.readerSerialNo = value;
    }

    /**
     * Gets the value of the icc property.
     * 
     * @return
     *     possible object is
     *     {@link ICCType }
     *     
     */
    public ICCType getICC() {
        return icc;
    }

    /**
     * Sets the value of the icc property.
     * 
     * @param value
     *     allowed object is
     *     {@link ICCType }
     *     
     */
    public void setICC(ICCType value) {
        this.icc = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="Mod10" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *       &lt;attribute name="Mod11" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *       &lt;attribute name="MC" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *       &lt;attribute name="BPA" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *       &lt;attribute name="BPARearranged" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class CADLuhn {

        @XmlAttribute(name = "Mod10")
        protected Boolean mod10;
        @XmlAttribute(name = "Mod11")
        protected Boolean mod11;
        @XmlAttribute(name = "MC")
        protected Boolean mc;
        @XmlAttribute(name = "BPA")
        protected Boolean bpa;
        @XmlAttribute(name = "BPARearranged")
        protected Boolean bpaRearranged;

        /**
         * Gets the value of the mod10 property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isMod10() {
            return mod10;
        }

        /**
         * Sets the value of the mod10 property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setMod10(Boolean value) {
            this.mod10 = value;
        }

        /**
         * Gets the value of the mod11 property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isMod11() {
            return mod11;
        }

        /**
         * Sets the value of the mod11 property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setMod11(Boolean value) {
            this.mod11 = value;
        }

        /**
         * Gets the value of the mc property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isMC() {
            return mc;
        }

        /**
         * Sets the value of the mc property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setMC(Boolean value) {
            this.mc = value;
        }

        /**
         * Gets the value of the bpa property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isBPA() {
            return bpa;
        }

        /**
         * Sets the value of the bpa property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setBPA(Boolean value) {
            this.bpa = value;
        }

        /**
         * Gets the value of the bpaRearranged property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isBPARearranged() {
            return bpaRearranged;
        }

        /**
         * Sets the value of the bpaRearranged property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setBPARearranged(Boolean value) {
            this.bpaRearranged = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Feature" type="{http://www.nrf-arts.org/IXRetail/namespace}CardFeatureType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "feature"
    })
    public static class Features {

        @XmlElement(name = "Feature")
        @XmlSchemaType(name = "string")
        protected List<CardFeatureType> feature;

        /**
         * Gets the value of the feature property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the feature property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFeature().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CardFeatureType }
         * 
         * 
         */
        public List<CardFeatureType> getFeature() {
            if (feature == null) {
                feature = new ArrayList<CardFeatureType>();
            }
            return this.feature;
        }

    }

}
