//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 04:13:46 PM CDT 
//


package com.mastercard.gateway.ats.domain


/**
 *
 * Java class for CommandType.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 *
 * <pre>
 * &lt;simpleType name="CommandType"&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 * &lt;enumeration value="GetDecimals"/&gt;
 * &lt;enumeration value="GetChar"/&gt;
 * &lt;enumeration value="GetMenu"/&gt;
 * &lt;enumeration value="GetAmount"/&gt;
 * &lt;enumeration value="GetAmountNoPrompt"/&gt;
 * &lt;enumeration value="GetConfirmation"/&gt;
 * &lt;enumeration value="GetAnyKey"/&gt;
 * &lt;enumeration value="GetOptionKey"/&gt;
 * &lt;enumeration value="CheckPIN"/&gt;
 * &lt;enumeration value="ProcessPIN"/&gt;
 * &lt;enumeration value="RequestCard"/&gt;
 * &lt;enumeration value="RequestTypeCard"/&gt;
 * &lt;enumeration value="ReadCard"/&gt;
 * &lt;enumeration value="TransferData"/&gt;
 * &lt;enumeration value="ValidateMAC"/&gt;
 * &lt;enumeration value="CalculateMAC"/&gt;
 * &lt;enumeration value="UpdateKeys"/&gt;
 * &lt;enumeration value="GetTrack2"/&gt;
 * &lt;enumeration value="Other"/&gt;
 * &lt;/restriction&gt;
 * &lt;/simpleType&gt;
</pre> *
 *
 */
enum class CommandType {

    GetDecimals,
    GetChar,
    GetMenu,
    GetAmount,
    GetAmountNoPrompt,
    GetConfirmation,
    GetAnyKey,
    GetOptionKey,
    CheckPIN,
    ProcessPIN,
    RequestCard,
    RequestTypeCard,
    ReadCard,
    TransferData,
    ValidateMAC,
    CalculateMAC,
    UpdateKeys,
    GetTrack2,
    /**
     * To explicitly address the possibility to extend the commands according to each supplier pin-pad implementation.
     * PinPad independence will be subject for future extension of the interface.
     *
     */
    Other
}
