//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 04:13:46 PM CDT 
//


package com.mastercard.gateway.ats.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CommandType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CommandType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="GetDecimals"/&gt;
 *     &lt;enumeration value="GetChar"/&gt;
 *     &lt;enumeration value="GetMenu"/&gt;
 *     &lt;enumeration value="GetAmount"/&gt;
 *     &lt;enumeration value="GetAmountNoPrompt"/&gt;
 *     &lt;enumeration value="GetConfirmation"/&gt;
 *     &lt;enumeration value="GetAnyKey"/&gt;
 *     &lt;enumeration value="GetOptionKey"/&gt;
 *     &lt;enumeration value="CheckPIN"/&gt;
 *     &lt;enumeration value="ProcessPIN"/&gt;
 *     &lt;enumeration value="RequestCard"/&gt;
 *     &lt;enumeration value="RequestTypeCard"/&gt;
 *     &lt;enumeration value="ReadCard"/&gt;
 *     &lt;enumeration value="TransferData"/&gt;
 *     &lt;enumeration value="ValidateMAC"/&gt;
 *     &lt;enumeration value="CalculateMAC"/&gt;
 *     &lt;enumeration value="UpdateKeys"/&gt;
 *     &lt;enumeration value="GetTrack2"/&gt;
 *     &lt;enumeration value="Other"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CommandType")
@XmlEnum
public enum CommandType {

    @XmlEnumValue("GetDecimals")
    GET_DECIMALS("GetDecimals"),
    @XmlEnumValue("GetChar")
    GET_CHAR("GetChar"),
    @XmlEnumValue("GetMenu")
    GET_MENU("GetMenu"),
    @XmlEnumValue("GetAmount")
    GET_AMOUNT("GetAmount"),
    @XmlEnumValue("GetAmountNoPrompt")
    GET_AMOUNT_NO_PROMPT("GetAmountNoPrompt"),
    @XmlEnumValue("GetConfirmation")
    GET_CONFIRMATION("GetConfirmation"),
    @XmlEnumValue("GetAnyKey")
    GET_ANY_KEY("GetAnyKey"),
    @XmlEnumValue("GetOptionKey")
    GET_OPTION_KEY("GetOptionKey"),
    @XmlEnumValue("CheckPIN")
    CHECK_PIN("CheckPIN"),
    @XmlEnumValue("ProcessPIN")
    PROCESS_PIN("ProcessPIN"),
    @XmlEnumValue("RequestCard")
    REQUEST_CARD("RequestCard"),
    @XmlEnumValue("RequestTypeCard")
    REQUEST_TYPE_CARD("RequestTypeCard"),
    @XmlEnumValue("ReadCard")
    READ_CARD("ReadCard"),
    @XmlEnumValue("TransferData")
    TRANSFER_DATA("TransferData"),
    @XmlEnumValue("ValidateMAC")
    VALIDATE_MAC("ValidateMAC"),
    @XmlEnumValue("CalculateMAC")
    CALCULATE_MAC("CalculateMAC"),
    @XmlEnumValue("UpdateKeys")
    UPDATE_KEYS("UpdateKeys"),
    @XmlEnumValue("GetTrack2")
    GET_TRACK_2("GetTrack2"),

    /**
     * To explicitly address the possibility to extend the commands according to each supplier pin-pad implementation.
     * PinPad independence will be subject for future extension of the interface.
     * 
     */
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    CommandType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CommandType fromValue(String v) {
        for (CommandType c: CommandType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
