//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 04:13:46 PM CDT 
//


package com.mastercard.gateway.ats.domain

/**
 *
 * Java class for DataRequiredType.
 *
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 *
 * <pre>
 * &lt;simpleType name="DataRequiredType"&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 * &lt;enumeration value="Track2"/&gt;
 * &lt;enumeration value="PAN"/&gt;
 * &lt;enumeration value="ExpiryDate"/&gt;
 * &lt;enumeration value="StartDate"/&gt;
 * &lt;enumeration value="IssueNumber"/&gt;
 * &lt;enumeration value="Signature"/&gt;
 * &lt;enumeration value="Cashback"/&gt;
 * &lt;enumeration value="SplitPayment"/&gt;
 * &lt;enumeration value="Gratuity"/&gt;
 * &lt;enumeration value="Donation"/&gt;
 * &lt;enumeration value="Amount"/&gt;
 * &lt;enumeration value="Products"/&gt;
 * &lt;enumeration value="Mileage"/&gt;
 * &lt;enumeration value="Registration"/&gt;
 * &lt;enumeration value="Id"/&gt;
 * &lt;enumeration value="Supplementary"/&gt;
 * &lt;enumeration value="AuthCode"/&gt;
 * &lt;enumeration value="CV2"/&gt;
 * &lt;enumeration value="PostCode"/&gt;
 * &lt;enumeration value="Address"/&gt;
 * &lt;enumeration value="FailureAcknowledgement"/&gt;
 * &lt;enumeration value="ETUProvider"/&gt;
 * &lt;enumeration value="ETUPlan"/&gt;
 * &lt;enumeration value="ETUAmount"/&gt;
 * &lt;enumeration value="DataNotChecked"/&gt;
 * &lt;enumeration value="AllMatch"/&gt;
 * &lt;enumeration value="SecurityCodeMatchOnly"/&gt;
 * &lt;enumeration value="AddressMatchOnly"/&gt;
 * &lt;enumeration value="NoDataMatches"/&gt;
 * &lt;enumeration value="FallbackPKE"/&gt;
 * &lt;enumeration value="PrintDone"/&gt;
 * &lt;enumeration value="PrintRetry"/&gt;
 * &lt;enumeration value="DCCQuery"/&gt;
 * &lt;enumeration value="DCCConfirm"/&gt;
 * &lt;enumeration value="Transaction"/&gt;
 * &lt;enumeration value="Password"/&gt;
 * &lt;/restriction&gt;
 * &lt;/simpleType&gt;
</pre> *
 */
enum class DataRequiredType {
    Track2,
    PAN,
    ExpiryDate,
    StartDate,
    IssueNumber,
    Signature,
    Cashback,
    SplitPayment,
    Gratuity,
    Donation,
    Amount,
    Products,
    Mileage,
    Registration,
    Id,
    Supplementary,
    AuthCode,
    CV2,
    PostCode,
    Address,
    FailureAcknowledgement,
    ETUProvider,
    ETUPlan,
    ETUAmount,
    DataNotChecked,
    AllMatch,
    SecurityCodeMatchOnly,
    AddressMatchOnly,
    NoDataMatches,
    FallbackPKE,
    PrintDone,
    PrintRetry,
    DCCQuery,
    DCCConfirm,
    Transaction,
    Password
}
