//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 04:13:46 PM CDT 
//


package com.mastercard.gateway.ats.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataRequiredType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DataRequiredType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Track2"/&gt;
 *     &lt;enumeration value="PAN"/&gt;
 *     &lt;enumeration value="ExpiryDate"/&gt;
 *     &lt;enumeration value="StartDate"/&gt;
 *     &lt;enumeration value="IssueNumber"/&gt;
 *     &lt;enumeration value="Signature"/&gt;
 *     &lt;enumeration value="Cashback"/&gt;
 *     &lt;enumeration value="SplitPayment"/&gt;
 *     &lt;enumeration value="Gratuity"/&gt;
 *     &lt;enumeration value="Donation"/&gt;
 *     &lt;enumeration value="Amount"/&gt;
 *     &lt;enumeration value="Products"/&gt;
 *     &lt;enumeration value="Mileage"/&gt;
 *     &lt;enumeration value="Registration"/&gt;
 *     &lt;enumeration value="Id"/&gt;
 *     &lt;enumeration value="Supplementary"/&gt;
 *     &lt;enumeration value="AuthCode"/&gt;
 *     &lt;enumeration value="CV2"/&gt;
 *     &lt;enumeration value="PostCode"/&gt;
 *     &lt;enumeration value="Address"/&gt;
 *     &lt;enumeration value="FailureAcknowledgement"/&gt;
 *     &lt;enumeration value="ETUProvider"/&gt;
 *     &lt;enumeration value="ETUPlan"/&gt;
 *     &lt;enumeration value="ETUAmount"/&gt;
 *     &lt;enumeration value="DataNotChecked"/&gt;
 *     &lt;enumeration value="AllMatch"/&gt;
 *     &lt;enumeration value="SecurityCodeMatchOnly"/&gt;
 *     &lt;enumeration value="AddressMatchOnly"/&gt;
 *     &lt;enumeration value="NoDataMatches"/&gt;
 *     &lt;enumeration value="FallbackPKE"/&gt;
 *     &lt;enumeration value="PrintDone"/&gt;
 *     &lt;enumeration value="PrintRetry"/&gt;
 *     &lt;enumeration value="DCCQuery"/&gt;
 *     &lt;enumeration value="DCCConfirm"/&gt;
 *     &lt;enumeration value="Transaction"/&gt;
 *     &lt;enumeration value="Password"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "DataRequiredType")
@XmlEnum
public enum DataRequiredType {

    @XmlEnumValue("Track2")
    TRACK_2("Track2"),
    PAN("PAN"),
    @XmlEnumValue("ExpiryDate")
    EXPIRY_DATE("ExpiryDate"),
    @XmlEnumValue("StartDate")
    START_DATE("StartDate"),
    @XmlEnumValue("IssueNumber")
    ISSUE_NUMBER("IssueNumber"),
    @XmlEnumValue("Signature")
    SIGNATURE("Signature"),
    @XmlEnumValue("Cashback")
    CASHBACK("Cashback"),
    @XmlEnumValue("SplitPayment")
    SPLIT_PAYMENT("SplitPayment"),
    @XmlEnumValue("Gratuity")
    GRATUITY("Gratuity"),
    @XmlEnumValue("Donation")
    DONATION("Donation"),
    @XmlEnumValue("Amount")
    AMOUNT("Amount"),
    @XmlEnumValue("Products")
    PRODUCTS("Products"),
    @XmlEnumValue("Mileage")
    MILEAGE("Mileage"),
    @XmlEnumValue("Registration")
    REGISTRATION("Registration"),
    @XmlEnumValue("Id")
    ID("Id"),
    @XmlEnumValue("Supplementary")
    SUPPLEMENTARY("Supplementary"),
    @XmlEnumValue("AuthCode")
    AUTH_CODE("AuthCode"),
    @XmlEnumValue("CV2")
    CV_2("CV2"),
    @XmlEnumValue("PostCode")
    POST_CODE("PostCode"),
    @XmlEnumValue("Address")
    ADDRESS("Address"),
    @XmlEnumValue("FailureAcknowledgement")
    FAILURE_ACKNOWLEDGEMENT("FailureAcknowledgement"),
    @XmlEnumValue("ETUProvider")
    ETU_PROVIDER("ETUProvider"),
    @XmlEnumValue("ETUPlan")
    ETU_PLAN("ETUPlan"),
    @XmlEnumValue("ETUAmount")
    ETU_AMOUNT("ETUAmount"),
    @XmlEnumValue("DataNotChecked")
    DATA_NOT_CHECKED("DataNotChecked"),
    @XmlEnumValue("AllMatch")
    ALL_MATCH("AllMatch"),
    @XmlEnumValue("SecurityCodeMatchOnly")
    SECURITY_CODE_MATCH_ONLY("SecurityCodeMatchOnly"),
    @XmlEnumValue("AddressMatchOnly")
    ADDRESS_MATCH_ONLY("AddressMatchOnly"),
    @XmlEnumValue("NoDataMatches")
    NO_DATA_MATCHES("NoDataMatches"),
    @XmlEnumValue("FallbackPKE")
    FALLBACK_PKE("FallbackPKE"),
    @XmlEnumValue("PrintDone")
    PRINT_DONE("PrintDone"),
    @XmlEnumValue("PrintRetry")
    PRINT_RETRY("PrintRetry"),
    @XmlEnumValue("DCCQuery")
    DCC_QUERY("DCCQuery"),
    @XmlEnumValue("DCCConfirm")
    DCC_CONFIRM("DCCConfirm"),
    @XmlEnumValue("Transaction")
    TRANSACTION("Transaction"),
    @XmlEnumValue("Password")
    PASSWORD("Password");
    private final String value;

    DataRequiredType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DataRequiredType fromValue(String v) {
        for (DataRequiredType c: DataRequiredType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
