//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 04:13:46 PM CDT 
//


package com.mastercard.gateway.ats.domain

import org.simpleframework.xml.Attribute
import org.simpleframework.xml.Element
import org.simpleframework.xml.Order
import org.simpleframework.xml.Root

import java.math.BigDecimal
import java.math.BigInteger


/**
 *
 * Java class for anonymous complex type.
 *
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 *
 * <pre>
 * &lt;complexType&gt;
 * &lt;complexContent&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 * &lt;sequence&gt;
 * &lt;element name="Output" maxOccurs="2" minOccurs="0"&gt;
 * &lt;complexType&gt;
 * &lt;complexContent&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 * &lt;attribute name="OutDeviceTarget" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}DeviceType" /&gt;
 * &lt;attribute name="OutResult" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}RequestResultType" /&gt;
 * &lt;/restriction&gt;
 * &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * &lt;/element&gt;
 * &lt;element name="Input" minOccurs="0"&gt;
 * &lt;complexType&gt;
 * &lt;complexContent&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 * &lt;sequence&gt;
 * &lt;element name="SecureData" type="{http://www.nrf-arts.org/IXRetail/namespace}SecureDataFlow" maxOccurs="unbounded" minOccurs="0"/&gt;
 * &lt;element name="InputValue" type="{http://www.nrf-arts.org/IXRetail/namespace}InputValueType" minOccurs="0"/&gt;
 * &lt;/sequence&gt;
 * &lt;attribute name="InDeviceTarget" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}DeviceType" /&gt;
 * &lt;attribute name="InResult" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}RequestResultType" /&gt;
 * &lt;/restriction&gt;
 * &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * &lt;/element&gt;
 * &lt;element name="EventResult" minOccurs="0"&gt;
 * &lt;complexType&gt;
 * &lt;complexContent&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 * &lt;sequence&gt;
 * &lt;element name="Dispenser" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" maxOccurs="unbounded" minOccurs="0"/&gt;
 * &lt;element name="ProductCode" type="{http://www.nrf-arts.org/IXRetail/namespace}ProductGroupType" maxOccurs="unbounded" minOccurs="0"/&gt;
 * &lt;element name="ModifiedRequest" type="{http://www.nrf-arts.org/IXRetail/namespace}CardRequestType" minOccurs="0"/&gt;
 * &lt;element name="TotalAmount" type="{http://www.nrf-arts.org/IXRetail/namespace}TotalAmountType" minOccurs="0"/&gt;
 * &lt;element name="SaleItem" type="{http://www.nrf-arts.org/IXRetail/namespace}SaleItemType" maxOccurs="9999" minOccurs="0"/&gt;
 * &lt;element name="Acquirer" minOccurs="0"&gt;
 * &lt;complexType&gt;
 * &lt;complexContent&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 * &lt;attribute name="MerchantID" type="{http://www.nrf-arts.org/IXRetail/namespace}MerchantIDType" /&gt;
 * &lt;attribute name="AcquirerID" type="{http://www.nrf-arts.org/IXRetail/namespace}AcquirerType" /&gt;
 * &lt;attribute name="MerchantReference" type="{http://www.nrf-arts.org/IXRetail/namespace}MerchantReferenceType" /&gt;
 * &lt;attribute name="CreditPlan" type="{http://www.nrf-arts.org/IXRetail/namespace}CreditPlanType" /&gt;
 * &lt;/restriction&gt;
 * &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * &lt;/element&gt;
 * &lt;element name="AuthResponse" minOccurs="0"&gt;
 * &lt;complexType&gt;
 * &lt;complexContent&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 * &lt;sequence&gt;
 * &lt;element name="AuthARC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 * &lt;element name="AuthCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 * &lt;element name="AuthResult" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 * &lt;element name="ICC" type="{http://www.nrf-arts.org/IXRetail/namespace}ICCType" minOccurs="0"/&gt;
 * &lt;/sequence&gt;
 * &lt;/restriction&gt;
 * &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * &lt;/element&gt;
 * &lt;element name="TransactionLimits" minOccurs="0"&gt;
 * &lt;complexType&gt;
 * &lt;complexContent&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 * &lt;sequence&gt;
 * &lt;element name="AuthFlags" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 * &lt;element name="LimitFloor" type="{http://www.nrf-arts.org/IXRetail/namespace}MonetaryAmount" minOccurs="0"/&gt;
 * &lt;element name="LimitPostComms" type="{http://www.nrf-arts.org/IXRetail/namespace}MonetaryAmount" minOccurs="0"/&gt;
 * &lt;element name="Ceiling" type="{http://www.nrf-arts.org/IXRetail/namespace}MonetaryAmount" minOccurs="0"/&gt;
 * &lt;element name="CeilingCDCVM" type="{http://www.nrf-arts.org/IXRetail/namespace}MonetaryAmount" minOccurs="0"/&gt;
 * &lt;element name="CeilingCash" type="{http://www.nrf-arts.org/IXRetail/namespace}MonetaryAmount" minOccurs="0"/&gt;
 * &lt;element name="CeilingFPA" type="{http://www.nrf-arts.org/IXRetail/namespace}MonetaryAmount" minOccurs="0"/&gt;
 * &lt;element name="ReadTLV" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/&gt;
 * &lt;/sequence&gt;
 * &lt;/restriction&gt;
 * &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * &lt;/element&gt;
 * &lt;element name="OACentreDetails" minOccurs="0"&gt;
 * &lt;complexType&gt;
 * &lt;complexContent&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 * &lt;sequence&gt;
 * &lt;element name="OACentreName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 * &lt;element name="RefundOnline" type="{http://www.nrf-arts.org/IXRetail/namespace}OARefundOnline" minOccurs="0"/&gt;
 * &lt;element name="RefundOnlineCtls" type="{http://www.nrf-arts.org/IXRetail/namespace}OARefundOnline" minOccurs="0"/&gt;
 * &lt;element name="ReversalMode" type="{http://www.nrf-arts.org/IXRetail/namespace}OAReversalMode" minOccurs="0"/&gt;
 * &lt;element name="ReverseOnline" type="{http://www.nrf-arts.org/IXRetail/namespace}OAReverseOnline" minOccurs="0"/&gt;
 * &lt;element name="ICCNoTrack2" type="{http://www.nrf-arts.org/IXRetail/namespace}OAICCNoTrack2" minOccurs="0"/&gt;
 * &lt;/sequence&gt;
 * &lt;/restriction&gt;
 * &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * &lt;/element&gt;
 * &lt;/sequence&gt;
 * &lt;/restriction&gt;
 * &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * &lt;/element&gt;
 * &lt;element name="ErrorDetail" type="{http://www.nrf-arts.org/IXRetail/namespace}ATSErrorDetailType" minOccurs="0"/&gt;
 * &lt;/sequence&gt;
 * &lt;attribute name="RequestType" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}DeviceRequestType" /&gt;
 * &lt;attribute name="ApplicationSender" type="{http://www.nrf-arts.org/IXRetail/namespace}ApplicationType" /&gt;
 * &lt;attribute name="WorkstationID" type="{http://www.nrf-arts.org/IXRetail/namespace}WorkstationIDType" /&gt;
 * &lt;attribute name="TerminalID" type="{http://www.nrf-arts.org/IXRetail/namespace}TerminalIDType" /&gt;
 * &lt;attribute name="POPID" type="{http://www.nrf-arts.org/IXRetail/namespace}POPIDType" /&gt;
 * &lt;attribute name="RequestID" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}RequestIDType" /&gt;
 * &lt;attribute name="SequenceID" type="{http://www.nrf-arts.org/IXRetail/namespace}SequenceIDType" /&gt;
 * &lt;attribute name="ReferenceRequestID" type="{http://www.nrf-arts.org/IXRetail/namespace}RequestIDType" /&gt;
 * &lt;attribute name="OverallResult" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}RequestResultType" /&gt;
 * &lt;/restriction&gt;
 * &lt;/complexContent&gt;
 * &lt;/complexType&gt;
</pre> *
 */

@Root(name = "DeviceResponse", strict = false)
@Order(elements = ["output", "input", "eventResult", "errorDetail"])
data class DeviceResponse(

        @Element(name = "Output")
        var output: List<Output>? = null,
        @Element(name = "Input")
        var input: DeviceResponse.Input? = null,
        @Element(name = "EventResult")
        var eventResult: DeviceResponse.EventResult? = null,
        @Element(name = "ErrorDetail")
        var errorDetail: ATSErrorDetailType? = null,
        @Attribute(name = "RequestType", required = true)
        var requestType: DeviceRequestType,
        @Attribute(name = "ApplicationSender")
        var applicationSender: String? = null,
        @Attribute(name = "WorkstationID")
        var workstationID: String? = null,
        @Attribute(name = "TerminalID")
        var terminalID: String? = null,
        @Attribute(name = "POPID")
        var popid: String? = null,
        @Attribute(name = "RequestID", required = true)
        var requestID: String,
        @Attribute(name = "SequenceID")
        var sequenceID: Int? = null,
        @Attribute(name = "ReferenceRequestID")
        var referenceRequestID: String? = null,
        @Attribute(name = "OverallResult", required = true)
        var overallResult: RequestResultType) {

    /**
     *
     * Java class for anonymous complex type.
     *
     *
     *
     * The following schema fragment specifies the expected content contained within this class.
     *
     *
     * <pre>
     * &lt;complexType&gt;
     * &lt;complexContent&gt;
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     * &lt;sequence&gt;
     * &lt;element name="Dispenser" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" maxOccurs="unbounded" minOccurs="0"/&gt;
     * &lt;element name="ProductCode" type="{http://www.nrf-arts.org/IXRetail/namespace}ProductGroupType" maxOccurs="unbounded" minOccurs="0"/&gt;
     * &lt;element name="ModifiedRequest" type="{http://www.nrf-arts.org/IXRetail/namespace}CardRequestType" minOccurs="0"/&gt;
     * &lt;element name="TotalAmount" type="{http://www.nrf-arts.org/IXRetail/namespace}TotalAmountType" minOccurs="0"/&gt;
     * &lt;element name="SaleItem" type="{http://www.nrf-arts.org/IXRetail/namespace}SaleItemType" maxOccurs="9999" minOccurs="0"/&gt;
     * &lt;element name="Acquirer" minOccurs="0"&gt;
     * &lt;complexType&gt;
     * &lt;complexContent&gt;
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     * &lt;attribute name="MerchantID" type="{http://www.nrf-arts.org/IXRetail/namespace}MerchantIDType" /&gt;
     * &lt;attribute name="AcquirerID" type="{http://www.nrf-arts.org/IXRetail/namespace}AcquirerType" /&gt;
     * &lt;attribute name="MerchantReference" type="{http://www.nrf-arts.org/IXRetail/namespace}MerchantReferenceType" /&gt;
     * &lt;attribute name="CreditPlan" type="{http://www.nrf-arts.org/IXRetail/namespace}CreditPlanType" /&gt;
     * &lt;/restriction&gt;
     * &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * &lt;/element&gt;
     * &lt;element name="AuthResponse" minOccurs="0"&gt;
     * &lt;complexType&gt;
     * &lt;complexContent&gt;
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     * &lt;sequence&gt;
     * &lt;element name="AuthARC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     * &lt;element name="AuthCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     * &lt;element name="AuthResult" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     * &lt;element name="ICC" type="{http://www.nrf-arts.org/IXRetail/namespace}ICCType" minOccurs="0"/&gt;
     * &lt;/sequence&gt;
     * &lt;/restriction&gt;
     * &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * &lt;/element&gt;
     * &lt;element name="TransactionLimits" minOccurs="0"&gt;
     * &lt;complexType&gt;
     * &lt;complexContent&gt;
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     * &lt;sequence&gt;
     * &lt;element name="AuthFlags" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     * &lt;element name="LimitFloor" type="{http://www.nrf-arts.org/IXRetail/namespace}MonetaryAmount" minOccurs="0"/&gt;
     * &lt;element name="LimitPostComms" type="{http://www.nrf-arts.org/IXRetail/namespace}MonetaryAmount" minOccurs="0"/&gt;
     * &lt;element name="Ceiling" type="{http://www.nrf-arts.org/IXRetail/namespace}MonetaryAmount" minOccurs="0"/&gt;
     * &lt;element name="CeilingCDCVM" type="{http://www.nrf-arts.org/IXRetail/namespace}MonetaryAmount" minOccurs="0"/&gt;
     * &lt;element name="CeilingCash" type="{http://www.nrf-arts.org/IXRetail/namespace}MonetaryAmount" minOccurs="0"/&gt;
     * &lt;element name="CeilingFPA" type="{http://www.nrf-arts.org/IXRetail/namespace}MonetaryAmount" minOccurs="0"/&gt;
     * &lt;element name="ReadTLV" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/&gt;
     * &lt;/sequence&gt;
     * &lt;/restriction&gt;
     * &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * &lt;/element&gt;
     * &lt;element name="OACentreDetails" minOccurs="0"&gt;
     * &lt;complexType&gt;
     * &lt;complexContent&gt;
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     * &lt;sequence&gt;
     * &lt;element name="OACentreName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     * &lt;element name="RefundOnline" type="{http://www.nrf-arts.org/IXRetail/namespace}OARefundOnline" minOccurs="0"/&gt;
     * &lt;element name="RefundOnlineCtls" type="{http://www.nrf-arts.org/IXRetail/namespace}OARefundOnline" minOccurs="0"/&gt;
     * &lt;element name="ReversalMode" type="{http://www.nrf-arts.org/IXRetail/namespace}OAReversalMode" minOccurs="0"/&gt;
     * &lt;element name="ReverseOnline" type="{http://www.nrf-arts.org/IXRetail/namespace}OAReverseOnline" minOccurs="0"/&gt;
     * &lt;element name="ICCNoTrack2" type="{http://www.nrf-arts.org/IXRetail/namespace}OAICCNoTrack2" minOccurs="0"/&gt;
     * &lt;/sequence&gt;
     * &lt;/restriction&gt;
     * &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * &lt;/element&gt;
     * &lt;/sequence&gt;
     * &lt;/restriction&gt;
     * &lt;/complexContent&gt;
     * &lt;/complexType&gt;
    </pre> *
     */
    @Order(elements = ["dispenser", "productCode", "modifiedRequest", "totalAmount", "saleItem", "acquirer", "authResponse", "transactionLimits", "oaCentreDetails"])
    data class EventResult(
            @Element(name = "Dispenser", type = Short::class)
            var dispenser: List<Short>? = null,
            @Element(name = "ProductCode")
            var productCode: List<BigInteger>? = null,
            @Element(name = "ModifiedRequest")
            var modifiedRequest: CardRequestType? = null,
            @Element(name = "TotalAmount")
            var totalAmount: TotalAmountType? = null,
            @Element(name = "SaleItem")
            var saleItem: List<SaleItemType>? = null,
            @Element(name = "Acquirer")
            var acquirer: DeviceResponse.EventResult.Acquirer? = null,
            @Element(name = "AuthResponse")
            var authResponse: DeviceResponse.EventResult.AuthResponse? = null,
            @Element(name = "TransactionLimits")
            var transactionLimits: DeviceResponse.EventResult.TransactionLimits? = null,
            @Element(name = "OACentreDetails")
            var oaCentreDetails: DeviceResponse.EventResult.OACentreDetails? = null) {

        /**
         *
         * Java class for anonymous complex type.
         *
         *
         *
         * The following schema fragment specifies the expected content contained within this class.
         *
         *
         * <pre>
         * &lt;complexType&gt;
         * &lt;complexContent&gt;
         * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         * &lt;attribute name="MerchantID" type="{http://www.nrf-arts.org/IXRetail/namespace}MerchantIDType" /&gt;
         * &lt;attribute name="AcquirerID" type="{http://www.nrf-arts.org/IXRetail/namespace}AcquirerType" /&gt;
         * &lt;attribute name="MerchantReference" type="{http://www.nrf-arts.org/IXRetail/namespace}MerchantReferenceType" /&gt;
         * &lt;attribute name="CreditPlan" type="{http://www.nrf-arts.org/IXRetail/namespace}CreditPlanType" /&gt;
         * &lt;/restriction&gt;
         * &lt;/complexContent&gt;
         * &lt;/complexType&gt;
        </pre> *
         */
        data class Acquirer(
                @Attribute(name = "MerchantID")
                var merchantID: String? = null,
                @Attribute(name = "AcquirerID")
                var acquirerID: String? = null,
                @Attribute(name = "MerchantReference")
                var merchantReference: String? = null,
                @Attribute(name = "CreditPlan")
                var creditPlan: String? = null)

        /**
         *
         * Java class for anonymous complex type.
         *
         *
         *
         * The following schema fragment specifies the expected content contained within this class.
         *
         *
         * <pre>
         * &lt;complexType&gt;
         * &lt;complexContent&gt;
         * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         * &lt;sequence&gt;
         * &lt;element name="AuthARC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         * &lt;element name="AuthCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         * &lt;element name="AuthResult" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         * &lt;element name="ICC" type="{http://www.nrf-arts.org/IXRetail/namespace}ICCType" minOccurs="0"/&gt;
         * &lt;/sequence&gt;
         * &lt;/restriction&gt;
         * &lt;/complexContent&gt;
         * &lt;/complexType&gt;
        </pre> *
         */
        @Order(elements = ["authARC", "authCode", "authResult", "icc"])
        data class AuthResponse(
                @Element(name = "AuthARC")
                var authARC: String? = null,
                @Element(name = "AuthCode")
                var authCode: String? = null,
                @Element(name = "AuthResult")
                var authResult: String? = null,
                @Element(name = "ICC")
                var icc: ICCType? = null)

        /**
         *
         * Java class for anonymous complex type.
         *
         *
         *
         * The following schema fragment specifies the expected content contained within this class.
         *
         *
         * <pre>
         * &lt;complexType&gt;
         * &lt;complexContent&gt;
         * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         * &lt;sequence&gt;
         * &lt;element name="OACentreName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         * &lt;element name="RefundOnline" type="{http://www.nrf-arts.org/IXRetail/namespace}OARefundOnline" minOccurs="0"/&gt;
         * &lt;element name="RefundOnlineCtls" type="{http://www.nrf-arts.org/IXRetail/namespace}OARefundOnline" minOccurs="0"/&gt;
         * &lt;element name="ReversalMode" type="{http://www.nrf-arts.org/IXRetail/namespace}OAReversalMode" minOccurs="0"/&gt;
         * &lt;element name="ReverseOnline" type="{http://www.nrf-arts.org/IXRetail/namespace}OAReverseOnline" minOccurs="0"/&gt;
         * &lt;element name="ICCNoTrack2" type="{http://www.nrf-arts.org/IXRetail/namespace}OAICCNoTrack2" minOccurs="0"/&gt;
         * &lt;/sequence&gt;
         * &lt;/restriction&gt;
         * &lt;/complexContent&gt;
         * &lt;/complexType&gt;
        </pre> *
         */
        @Order(elements = ["oaCentreName", "refundOnline", "refundOnlineCtls", "reversalMode", "reverseOnline", "iccNoTrack2"])
        data class OACentreDetails(
                @Element(name = "OACentreName")
                var oaCentreName: String? = null,
                @Element(name = "RefundOnline")
                var refundOnline: OARefundOnline? = null,
                @Element(name = "RefundOnlineCtls")
                var refundOnlineCtls: OARefundOnline? = null,
                @Element(name = "ReversalMode")
                var reversalMode: OAReversalMode? = null,
                @Element(name = "ReverseOnline")
                var reverseOnline: OAReverseOnline? = null,
                @Element(name = "ICCNoTrack2")
                var iccNoTrack2: OAICCNoTrack2? = null)

        /**
         *
         * Java class for anonymous complex type.
         *
         *
         *
         * The following schema fragment specifies the expected content contained within this class.
         *
         *
         * <pre>
         * &lt;complexType&gt;
         * &lt;complexContent&gt;
         * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         * &lt;sequence&gt;
         * &lt;element name="AuthFlags" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         * &lt;element name="LimitFloor" type="{http://www.nrf-arts.org/IXRetail/namespace}MonetaryAmount" minOccurs="0"/&gt;
         * &lt;element name="LimitPostComms" type="{http://www.nrf-arts.org/IXRetail/namespace}MonetaryAmount" minOccurs="0"/&gt;
         * &lt;element name="Ceiling" type="{http://www.nrf-arts.org/IXRetail/namespace}MonetaryAmount" minOccurs="0"/&gt;
         * &lt;element name="CeilingCDCVM" type="{http://www.nrf-arts.org/IXRetail/namespace}MonetaryAmount" minOccurs="0"/&gt;
         * &lt;element name="CeilingCash" type="{http://www.nrf-arts.org/IXRetail/namespace}MonetaryAmount" minOccurs="0"/&gt;
         * &lt;element name="CeilingFPA" type="{http://www.nrf-arts.org/IXRetail/namespace}MonetaryAmount" minOccurs="0"/&gt;
         * &lt;element name="ReadTLV" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/&gt;
         * &lt;/sequence&gt;
         * &lt;/restriction&gt;
         * &lt;/complexContent&gt;
         * &lt;/complexType&gt;
        </pre> *
         */
        @Order(elements = ["authFlags", "limitFloor", "limitPostComms", "ceiling", "ceilingCDCVM", "ceilingCash", "ceilingFPA", "readTLV"])
        data class TransactionLimits(
                @Element(name = "AuthFlags")
                var authFlags: String? = null,
                @Element(name = "LimitFloor")
                var limitFloor: BigDecimal? = null,
                @Element(name = "LimitPostComms")
                var limitPostComms: BigDecimal? = null,
                @Element(name = "Ceiling")
                var ceiling: BigDecimal? = null,
                @Element(name = "CeilingCDCVM")
                var ceilingCDCVM: BigDecimal? = null,
                @Element(name = "CeilingCash")
                var ceilingCash: BigDecimal? = null,
                @Element(name = "CeilingFPA")
                var ceilingFPA: BigDecimal? = null,
                @Element(name = "ReadTLV")
                var readTLV: BigInteger? = null)

    }

    /**
     *
     * Java class for anonymous complex type.
     *
     *
     *
     * The following schema fragment specifies the expected content contained within this class.
     *
     *
     * <pre>
     * &lt;complexType&gt;
     * &lt;complexContent&gt;
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     * &lt;sequence&gt;
     * &lt;element name="SecureData" type="{http://www.nrf-arts.org/IXRetail/namespace}SecureDataFlow" maxOccurs="unbounded" minOccurs="0"/&gt;
     * &lt;element name="InputValue" type="{http://www.nrf-arts.org/IXRetail/namespace}InputValueType" minOccurs="0"/&gt;
     * &lt;/sequence&gt;
     * &lt;attribute name="InDeviceTarget" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}DeviceType" /&gt;
     * &lt;attribute name="InResult" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}RequestResultType" /&gt;
     * &lt;/restriction&gt;
     * &lt;/complexContent&gt;
     * &lt;/complexType&gt;
    </pre> *
     */
    @Order(elements = ["secureData", "inputValue"])
    data class Input (
        @Element(name = "SecureData")
        var secureData: List<SecureDataFlow>? = null,
        @Element(name = "InputValue")
        var inputValue: InputValueType? = null,
        @Attribute(name = "InDeviceTarget", required = true)
        var inDeviceTarget: DeviceType,
        @Attribute(name = "InResult", required = true)
        var inResult: RequestResultType)

    /**
     *
     * Java class for anonymous complex type.
     *
     *
     *
     * The following schema fragment specifies the expected content contained within this class.
     *
     *
     * <pre>
     * &lt;complexType&gt;
     * &lt;complexContent&gt;
     * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     * &lt;attribute name="OutDeviceTarget" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}DeviceType" /&gt;
     * &lt;attribute name="OutResult" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}RequestResultType" /&gt;
     * &lt;/restriction&gt;
     * &lt;/complexContent&gt;
     * &lt;/complexType&gt;
    </pre> *
     */
    data class Output(
        @Attribute(name = "OutDeviceTarget", required = true)
        var outDeviceTarget: DeviceType,
        @Attribute(name = "OutResult", required = true)
        var outResult: RequestResultType)

}
