//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 04:13:46 PM CDT 
//


package com.mastercard.gateway.ats.domain


/**
 *
 * Java class for DeviceRequestType.
 *
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 *
 * <pre>
 * &lt;simpleType name="DeviceRequestType"&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 * &lt;enumeration value="Input"/&gt;
 * &lt;enumeration value="Output"/&gt;
 * &lt;enumeration value="SecureInput"/&gt;
 * &lt;enumeration value="SecureOutput"/&gt;
 * &lt;enumeration value="AbortInput"/&gt;
 * &lt;enumeration value="AbortOutput"/&gt;
 * &lt;enumeration value="Event"/&gt;
 * &lt;enumeration value="RepeatLastMessage"/&gt;
 * &lt;/restriction&gt;
 * &lt;/simpleType&gt;
</pre> *
 */
enum class DeviceRequestType {

    Input,
    Output,
    SecureInput,
    SecureOutput,
    AbortInput,
    AbortOutput,
    Event,
    RepeatLastMessage

}
