//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 04:13:46 PM CDT 
//


package com.mastercard.gateway.ats.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Specifies the E2EE encryption values
 * 
 * <p>Java class for E2EEValues complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="E2EEValues"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EncryptionIvDt" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="EncryptionKeyData" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/&gt;
 *         &lt;element name="EncryptedTrack2" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/&gt;
 *         &lt;element name="EncryptedCardPAN" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "E2EEValues", propOrder = {
    "encryptionIvDt",
    "encryptionKeyData",
    "encryptedTrack2",
    "encryptedCardPAN"
})
public class E2EEValues {

    @XmlElement(name = "EncryptionIvDt")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar encryptionIvDt;
    @XmlElement(name = "EncryptionKeyData", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] encryptionKeyData;
    @XmlElement(name = "EncryptedTrack2", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] encryptedTrack2;
    @XmlElement(name = "EncryptedCardPAN", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] encryptedCardPAN;

    /**
     * Gets the value of the encryptionIvDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEncryptionIvDt() {
        return encryptionIvDt;
    }

    /**
     * Sets the value of the encryptionIvDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEncryptionIvDt(XMLGregorianCalendar value) {
        this.encryptionIvDt = value;
    }

    /**
     * Gets the value of the encryptionKeyData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getEncryptionKeyData() {
        return encryptionKeyData;
    }

    /**
     * Sets the value of the encryptionKeyData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncryptionKeyData(byte[] value) {
        this.encryptionKeyData = value;
    }

    /**
     * Gets the value of the encryptedTrack2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getEncryptedTrack2() {
        return encryptedTrack2;
    }

    /**
     * Sets the value of the encryptedTrack2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncryptedTrack2(byte[] value) {
        this.encryptedTrack2 = value;
    }

    /**
     * Gets the value of the encryptedCardPAN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getEncryptedCardPAN() {
        return encryptedCardPAN;
    }

    /**
     * Sets the value of the encryptedCardPAN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncryptedCardPAN(byte[] value) {
        this.encryptedCardPAN = value;
    }

}
