//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 04:13:46 PM CDT 
//


package com.mastercard.gateway.ats.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EventTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EventTypes"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CardInserted"/&gt;
 *     &lt;enumeration value="DispenserSelected"/&gt;
 *     &lt;enumeration value="ObtainAuth"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "EventTypes")
@XmlEnum
public enum EventTypes {

    @XmlEnumValue("CardInserted")
    CARD_INSERTED("CardInserted"),
    @XmlEnumValue("DispenserSelected")
    DISPENSER_SELECTED("DispenserSelected"),
    @XmlEnumValue("ObtainAuth")
    OBTAIN_AUTH("ObtainAuth");
    private final String value;

    EventTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EventTypes fromValue(String v) {
        for (EventTypes c: EventTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
