//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 04:13:46 PM CDT 
//


package com.mastercard.gateway.ats.domain

import org.simpleframework.xml.Element
import org.simpleframework.xml.Order
import org.simpleframework.xml.Root


/**
 * Specifies the type of input received from the device (some are card reader specific, other PinPad/Cashier Keyboard specific)
 *
 *
 * Java class for InputValueType complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="InputValueType"&gt;
 * &lt;complexContent&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 * &lt;sequence&gt;
 * &lt;element name="Track1" type="{http://www.nrf-arts.org/IXRetail/namespace}CardTrack" minOccurs="0"/&gt;
 * &lt;element name="Track2" type="{http://www.nrf-arts.org/IXRetail/namespace}CardTrack" minOccurs="0"/&gt;
 * &lt;element name="Track3" type="{http://www.nrf-arts.org/IXRetail/namespace}CardTrack" minOccurs="0"/&gt;
 * &lt;element name="ICC" type="{http://www.nrf-arts.org/IXRetail/namespace}SecureDataFlow" minOccurs="0"/&gt;
 * &lt;element name="Barcode" minOccurs="0"&gt;
 * &lt;simpleType&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 * &lt;minLength value="8"/&gt;
 * &lt;maxLength value="14"/&gt;
 * &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * &lt;/element&gt;
 * &lt;element name="InBoolean" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 * &lt;element name="InNumber" minOccurs="0"&gt;
 * &lt;simpleType&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 * &lt;pattern value="[0-9\.]+"/&gt;
 * &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * &lt;/element&gt;
 * &lt;element name="InString" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 * &lt;element name="CardPAN" type="{http://www.nrf-arts.org/IXRetail/namespace}CardPANType" minOccurs="0"/&gt;
 * &lt;element name="StartDate" type="{http://www.nrf-arts.org/IXRetail/namespace}CardDate" minOccurs="0"/&gt;
 * &lt;element name="ExpiryDate" type="{http://www.nrf-arts.org/IXRetail/namespace}CardDate" minOccurs="0"/&gt;
 * &lt;/sequence&gt;
 * &lt;/restriction&gt;
 * &lt;/complexContent&gt;
 * &lt;/complexType&gt;
</pre> *
 *
 *
 */


@Root(name = "InputValueType")
@Order(elements = ["track1", "track2", "track3", "icc", "barcode", "inBoolean", "inNumber", "inString", "cardPAN", "startDate", "expiryDate"])
data class InputValueType(
        @field:Element(name = "Track1") var track1: CardTrack? = null,
        @field:Element(name = "Track2") var track2: CardTrack? = null,
        @field:Element(name = "Track3") var track3: CardTrack? = null,
        @field:Element(name = "ICC") var icc: SecureDataFlow? = null,
        @field:Element(name = "Barcode") var barcode: String? = null,
        @field:Element(name = "InBoolean") var inBoolean: Boolean? = null,
        @field:Element(name = "InNumber") var inNumber: String? = null,
        @field:Element(name = "InString") var inString: String? = null,
        @field:Element(name = "CardPAN") var cardPAN: String? = null,
        @field:Element(name = "StartDate") var startDate: String? = null,
        @field:Element(name = "ExpiryDate") var expiryDate: String? = null)
