//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 04:13:46 PM CDT 
//


package com.mastercard.gateway.ats.domain

/**
 *
 * Java class for LanguageCodeType.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 *
 * <pre>
 * &lt;simpleType name="LanguageCodeType"&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 * &lt;enumeration value="aa"/&gt;
 * &lt;enumeration value="ab"/&gt;
 * &lt;enumeration value="af"/&gt;
 * &lt;enumeration value="am"/&gt;
 * &lt;enumeration value="ar"/&gt;
 * &lt;enumeration value="as"/&gt;
 * &lt;enumeration value="ay"/&gt;
 * &lt;enumeration value="az"/&gt;
 * &lt;enumeration value="ba"/&gt;
 * &lt;enumeration value="be"/&gt;
 * &lt;enumeration value="bg"/&gt;
 * &lt;enumeration value="bh"/&gt;
 * &lt;enumeration value="bi"/&gt;
 * &lt;enumeration value="bn"/&gt;
 * &lt;enumeration value="bo"/&gt;
 * &lt;enumeration value="br"/&gt;
 * &lt;enumeration value="ca"/&gt;
 * &lt;enumeration value="co"/&gt;
 * &lt;enumeration value="cs"/&gt;
 * &lt;enumeration value="cy"/&gt;
 * &lt;enumeration value="da"/&gt;
 * &lt;enumeration value="de"/&gt;
 * &lt;enumeration value="dz"/&gt;
 * &lt;enumeration value="el"/&gt;
 * &lt;enumeration value="en"/&gt;
 * &lt;enumeration value="eo"/&gt;
 * &lt;enumeration value="es"/&gt;
 * &lt;enumeration value="et"/&gt;
 * &lt;enumeration value="eu"/&gt;
 * &lt;enumeration value="fa"/&gt;
 * &lt;enumeration value="fi"/&gt;
 * &lt;enumeration value="fj"/&gt;
 * &lt;enumeration value="fo"/&gt;
 * &lt;enumeration value="fr"/&gt;
 * &lt;enumeration value="fy"/&gt;
 * &lt;enumeration value="ga"/&gt;
 * &lt;enumeration value="gd"/&gt;
 * &lt;enumeration value="gl"/&gt;
 * &lt;enumeration value="gn"/&gt;
 * &lt;enumeration value="gu"/&gt;
 * &lt;enumeration value="ha"/&gt;
 * &lt;enumeration value="he"/&gt;
 * &lt;enumeration value="hi"/&gt;
 * &lt;enumeration value="hr"/&gt;
 * &lt;enumeration value="hu"/&gt;
 * &lt;enumeration value="hy"/&gt;
 * &lt;enumeration value="ia"/&gt;
 * &lt;enumeration value="id"/&gt;
 * &lt;enumeration value="ie"/&gt;
 * &lt;enumeration value="ik"/&gt;
 * &lt;enumeration value="is"/&gt;
 * &lt;enumeration value="it"/&gt;
 * &lt;enumeration value="iu"/&gt;
 * &lt;enumeration value="ja"/&gt;
 * &lt;enumeration value="jw"/&gt;
 * &lt;enumeration value="ka"/&gt;
 * &lt;enumeration value="kk"/&gt;
 * &lt;enumeration value="kl"/&gt;
 * &lt;enumeration value="km"/&gt;
 * &lt;enumeration value="kn"/&gt;
 * &lt;enumeration value="ko"/&gt;
 * &lt;enumeration value="ks"/&gt;
 * &lt;enumeration value="ku"/&gt;
 * &lt;enumeration value="ky"/&gt;
 * &lt;enumeration value="la"/&gt;
 * &lt;enumeration value="ln"/&gt;
 * &lt;enumeration value="lo"/&gt;
 * &lt;enumeration value="lt"/&gt;
 * &lt;enumeration value="lv"/&gt;
 * &lt;enumeration value="mg"/&gt;
 * &lt;enumeration value="mi"/&gt;
 * &lt;enumeration value="mk"/&gt;
 * &lt;enumeration value="ml"/&gt;
 * &lt;enumeration value="mn"/&gt;
 * &lt;enumeration value="mo"/&gt;
 * &lt;enumeration value="mr"/&gt;
 * &lt;enumeration value="ms"/&gt;
 * &lt;enumeration value="mt"/&gt;
 * &lt;enumeration value="my"/&gt;
 * &lt;enumeration value="na"/&gt;
 * &lt;enumeration value="ne"/&gt;
 * &lt;enumeration value="nl"/&gt;
 * &lt;enumeration value="no"/&gt;
 * &lt;enumeration value="oc"/&gt;
 * &lt;enumeration value="om"/&gt;
 * &lt;enumeration value="or"/&gt;
 * &lt;enumeration value="pa"/&gt;
 * &lt;enumeration value="pl"/&gt;
 * &lt;enumeration value="ps"/&gt;
 * &lt;enumeration value="pt"/&gt;
 * &lt;enumeration value="qu"/&gt;
 * &lt;enumeration value="rm"/&gt;
 * &lt;enumeration value="rn"/&gt;
 * &lt;enumeration value="ro"/&gt;
 * &lt;enumeration value="ru"/&gt;
 * &lt;enumeration value="rw"/&gt;
 * &lt;enumeration value="sa"/&gt;
 * &lt;enumeration value="sd"/&gt;
 * &lt;enumeration value="sg"/&gt;
 * &lt;enumeration value="sh"/&gt;
 * &lt;enumeration value="si"/&gt;
 * &lt;enumeration value="sk"/&gt;
 * &lt;enumeration value="sl"/&gt;
 * &lt;enumeration value="sm"/&gt;
 * &lt;enumeration value="sn"/&gt;
 * &lt;enumeration value="so"/&gt;
 * &lt;enumeration value="sq"/&gt;
 * &lt;enumeration value="sr"/&gt;
 * &lt;enumeration value="ss"/&gt;
 * &lt;enumeration value="st"/&gt;
 * &lt;enumeration value="su"/&gt;
 * &lt;enumeration value="sv"/&gt;
 * &lt;enumeration value="sw"/&gt;
 * &lt;enumeration value="ta"/&gt;
 * &lt;enumeration value="te"/&gt;
 * &lt;enumeration value="tg"/&gt;
 * &lt;enumeration value="th"/&gt;
 * &lt;enumeration value="ti"/&gt;
 * &lt;enumeration value="tk"/&gt;
 * &lt;enumeration value="tl"/&gt;
 * &lt;enumeration value="tn"/&gt;
 * &lt;enumeration value="to"/&gt;
 * &lt;enumeration value="tr"/&gt;
 * &lt;enumeration value="ts"/&gt;
 * &lt;enumeration value="tt"/&gt;
 * &lt;enumeration value="tw"/&gt;
 * &lt;enumeration value="ug"/&gt;
 * &lt;enumeration value="uk"/&gt;
 * &lt;enumeration value="ur"/&gt;
 * &lt;enumeration value="uz"/&gt;
 * &lt;enumeration value="vi"/&gt;
 * &lt;enumeration value="vo"/&gt;
 * &lt;enumeration value="wo"/&gt;
 * &lt;enumeration value="xh"/&gt;
 * &lt;enumeration value="yi"/&gt;
 * &lt;enumeration value="yo"/&gt;
 * &lt;enumeration value="za"/&gt;
 * &lt;enumeration value="zh"/&gt;
 * &lt;enumeration value="zu"/&gt;
 * &lt;/restriction&gt;
 * &lt;/simpleType&gt;
</pre> *
 *
 */


enum class LanguageCodeType {

    /**
     * Afar
     */
    AA,

    /**
     * Abkhazian
     */
    AB,

    /**
     * Afrikaans
     */
    AF,

    /**
     * Amharic
     */
    AM,

    /**
     * Arabic
     */
    AR,

    /**
     * Assamese
     */
    AS,

    /**
     * Aymara
     */
    AY,

    /**
     * Azerbaijani
     */
    AZ,

    /**
     * Bashkir
     */
    BA,

    /**
     * Byelorussian
     */
    BE,

    /**
     * Bulgarian
     */
    BG,

    /**
     * Bihari
     */
    BH,

    /**
     * Bislama
     */
    BI,

    /**
     * Bengali; Bangla
     */
    BN,

    /**
     * Tibetan
     */
    BO,

    /**
     * Breton
     */
    BR,

    /**
     * Catalan
     */
    CA,

    /**
     * Corsican
     */
    CO,

    /**
     * Czech
     */
    CS,

    /**
     * Welsh
     */
    CY,

    /**
     * Danish
     */
    DA,

    /**
     * German
     */
    DE,

    /**
     * Bhutani
     */
    DZ,

    /**
     * Greek
     */
    EL,

    /**
     * English
     */
    EN,

    /**
     * Esperanto
     */
    EO,

    /**
     * Spanish
     */
    ES,

    /**
     * Estonian
     */
    ET,

    /**
     * Basque
     */
    EU,

    /**
     * Persian
     */
    FA,

    /**
     * Finnish
     */
    FI,

    /**
     * Fiji
     */
    FJ,

    /**
     * Faroese
     */
    FO,

    /**
     * French
     */
    FR,

    /**
     * Frisian
     */
    FY,

    /**
     * Irish
     */
    GA,

    /**
     * Scots Gaelic
     */
    GD,

    /**
     * Galician
     */
    GL,

    /**
     * Guarani
     */
    GN,

    /**
     * Gujarati
     */
    GU,

    /**
     * Hausa
     */
    HA,

    /**
     * Hebrew  (formerly iw)
     */
    HE,

    /**
     * Hindi
     */
    HI,

    /**
     * Croatian
     */
    HR,

    /**
     * Hungarian
     */
    HU,

    /**
     * Armenian
     */
    HY,

    /**
     * Interlingua
     */
    IA,

    /**
     * Indonesian (formerly in)
     */
    ID,

    /**
     * Interlingue
     */
    IE,

    /**
     * Inupiak
     */
    IK,

    /**
     * Icelandic
     */
    IS,

    /**
     * Italian
     */
    IT,

    /**
     * Inuktitut
     */
    IU,

    /**
     * Japanese
     */
    JA,

    /**
     * Javanese
     */
    JW,

    /**
     * Georgian
     */
    KA,

    /**
     * Kazakh
     */
    KK,

    /**
     * Greenlandic
     */
    KL,

    /**
     * Cambodian
     */
    KM,

    /**
     * Kannada
     */
    KN,

    /**
     * Korean
     */
    KO,

    /**
     * Kashmiri
     */
    KS,

    /**
     * Kurdish
     */
    KU,

    /**
     * Kirghiz
     */
    KY,

    /**
     * Latin
     */
    LA,

    /**
     * Lingala
     */
    LN,

    /**
     * Laothian
     */
    LO,

    /**
     * Lithuanian
     */
    LT,

    /**
     * Latvian, Lettish
     */
    LV,

    /**
     * Malagasy
     */
    MG,

    /**
     * Maori
     */
    MI,

    /**
     * Macedonian
     */
    MK,

    /**
     * Malayalam
     */
    ML,

    /**
     * Mongolian
     */
    MN,

    /**
     * Moldavian
     */
    MO,

    /**
     * Marathi
     */
    MR,

    /**
     * Malay
     */
    MS,

    /**
     * Maltese
     */
    MT,

    /**
     * Burmese
     */
    MY,

    /**
     * Nauru
     */
    NA,

    /**
     * Nepali
     */
    NE,

    /**
     * Dutch
     */
    NL,

    /**
     * Norwegian
     */
    NO,

    /**
     * Occitan
     */
    OC,

    /**
     * (Afan) Oromo
     */
    OM,

    /**
     * Oriya
     */
    OR,

    /**
     * Punjabi
     */
    PA,

    /**
     * Polish
     */
    PL,

    /**
     * Pashto, Pushto
     */
    PS,

    /**
     * Portuguese
     */
    PT,

    /**
     * Quechua
     */
    QU,

    /**
     * Rhaeto-Romance
     */
    RM,

    /**
     * Kirundi
     */
    RN,

    /**
     * Romanian
     */
    RO,

    /**
     * Russian
     */
    RU,

    /**
     * Kinyarwanda
     */
    RW,

    /**
     * Sanskrit
     */
    SA,

    /**
     * Sindhi
     */
    SD,

    /**
     * Sangho
     */
    SG,

    /**
     * Serbo-Croatian
     */
    SH,

    /**
     * Sinhalese
     */
    SI,

    /**
     * Slovak
     */
    SK,

    /**
     * Slovenian
     */
    SL,

    /**
     * Samoan
     */
    SM,

    /**
     * Shona
     */
    SN,

    /**
     * Somali
     */
    SO,

    /**
     * Albanian
     */
    SQ,

    /**
     * Serbian
     */
    SR,

    /**
     * Siswati
     */
    SS,

    /**
     * Sesotho
     */
    ST,

    /**
     * Sundanese
     */
    SU,

    /**
     * Swedish
     */
    SV,

    /**
     * Swahili
     */
    SW,

    /**
     * Tamil
     */
    TA,

    /**
     * Telugu
     */
    TE,

    /**
     * Tajik
     */
    TG,

    /**
     * Thai
     */
    TH,

    /**
     * Tigrinya
     */
    TI,

    /**
     * Turkmen
     */
    TK,

    /**
     * Tagalog
     */
    TL,

    /**
     * Setswana
     */
    TN,

    /**
     * Tonga
     */
    TO,

    /**
     * Turkish
     */
    TR,

    /**
     * Tsonga
     */
    TS,

    /**
     * Tatar
     */
    TT,

    /**
     * Twi
     */
    TW,

    /**
     * Uighur
     */
    UG,

    /**
     * Ukrainian
     */
    UK,

    /**
     * Urdu
     */
    UR,

    /**
     * Uzbek
     */
    UZ,

    /**
     * Vietnamese
     */
    VI,

    /**
     * Volapuk
     */
    VO,

    /**
     * Wolof
     */
    WO,

    /**
     * Xhosa
     */
    XH,

    /**
     * Yiddish (formerly ji)
     */
    YI,

    /**
     * Yoruba
     */
    YO,

    /**
     * Zhuang
     */
    ZA,

    /**
     * Chinese
     */
    ZH,

    /**
     * Zulu
     */
    ZU

}
