//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 04:13:46 PM CDT 
//


package com.mastercard.gateway.ats.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LanguageCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LanguageCodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="aa"/&gt;
 *     &lt;enumeration value="ab"/&gt;
 *     &lt;enumeration value="af"/&gt;
 *     &lt;enumeration value="am"/&gt;
 *     &lt;enumeration value="ar"/&gt;
 *     &lt;enumeration value="as"/&gt;
 *     &lt;enumeration value="ay"/&gt;
 *     &lt;enumeration value="az"/&gt;
 *     &lt;enumeration value="ba"/&gt;
 *     &lt;enumeration value="be"/&gt;
 *     &lt;enumeration value="bg"/&gt;
 *     &lt;enumeration value="bh"/&gt;
 *     &lt;enumeration value="bi"/&gt;
 *     &lt;enumeration value="bn"/&gt;
 *     &lt;enumeration value="bo"/&gt;
 *     &lt;enumeration value="br"/&gt;
 *     &lt;enumeration value="ca"/&gt;
 *     &lt;enumeration value="co"/&gt;
 *     &lt;enumeration value="cs"/&gt;
 *     &lt;enumeration value="cy"/&gt;
 *     &lt;enumeration value="da"/&gt;
 *     &lt;enumeration value="de"/&gt;
 *     &lt;enumeration value="dz"/&gt;
 *     &lt;enumeration value="el"/&gt;
 *     &lt;enumeration value="en"/&gt;
 *     &lt;enumeration value="eo"/&gt;
 *     &lt;enumeration value="es"/&gt;
 *     &lt;enumeration value="et"/&gt;
 *     &lt;enumeration value="eu"/&gt;
 *     &lt;enumeration value="fa"/&gt;
 *     &lt;enumeration value="fi"/&gt;
 *     &lt;enumeration value="fj"/&gt;
 *     &lt;enumeration value="fo"/&gt;
 *     &lt;enumeration value="fr"/&gt;
 *     &lt;enumeration value="fy"/&gt;
 *     &lt;enumeration value="ga"/&gt;
 *     &lt;enumeration value="gd"/&gt;
 *     &lt;enumeration value="gl"/&gt;
 *     &lt;enumeration value="gn"/&gt;
 *     &lt;enumeration value="gu"/&gt;
 *     &lt;enumeration value="ha"/&gt;
 *     &lt;enumeration value="he"/&gt;
 *     &lt;enumeration value="hi"/&gt;
 *     &lt;enumeration value="hr"/&gt;
 *     &lt;enumeration value="hu"/&gt;
 *     &lt;enumeration value="hy"/&gt;
 *     &lt;enumeration value="ia"/&gt;
 *     &lt;enumeration value="id"/&gt;
 *     &lt;enumeration value="ie"/&gt;
 *     &lt;enumeration value="ik"/&gt;
 *     &lt;enumeration value="is"/&gt;
 *     &lt;enumeration value="it"/&gt;
 *     &lt;enumeration value="iu"/&gt;
 *     &lt;enumeration value="ja"/&gt;
 *     &lt;enumeration value="jw"/&gt;
 *     &lt;enumeration value="ka"/&gt;
 *     &lt;enumeration value="kk"/&gt;
 *     &lt;enumeration value="kl"/&gt;
 *     &lt;enumeration value="km"/&gt;
 *     &lt;enumeration value="kn"/&gt;
 *     &lt;enumeration value="ko"/&gt;
 *     &lt;enumeration value="ks"/&gt;
 *     &lt;enumeration value="ku"/&gt;
 *     &lt;enumeration value="ky"/&gt;
 *     &lt;enumeration value="la"/&gt;
 *     &lt;enumeration value="ln"/&gt;
 *     &lt;enumeration value="lo"/&gt;
 *     &lt;enumeration value="lt"/&gt;
 *     &lt;enumeration value="lv"/&gt;
 *     &lt;enumeration value="mg"/&gt;
 *     &lt;enumeration value="mi"/&gt;
 *     &lt;enumeration value="mk"/&gt;
 *     &lt;enumeration value="ml"/&gt;
 *     &lt;enumeration value="mn"/&gt;
 *     &lt;enumeration value="mo"/&gt;
 *     &lt;enumeration value="mr"/&gt;
 *     &lt;enumeration value="ms"/&gt;
 *     &lt;enumeration value="mt"/&gt;
 *     &lt;enumeration value="my"/&gt;
 *     &lt;enumeration value="na"/&gt;
 *     &lt;enumeration value="ne"/&gt;
 *     &lt;enumeration value="nl"/&gt;
 *     &lt;enumeration value="no"/&gt;
 *     &lt;enumeration value="oc"/&gt;
 *     &lt;enumeration value="om"/&gt;
 *     &lt;enumeration value="or"/&gt;
 *     &lt;enumeration value="pa"/&gt;
 *     &lt;enumeration value="pl"/&gt;
 *     &lt;enumeration value="ps"/&gt;
 *     &lt;enumeration value="pt"/&gt;
 *     &lt;enumeration value="qu"/&gt;
 *     &lt;enumeration value="rm"/&gt;
 *     &lt;enumeration value="rn"/&gt;
 *     &lt;enumeration value="ro"/&gt;
 *     &lt;enumeration value="ru"/&gt;
 *     &lt;enumeration value="rw"/&gt;
 *     &lt;enumeration value="sa"/&gt;
 *     &lt;enumeration value="sd"/&gt;
 *     &lt;enumeration value="sg"/&gt;
 *     &lt;enumeration value="sh"/&gt;
 *     &lt;enumeration value="si"/&gt;
 *     &lt;enumeration value="sk"/&gt;
 *     &lt;enumeration value="sl"/&gt;
 *     &lt;enumeration value="sm"/&gt;
 *     &lt;enumeration value="sn"/&gt;
 *     &lt;enumeration value="so"/&gt;
 *     &lt;enumeration value="sq"/&gt;
 *     &lt;enumeration value="sr"/&gt;
 *     &lt;enumeration value="ss"/&gt;
 *     &lt;enumeration value="st"/&gt;
 *     &lt;enumeration value="su"/&gt;
 *     &lt;enumeration value="sv"/&gt;
 *     &lt;enumeration value="sw"/&gt;
 *     &lt;enumeration value="ta"/&gt;
 *     &lt;enumeration value="te"/&gt;
 *     &lt;enumeration value="tg"/&gt;
 *     &lt;enumeration value="th"/&gt;
 *     &lt;enumeration value="ti"/&gt;
 *     &lt;enumeration value="tk"/&gt;
 *     &lt;enumeration value="tl"/&gt;
 *     &lt;enumeration value="tn"/&gt;
 *     &lt;enumeration value="to"/&gt;
 *     &lt;enumeration value="tr"/&gt;
 *     &lt;enumeration value="ts"/&gt;
 *     &lt;enumeration value="tt"/&gt;
 *     &lt;enumeration value="tw"/&gt;
 *     &lt;enumeration value="ug"/&gt;
 *     &lt;enumeration value="uk"/&gt;
 *     &lt;enumeration value="ur"/&gt;
 *     &lt;enumeration value="uz"/&gt;
 *     &lt;enumeration value="vi"/&gt;
 *     &lt;enumeration value="vo"/&gt;
 *     &lt;enumeration value="wo"/&gt;
 *     &lt;enumeration value="xh"/&gt;
 *     &lt;enumeration value="yi"/&gt;
 *     &lt;enumeration value="yo"/&gt;
 *     &lt;enumeration value="za"/&gt;
 *     &lt;enumeration value="zh"/&gt;
 *     &lt;enumeration value="zu"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "LanguageCodeType")
@XmlEnum
public enum LanguageCodeType {


    /**
     * Afar
     * 
     */
    @XmlEnumValue("aa")
    AA("aa"),

    /**
     * Abkhazian
     * 
     */
    @XmlEnumValue("ab")
    AB("ab"),

    /**
     * Afrikaans
     * 
     */
    @XmlEnumValue("af")
    AF("af"),

    /**
     * Amharic
     * 
     */
    @XmlEnumValue("am")
    AM("am"),

    /**
     * Arabic
     * 
     */
    @XmlEnumValue("ar")
    AR("ar"),

    /**
     * Assamese
     * 
     */
    @XmlEnumValue("as")
    AS("as"),

    /**
     * Aymara
     * 
     */
    @XmlEnumValue("ay")
    AY("ay"),

    /**
     * Azerbaijani
     * 
     */
    @XmlEnumValue("az")
    AZ("az"),

    /**
     * Bashkir
     * 
     */
    @XmlEnumValue("ba")
    BA("ba"),

    /**
     * Byelorussian
     * 
     */
    @XmlEnumValue("be")
    BE("be"),

    /**
     * Bulgarian
     * 
     */
    @XmlEnumValue("bg")
    BG("bg"),

    /**
     * Bihari
     * 
     */
    @XmlEnumValue("bh")
    BH("bh"),

    /**
     * Bislama
     * 
     */
    @XmlEnumValue("bi")
    BI("bi"),

    /**
     * Bengali; Bangla
     * 
     */
    @XmlEnumValue("bn")
    BN("bn"),

    /**
     * Tibetan
     * 
     */
    @XmlEnumValue("bo")
    BO("bo"),

    /**
     * Breton
     * 
     */
    @XmlEnumValue("br")
    BR("br"),

    /**
     * Catalan
     * 
     */
    @XmlEnumValue("ca")
    CA("ca"),

    /**
     * Corsican
     * 
     */
    @XmlEnumValue("co")
    CO("co"),

    /**
     * Czech
     * 
     */
    @XmlEnumValue("cs")
    CS("cs"),

    /**
     * Welsh
     * 
     */
    @XmlEnumValue("cy")
    CY("cy"),

    /**
     * Danish
     * 
     */
    @XmlEnumValue("da")
    DA("da"),

    /**
     * German
     * 
     */
    @XmlEnumValue("de")
    DE("de"),

    /**
     * Bhutani
     * 
     */
    @XmlEnumValue("dz")
    DZ("dz"),

    /**
     * Greek
     * 
     */
    @XmlEnumValue("el")
    EL("el"),

    /**
     * English
     * 
     */
    @XmlEnumValue("en")
    EN("en"),

    /**
     * Esperanto
     * 
     */
    @XmlEnumValue("eo")
    EO("eo"),

    /**
     * Spanish
     * 
     */
    @XmlEnumValue("es")
    ES("es"),

    /**
     * Estonian
     * 
     */
    @XmlEnumValue("et")
    ET("et"),

    /**
     * Basque
     * 
     */
    @XmlEnumValue("eu")
    EU("eu"),

    /**
     * Persian
     * 
     */
    @XmlEnumValue("fa")
    FA("fa"),

    /**
     * Finnish
     * 
     */
    @XmlEnumValue("fi")
    FI("fi"),

    /**
     * Fiji
     * 
     */
    @XmlEnumValue("fj")
    FJ("fj"),

    /**
     * Faroese
     * 
     */
    @XmlEnumValue("fo")
    FO("fo"),

    /**
     * French
     * 
     */
    @XmlEnumValue("fr")
    FR("fr"),

    /**
     * Frisian
     * 
     */
    @XmlEnumValue("fy")
    FY("fy"),

    /**
     * Irish
     * 
     */
    @XmlEnumValue("ga")
    GA("ga"),

    /**
     * Scots Gaelic
     * 
     */
    @XmlEnumValue("gd")
    GD("gd"),

    /**
     * Galician
     * 
     */
    @XmlEnumValue("gl")
    GL("gl"),

    /**
     * Guarani
     * 
     */
    @XmlEnumValue("gn")
    GN("gn"),

    /**
     * Gujarati
     * 
     */
    @XmlEnumValue("gu")
    GU("gu"),

    /**
     * Hausa
     * 
     */
    @XmlEnumValue("ha")
    HA("ha"),

    /**
     * Hebrew  (formerly iw)
     * 
     */
    @XmlEnumValue("he")
    HE("he"),

    /**
     * Hindi
     * 
     */
    @XmlEnumValue("hi")
    HI("hi"),

    /**
     * Croatian
     * 
     */
    @XmlEnumValue("hr")
    HR("hr"),

    /**
     * Hungarian
     * 
     */
    @XmlEnumValue("hu")
    HU("hu"),

    /**
     * Armenian
     * 
     */
    @XmlEnumValue("hy")
    HY("hy"),

    /**
     * Interlingua
     * 
     */
    @XmlEnumValue("ia")
    IA("ia"),

    /**
     * Indonesian (formerly in)
     * 
     */
    @XmlEnumValue("id")
    ID("id"),

    /**
     * Interlingue
     * 
     */
    @XmlEnumValue("ie")
    IE("ie"),

    /**
     * Inupiak
     * 
     */
    @XmlEnumValue("ik")
    IK("ik"),

    /**
     * Icelandic
     * 
     */
    @XmlEnumValue("is")
    IS("is"),

    /**
     * Italian
     * 
     */
    @XmlEnumValue("it")
    IT("it"),

    /**
     * Inuktitut
     * 
     */
    @XmlEnumValue("iu")
    IU("iu"),

    /**
     * Japanese
     * 
     */
    @XmlEnumValue("ja")
    JA("ja"),

    /**
     * Javanese
     * 
     */
    @XmlEnumValue("jw")
    JW("jw"),

    /**
     * Georgian
     * 
     */
    @XmlEnumValue("ka")
    KA("ka"),

    /**
     * Kazakh
     * 
     */
    @XmlEnumValue("kk")
    KK("kk"),

    /**
     * Greenlandic
     * 
     */
    @XmlEnumValue("kl")
    KL("kl"),

    /**
     * Cambodian
     * 
     */
    @XmlEnumValue("km")
    KM("km"),

    /**
     * Kannada
     * 
     */
    @XmlEnumValue("kn")
    KN("kn"),

    /**
     * Korean
     * 
     */
    @XmlEnumValue("ko")
    KO("ko"),

    /**
     * Kashmiri
     * 
     */
    @XmlEnumValue("ks")
    KS("ks"),

    /**
     * Kurdish
     * 
     */
    @XmlEnumValue("ku")
    KU("ku"),

    /**
     * Kirghiz
     * 
     */
    @XmlEnumValue("ky")
    KY("ky"),

    /**
     * Latin
     * 
     */
    @XmlEnumValue("la")
    LA("la"),

    /**
     * Lingala
     * 
     */
    @XmlEnumValue("ln")
    LN("ln"),

    /**
     * Laothian
     * 
     */
    @XmlEnumValue("lo")
    LO("lo"),

    /**
     * Lithuanian
     * 
     */
    @XmlEnumValue("lt")
    LT("lt"),

    /**
     * Latvian, Lettish
     * 
     */
    @XmlEnumValue("lv")
    LV("lv"),

    /**
     * Malagasy
     * 
     */
    @XmlEnumValue("mg")
    MG("mg"),

    /**
     * Maori
     * 
     */
    @XmlEnumValue("mi")
    MI("mi"),

    /**
     * Macedonian
     * 
     */
    @XmlEnumValue("mk")
    MK("mk"),

    /**
     * Malayalam
     * 
     */
    @XmlEnumValue("ml")
    ML("ml"),

    /**
     * Mongolian
     * 
     */
    @XmlEnumValue("mn")
    MN("mn"),

    /**
     * Moldavian
     * 
     */
    @XmlEnumValue("mo")
    MO("mo"),

    /**
     * Marathi
     * 
     */
    @XmlEnumValue("mr")
    MR("mr"),

    /**
     * Malay
     * 
     */
    @XmlEnumValue("ms")
    MS("ms"),

    /**
     * Maltese
     * 
     */
    @XmlEnumValue("mt")
    MT("mt"),

    /**
     * Burmese
     * 
     */
    @XmlEnumValue("my")
    MY("my"),

    /**
     * Nauru
     * 
     */
    @XmlEnumValue("na")
    NA("na"),

    /**
     * Nepali
     * 
     */
    @XmlEnumValue("ne")
    NE("ne"),

    /**
     * Dutch
     * 
     */
    @XmlEnumValue("nl")
    NL("nl"),

    /**
     * Norwegian
     * 
     */
    @XmlEnumValue("no")
    NO("no"),

    /**
     * Occitan
     * 
     */
    @XmlEnumValue("oc")
    OC("oc"),

    /**
     * (Afan) Oromo
     * 
     */
    @XmlEnumValue("om")
    OM("om"),

    /**
     * Oriya
     * 
     */
    @XmlEnumValue("or")
    OR("or"),

    /**
     * Punjabi
     * 
     */
    @XmlEnumValue("pa")
    PA("pa"),

    /**
     * Polish
     * 
     */
    @XmlEnumValue("pl")
    PL("pl"),

    /**
     * Pashto, Pushto
     * 
     */
    @XmlEnumValue("ps")
    PS("ps"),

    /**
     * Portuguese
     * 
     */
    @XmlEnumValue("pt")
    PT("pt"),

    /**
     * Quechua
     * 
     */
    @XmlEnumValue("qu")
    QU("qu"),

    /**
     * Rhaeto-Romance
     * 
     */
    @XmlEnumValue("rm")
    RM("rm"),

    /**
     * Kirundi
     * 
     */
    @XmlEnumValue("rn")
    RN("rn"),

    /**
     * Romanian
     * 
     */
    @XmlEnumValue("ro")
    RO("ro"),

    /**
     * Russian
     * 
     */
    @XmlEnumValue("ru")
    RU("ru"),

    /**
     * Kinyarwanda
     * 
     */
    @XmlEnumValue("rw")
    RW("rw"),

    /**
     * Sanskrit
     * 
     */
    @XmlEnumValue("sa")
    SA("sa"),

    /**
     * Sindhi
     * 
     */
    @XmlEnumValue("sd")
    SD("sd"),

    /**
     * Sangho
     * 
     */
    @XmlEnumValue("sg")
    SG("sg"),

    /**
     * Serbo-Croatian
     * 
     */
    @XmlEnumValue("sh")
    SH("sh"),

    /**
     * Sinhalese
     * 
     */
    @XmlEnumValue("si")
    SI("si"),

    /**
     * Slovak
     * 
     */
    @XmlEnumValue("sk")
    SK("sk"),

    /**
     * Slovenian
     * 
     */
    @XmlEnumValue("sl")
    SL("sl"),

    /**
     * Samoan
     * 
     */
    @XmlEnumValue("sm")
    SM("sm"),

    /**
     * Shona
     * 
     */
    @XmlEnumValue("sn")
    SN("sn"),

    /**
     * Somali
     * 
     */
    @XmlEnumValue("so")
    SO("so"),

    /**
     * Albanian
     * 
     */
    @XmlEnumValue("sq")
    SQ("sq"),

    /**
     * Serbian
     * 
     */
    @XmlEnumValue("sr")
    SR("sr"),

    /**
     * Siswati
     * 
     */
    @XmlEnumValue("ss")
    SS("ss"),

    /**
     * Sesotho
     * 
     */
    @XmlEnumValue("st")
    ST("st"),

    /**
     * Sundanese
     * 
     */
    @XmlEnumValue("su")
    SU("su"),

    /**
     * Swedish
     * 
     */
    @XmlEnumValue("sv")
    SV("sv"),

    /**
     * Swahili
     * 
     */
    @XmlEnumValue("sw")
    SW("sw"),

    /**
     * Tamil
     * 
     */
    @XmlEnumValue("ta")
    TA("ta"),

    /**
     * Telugu
     * 
     */
    @XmlEnumValue("te")
    TE("te"),

    /**
     * Tajik
     * 
     */
    @XmlEnumValue("tg")
    TG("tg"),

    /**
     * Thai
     * 
     */
    @XmlEnumValue("th")
    TH("th"),

    /**
     * Tigrinya
     * 
     */
    @XmlEnumValue("ti")
    TI("ti"),

    /**
     * Turkmen
     * 
     */
    @XmlEnumValue("tk")
    TK("tk"),

    /**
     * Tagalog
     * 
     */
    @XmlEnumValue("tl")
    TL("tl"),

    /**
     * Setswana
     * 
     */
    @XmlEnumValue("tn")
    TN("tn"),

    /**
     * Tonga
     * 
     */
    @XmlEnumValue("to")
    TO("to"),

    /**
     * Turkish
     * 
     */
    @XmlEnumValue("tr")
    TR("tr"),

    /**
     * Tsonga
     * 
     */
    @XmlEnumValue("ts")
    TS("ts"),

    /**
     * Tatar
     * 
     */
    @XmlEnumValue("tt")
    TT("tt"),

    /**
     * Twi
     * 
     */
    @XmlEnumValue("tw")
    TW("tw"),

    /**
     * Uighur
     * 
     */
    @XmlEnumValue("ug")
    UG("ug"),

    /**
     * Ukrainian
     * 
     */
    @XmlEnumValue("uk")
    UK("uk"),

    /**
     * Urdu
     * 
     */
    @XmlEnumValue("ur")
    UR("ur"),

    /**
     * Uzbek
     * 
     */
    @XmlEnumValue("uz")
    UZ("uz"),

    /**
     * Vietnamese
     * 
     */
    @XmlEnumValue("vi")
    VI("vi"),

    /**
     * Volapuk
     * 
     */
    @XmlEnumValue("vo")
    VO("vo"),

    /**
     * Wolof
     * 
     */
    @XmlEnumValue("wo")
    WO("wo"),

    /**
     * Xhosa
     * 
     */
    @XmlEnumValue("xh")
    XH("xh"),

    /**
     * Yiddish (formerly ji)
     * 
     */
    @XmlEnumValue("yi")
    YI("yi"),

    /**
     * Yoruba
     * 
     */
    @XmlEnumValue("yo")
    YO("yo"),

    /**
     * Zhuang
     * 
     */
    @XmlEnumValue("za")
    ZA("za"),

    /**
     * Chinese
     * 
     */
    @XmlEnumValue("zh")
    ZH("zh"),

    /**
     * Zulu
     * 
     */
    @XmlEnumValue("zu")
    ZU("zu");
    private final String value;

    LanguageCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LanguageCodeType fromValue(String v) {
        for (LanguageCodeType c: LanguageCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
