//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 04:13:46 PM CDT 
//


package com.mastercard.gateway.ats.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OAReverseOnline.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OAReverseOnline"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Any"/&gt;
 *     &lt;enumeration value="None"/&gt;
 *     &lt;enumeration value="NotRefunds"/&gt;
 *     &lt;enumeration value="DPG"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "OAReverseOnline")
@XmlEnum
public enum OAReverseOnline {

    @XmlEnumValue("Any")
    ANY("Any"),
    @XmlEnumValue("None")
    NONE("None"),
    @XmlEnumValue("NotRefunds")
    NOT_REFUNDS("NotRefunds"),
    DPG("DPG");
    private final String value;

    OAReverseOnline(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OAReverseOnline fromValue(String v) {
        for (OAReverseOnline c: OAReverseOnline.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
