//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 04:13:46 PM CDT 
//


package com.mastercard.gateway.ats.domain;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.nrf_arts.ixretail.namespace package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.nrf_arts.ixretail.namespace
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CardServiceRequest }
     * 
     */
    public CardServiceRequest createCardServiceRequest() {
        return new CardServiceRequest();
    }

    /**
     * Create an instance of {@link CardServiceResponse }
     * 
     */
    public CardServiceResponse createCardServiceResponse() {
        return new CardServiceResponse();
    }

    /**
     * Create an instance of {@link DeviceRequest }
     * 
     */
    public DeviceRequest createDeviceRequest() {
        return new DeviceRequest();
    }

    /**
     * Create an instance of {@link DeviceResponse }
     * 
     */
    public DeviceResponse createDeviceResponse() {
        return new DeviceResponse();
    }

    /**
     * Create an instance of {@link ServiceRequest }
     * 
     */
    public ServiceRequest createServiceRequest() {
        return new ServiceRequest();
    }

    /**
     * Create an instance of {@link ServiceResponse }
     * 
     */
    public ServiceResponse createServiceResponse() {
        return new ServiceResponse();
    }

    /**
     * Create an instance of {@link CardValueDRType }
     * 
     */
    public CardValueDRType createCardValueDRType() {
        return new CardValueDRType();
    }

    /**
     * Create an instance of {@link ServiceResponse.Versions }
     * 
     */
    public ServiceResponse.Versions createServiceResponseVersions() {
        return new ServiceResponse.Versions();
    }

    /**
     * Create an instance of {@link ServiceResponse.Versions.Devices }
     * 
     */
    public ServiceResponse.Versions.Devices createServiceResponseVersionsDevices() {
        return new ServiceResponse.Versions.Devices();
    }

    /**
     * Create an instance of {@link ServiceResponse.Submission }
     * 
     */
    public ServiceResponse.Submission createServiceResponseSubmission() {
        return new ServiceResponse.Submission();
    }

    /**
     * Create an instance of {@link ServiceResponse.Reconciliation }
     * 
     */
    public ServiceResponse.Reconciliation createServiceResponseReconciliation() {
        return new ServiceResponse.Reconciliation();
    }

    /**
     * Create an instance of {@link DeviceResponse.EventResult }
     * 
     */
    public DeviceResponse.EventResult createDeviceResponseEventResult() {
        return new DeviceResponse.EventResult();
    }

    /**
     * Create an instance of {@link DeviceRequest.Event }
     * 
     */
    public DeviceRequest.Event createDeviceRequestEvent() {
        return new DeviceRequest.Event();
    }

    /**
     * Create an instance of {@link DeviceRequest.Event.EventData }
     * 
     */
    public DeviceRequest.Event.EventData createDeviceRequestEventEventData() {
        return new DeviceRequest.Event.EventData();
    }

    /**
     * Create an instance of {@link DeviceRequest.Event.EventData.ProductsAllowed }
     * 
     */
    public DeviceRequest.Event.EventData.ProductsAllowed createDeviceRequestEventEventDataProductsAllowed() {
        return new DeviceRequest.Event.EventData.ProductsAllowed();
    }

    /**
     * Create an instance of {@link DeviceRequest.Input }
     * 
     */
    public DeviceRequest.Input createDeviceRequestInput() {
        return new DeviceRequest.Input();
    }

    /**
     * Create an instance of {@link DeviceRequest.Output }
     * 
     */
    public DeviceRequest.Output createDeviceRequestOutput() {
        return new DeviceRequest.Output();
    }

    /**
     * Create an instance of {@link CardServiceResponse.Loyalty }
     * 
     */
    public CardServiceResponse.Loyalty createCardServiceResponseLoyalty() {
        return new CardServiceResponse.Loyalty();
    }

    /**
     * Create an instance of {@link CardServiceResponse.Tender }
     * 
     */
    public CardServiceResponse.Tender createCardServiceResponseTender() {
        return new CardServiceResponse.Tender();
    }

    /**
     * Create an instance of {@link CardServiceRequest.CardCircuitCollection }
     * 
     */
    public CardServiceRequest.CardCircuitCollection createCardServiceRequestCardCircuitCollection() {
        return new CardServiceRequest.CardCircuitCollection();
    }

    /**
     * Create an instance of {@link CardServiceRequest.Loyalty }
     * 
     */
    public CardServiceRequest.Loyalty createCardServiceRequestLoyalty() {
        return new CardServiceRequest.Loyalty();
    }

    /**
     * Create an instance of {@link CardServiceRequest.POSdata }
     * 
     */
    public CardServiceRequest.POSdata createCardServiceRequestPOSdata() {
        return new CardServiceRequest.POSdata();
    }

    /**
     * Create an instance of {@link CardServiceRequest.OriginalTransaction }
     * 
     */
    public CardServiceRequest.OriginalTransaction createCardServiceRequestOriginalTransaction() {
        return new CardServiceRequest.OriginalTransaction();
    }

    /**
     * Create an instance of {@link TotalAmountType }
     * 
     */
    public TotalAmountType createTotalAmountType() {
        return new TotalAmountType();
    }

    /**
     * Create an instance of {@link SaleItemType }
     * 
     */
    public SaleItemType createSaleItemType() {
        return new SaleItemType();
    }

    /**
     * Create an instance of {@link CardValueType }
     * 
     */
    public CardValueType createCardValueType() {
        return new CardValueType();
    }

    /**
     * Create an instance of {@link EncryptedCardValueType }
     * 
     */
    public EncryptedCardValueType createEncryptedCardValueType() {
        return new EncryptedCardValueType();
    }

    /**
     * Create an instance of {@link CardServiceRequest.Acquirer }
     * 
     */
    public CardServiceRequest.Acquirer createCardServiceRequestAcquirer() {
        return new CardServiceRequest.Acquirer();
    }

    /**
     * Create an instance of {@link CardServiceResponse.Terminal }
     * 
     */
    public CardServiceResponse.Terminal createCardServiceResponseTerminal() {
        return new CardServiceResponse.Terminal();
    }

    /**
     * Create an instance of {@link ATSErrorDetailType }
     * 
     */
    public ATSErrorDetailType createATSErrorDetailType() {
        return new ATSErrorDetailType();
    }

    /**
     * Create an instance of {@link CardServiceResponse.OriginalHeader }
     * 
     */
    public CardServiceResponse.OriginalHeader createCardServiceResponseOriginalHeader() {
        return new CardServiceResponse.OriginalHeader();
    }

    /**
     * Create an instance of {@link CardValueICCType }
     * 
     */
    public CardValueICCType createCardValueICCType() {
        return new CardValueICCType();
    }

    /**
     * Create an instance of {@link DeviceResponse.Output }
     * 
     */
    public DeviceResponse.Output createDeviceResponseOutput() {
        return new DeviceResponse.Output();
    }

    /**
     * Create an instance of {@link DeviceResponse.Input }
     * 
     */
    public DeviceResponse.Input createDeviceResponseInput() {
        return new DeviceResponse.Input();
    }

    /**
     * Create an instance of {@link ServiceRequest.POSdata }
     * 
     */
    public ServiceRequest.POSdata createServiceRequestPOSdata() {
        return new ServiceRequest.POSdata();
    }

    /**
     * Create an instance of {@link ServiceRequest.TotalAmount }
     * 
     */
    public ServiceRequest.TotalAmount createServiceRequestTotalAmount() {
        return new ServiceRequest.TotalAmount();
    }

    /**
     * Create an instance of {@link ServiceRequest.PINPadProgramLoad }
     * 
     */
    public ServiceRequest.PINPadProgramLoad createServiceRequestPINPadProgramLoad() {
        return new ServiceRequest.PINPadProgramLoad();
    }

    /**
     * Create an instance of {@link ServiceResponse.Terminal }
     * 
     */
    public ServiceResponse.Terminal createServiceResponseTerminal() {
        return new ServiceResponse.Terminal();
    }

    /**
     * Create an instance of {@link ServiceResponse.Authorisation }
     * 
     */
    public ServiceResponse.Authorisation createServiceResponseAuthorisation() {
        return new ServiceResponse.Authorisation();
    }

    /**
     * Create an instance of {@link ServiceResponse.OriginalHeader }
     * 
     */
    public ServiceResponse.OriginalHeader createServiceResponseOriginalHeader() {
        return new ServiceResponse.OriginalHeader();
    }

    /**
     * Create an instance of {@link Text }
     * 
     */
    public Text createText() {
        return new Text();
    }

    /**
     * Create an instance of {@link Amount }
     * 
     */
    public Amount createAmount() {
        return new Amount();
    }

    /**
     * Create an instance of {@link CardTrack }
     * 
     */
    public CardTrack createCardTrack() {
        return new CardTrack();
    }

    /**
     * Create an instance of {@link SecureDataFlow }
     * 
     */
    public SecureDataFlow createSecureDataFlow() {
        return new SecureDataFlow();
    }

    /**
     * Create an instance of {@link MACType }
     * 
     */
    public MACType createMACType() {
        return new MACType();
    }

    /**
     * Create an instance of {@link InputValueType }
     * 
     */
    public InputValueType createInputValueType() {
        return new InputValueType();
    }

    /**
     * Create an instance of {@link ICCType }
     * 
     */
    public ICCType createICCType() {
        return new ICCType();
    }

    /**
     * Create an instance of {@link E2EEValues }
     * 
     */
    public E2EEValues createE2EEValues() {
        return new E2EEValues();
    }

    /**
     * Create an instance of {@link P2PEValues }
     * 
     */
    public P2PEValues createP2PEValues() {
        return new P2PEValues();
    }

    /**
     * Create an instance of {@link ATSErrorType }
     * 
     */
    public ATSErrorType createATSErrorType() {
        return new ATSErrorType();
    }

    /**
     * Create an instance of {@link ATSResponseType }
     * 
     */
    public ATSResponseType createATSResponseType() {
        return new ATSResponseType();
    }

    /**
     * Create an instance of {@link CardValueDRType.CADLuhn }
     * 
     */
    public CardValueDRType.CADLuhn createCardValueDRTypeCADLuhn() {
        return new CardValueDRType.CADLuhn();
    }

    /**
     * Create an instance of {@link CardValueDRType.Features }
     * 
     */
    public CardValueDRType.Features createCardValueDRTypeFeatures() {
        return new CardValueDRType.Features();
    }

    /**
     * Create an instance of {@link ServiceResponse.Versions.Devices.Device }
     * 
     */
    public ServiceResponse.Versions.Devices.Device createServiceResponseVersionsDevicesDevice() {
        return new ServiceResponse.Versions.Devices.Device();
    }

    /**
     * Create an instance of {@link ServiceResponse.Submission.Successful }
     * 
     */
    public ServiceResponse.Submission.Successful createServiceResponseSubmissionSuccessful() {
        return new ServiceResponse.Submission.Successful();
    }

    /**
     * Create an instance of {@link ServiceResponse.Submission.Failed }
     * 
     */
    public ServiceResponse.Submission.Failed createServiceResponseSubmissionFailed() {
        return new ServiceResponse.Submission.Failed();
    }

    /**
     * Create an instance of {@link ServiceResponse.Reconciliation.TotalAmount }
     * 
     */
    public ServiceResponse.Reconciliation.TotalAmount createServiceResponseReconciliationTotalAmount() {
        return new ServiceResponse.Reconciliation.TotalAmount();
    }

    /**
     * Create an instance of {@link DeviceResponse.EventResult.Acquirer }
     * 
     */
    public DeviceResponse.EventResult.Acquirer createDeviceResponseEventResultAcquirer() {
        return new DeviceResponse.EventResult.Acquirer();
    }

    /**
     * Create an instance of {@link DeviceResponse.EventResult.AuthResponse }
     * 
     */
    public DeviceResponse.EventResult.AuthResponse createDeviceResponseEventResultAuthResponse() {
        return new DeviceResponse.EventResult.AuthResponse();
    }

    /**
     * Create an instance of {@link DeviceResponse.EventResult.TransactionLimits }
     * 
     */
    public DeviceResponse.EventResult.TransactionLimits createDeviceResponseEventResultTransactionLimits() {
        return new DeviceResponse.EventResult.TransactionLimits();
    }

    /**
     * Create an instance of {@link DeviceResponse.EventResult.OACentreDetails }
     * 
     */
    public DeviceResponse.EventResult.OACentreDetails createDeviceResponseEventResultOACentreDetails() {
        return new DeviceResponse.EventResult.OACentreDetails();
    }

    /**
     * Create an instance of {@link DeviceRequest.Event.EventData.ProductsAllowed.ProductCode }
     * 
     */
    public DeviceRequest.Event.EventData.ProductsAllowed.ProductCode createDeviceRequestEventEventDataProductsAllowedProductCode() {
        return new DeviceRequest.Event.EventData.ProductsAllowed.ProductCode();
    }

    /**
     * Create an instance of {@link DeviceRequest.Input.Command }
     * 
     */
    public DeviceRequest.Input.Command createDeviceRequestInputCommand() {
        return new DeviceRequest.Input.Command();
    }

    /**
     * Create an instance of {@link DeviceRequest.Output.TextLine }
     * 
     */
    public DeviceRequest.Output.TextLine createDeviceRequestOutputTextLine() {
        return new DeviceRequest.Output.TextLine();
    }

    /**
     * Create an instance of {@link DeviceRequest.Output.Buzzer }
     * 
     */
    public DeviceRequest.Output.Buzzer createDeviceRequestOutputBuzzer() {
        return new DeviceRequest.Output.Buzzer();
    }

    /**
     * Create an instance of {@link CardServiceResponse.Loyalty.LoyaltyCard }
     * 
     */
    public CardServiceResponse.Loyalty.LoyaltyCard createCardServiceResponseLoyaltyLoyaltyCard() {
        return new CardServiceResponse.Loyalty.LoyaltyCard();
    }

    /**
     * Create an instance of {@link CardServiceResponse.Loyalty.LoyaltyAmount }
     * 
     */
    public CardServiceResponse.Loyalty.LoyaltyAmount createCardServiceResponseLoyaltyLoyaltyAmount() {
        return new CardServiceResponse.Loyalty.LoyaltyAmount();
    }

    /**
     * Create an instance of {@link CardServiceResponse.Loyalty.LoyaltyApprovalCode }
     * 
     */
    public CardServiceResponse.Loyalty.LoyaltyApprovalCode createCardServiceResponseLoyaltyLoyaltyApprovalCode() {
        return new CardServiceResponse.Loyalty.LoyaltyApprovalCode();
    }

    /**
     * Create an instance of {@link CardServiceResponse.Tender.Authorisation }
     * 
     */
    public CardServiceResponse.Tender.Authorisation createCardServiceResponseTenderAuthorisation() {
        return new CardServiceResponse.Tender.Authorisation();
    }

    /**
     * Create an instance of {@link CardServiceRequest.CardCircuitCollection.CardCircuit }
     * 
     */
    public CardServiceRequest.CardCircuitCollection.CardCircuit createCardServiceRequestCardCircuitCollectionCardCircuit() {
        return new CardServiceRequest.CardCircuitCollection.CardCircuit();
    }

    /**
     * Create an instance of {@link CardServiceRequest.Loyalty.LoyaltyCard }
     * 
     */
    public CardServiceRequest.Loyalty.LoyaltyCard createCardServiceRequestLoyaltyLoyaltyCard() {
        return new CardServiceRequest.Loyalty.LoyaltyCard();
    }

    /**
     * Create an instance of {@link CardServiceRequest.Loyalty.MOPrule }
     * 
     */
    public CardServiceRequest.Loyalty.MOPrule createCardServiceRequestLoyaltyMOPrule() {
        return new CardServiceRequest.Loyalty.MOPrule();
    }

}
