//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 04:13:46 PM CDT 
//


package com.mastercard.gateway.ats.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Specifies the P2PE encryption values
 * 
 * <p>Java class for P2PEValues complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="P2PEValues"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DataIV" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/&gt;
 *         &lt;element name="DataKSN" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/&gt;
 *         &lt;element name="EncryptedData" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/&gt;
 *         &lt;element name="PANIV" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/&gt;
 *         &lt;element name="PANKSN" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/&gt;
 *         &lt;element name="EncryptedPAN" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "P2PEValues", propOrder = {
    "dataIV",
    "dataKSN",
    "encryptedData",
    "paniv",
    "panksn",
    "encryptedPAN"
})
public class P2PEValues {

    @XmlElement(name = "DataIV", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] dataIV;
    @XmlElement(name = "DataKSN", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] dataKSN;
    @XmlElement(name = "EncryptedData", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] encryptedData;
    @XmlElement(name = "PANIV", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] paniv;
    @XmlElement(name = "PANKSN", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] panksn;
    @XmlElement(name = "EncryptedPAN", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] encryptedPAN;

    /**
     * Gets the value of the dataIV property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getDataIV() {
        return dataIV;
    }

    /**
     * Sets the value of the dataIV property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataIV(byte[] value) {
        this.dataIV = value;
    }

    /**
     * Gets the value of the dataKSN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getDataKSN() {
        return dataKSN;
    }

    /**
     * Sets the value of the dataKSN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataKSN(byte[] value) {
        this.dataKSN = value;
    }

    /**
     * Gets the value of the encryptedData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getEncryptedData() {
        return encryptedData;
    }

    /**
     * Sets the value of the encryptedData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncryptedData(byte[] value) {
        this.encryptedData = value;
    }

    /**
     * Gets the value of the paniv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getPANIV() {
        return paniv;
    }

    /**
     * Sets the value of the paniv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPANIV(byte[] value) {
        this.paniv = value;
    }

    /**
     * Gets the value of the panksn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getPANKSN() {
        return panksn;
    }

    /**
     * Sets the value of the panksn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPANKSN(byte[] value) {
        this.panksn = value;
    }

    /**
     * Gets the value of the encryptedPAN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getEncryptedPAN() {
        return encryptedPAN;
    }

    /**
     * Sets the value of the encryptedPAN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncryptedPAN(byte[] value) {
        this.encryptedPAN = value;
    }

}
