//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 04:13:46 PM CDT 
//


package com.mastercard.gateway.ats.domain

import org.simpleframework.xml.Element
import org.simpleframework.xml.Order
import org.simpleframework.xml.Root

/**
 * Specifies the P2PE encryption values
 *
 *
 *
 * Java class for P2PEValues complex type.
 *
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 *
 * <pre>
 * &lt;complexType name="P2PEValues"&gt;
 * &lt;complexContent&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 * &lt;sequence&gt;
 * &lt;element name="DataIV" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/&gt;
 * &lt;element name="DataKSN" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/&gt;
 * &lt;element name="EncryptedData" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/&gt;
 * &lt;element name="PANIV" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/&gt;
 * &lt;element name="PANKSN" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/&gt;
 * &lt;element name="EncryptedPAN" type="{http://www.w3.org/2001/XMLSchema}hexBinary" minOccurs="0"/&gt;
 * &lt;/sequence&gt;
 * &lt;/restriction&gt;
 * &lt;/complexContent&gt;
 * &lt;/complexType&gt;
</pre> *
 */
@Root(name = "P2PEValues")
@Order(elements = arrayOf("dataIV", "dataKSN", "encryptedData", "paniv", "panksn", "encryptedPAN"))
data class P2PEValues(

        @Element(name = "DataIV")
        /*@XmlJavaTypeAdapter(HexBinaryAdapter.class)
        @XmlSchemaType(name = "hexBinary")*/
        protected var dataIV: ByteArray? = null,

        @Element(name = "DataKSN")
        protected var dataKSN: ByteArray? = null,

        @Element(name = "EncryptedData")
        protected var encryptedData: ByteArray? = null,

        @Element(name = "PANIV")
        protected var paniv: ByteArray? = null,

        @Element(name = "PANKSN")
        protected var panksn: ByteArray? = null,

        @Element(name = "EncryptedPAN")
        protected var encryptedPAN: ByteArray? = null

)
