//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 04:13:46 PM CDT 
//


package com.mastercard.gateway.ats.domain

import org.simpleframework.xml.Root

/**
 *
 * Java class for RequestResultType.
 *
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 *
 * <pre>
 * &lt;simpleType name="RequestResultType"&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 * &lt;enumeration value="Success"/&gt;
 * &lt;enumeration value="PartialFailure"/&gt;
 * &lt;enumeration value="Failure"/&gt;
 * &lt;enumeration value="DeviceUnavailable"/&gt;
 * &lt;enumeration value="Busy"/&gt;
 * &lt;enumeration value="LoggedOut"/&gt;
 * &lt;enumeration value="Aborted"/&gt;
 * &lt;enumeration value="TimedOut"/&gt;
 * &lt;enumeration value="CommunicationError"/&gt;
 * &lt;enumeration value="FormatError"/&gt;
 * &lt;enumeration value="ParsingError"/&gt;
 * &lt;enumeration value="ValidationError"/&gt;
 * &lt;enumeration value="MissingMandatoryData"/&gt;
 * &lt;enumeration value="UnknownCard"/&gt;
 * &lt;enumeration value="NotSupported"/&gt;
 * &lt;/restriction&gt;
 * &lt;/simpleType&gt;
</pre> *
 */
@Root(name = "RequestResultType")
enum class RequestResultType {
    Success,
    PartialFailure,
    Failure,
    DeviceUnavailable,
    Busy,
    LoggedOut,
    Aborted,
    TimedOut,
    CommunicationError,
    FormatError,
    ParsingError,
    ValidationError,
    MissingMandatoryData,
    UnknownCard,
    NotSupported
}
