//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 04:13:46 PM CDT 
//


package com.mastercard.gateway.ats.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RequestResultType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RequestResultType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Success"/&gt;
 *     &lt;enumeration value="PartialFailure"/&gt;
 *     &lt;enumeration value="Failure"/&gt;
 *     &lt;enumeration value="DeviceUnavailable"/&gt;
 *     &lt;enumeration value="Busy"/&gt;
 *     &lt;enumeration value="LoggedOut"/&gt;
 *     &lt;enumeration value="Aborted"/&gt;
 *     &lt;enumeration value="TimedOut"/&gt;
 *     &lt;enumeration value="CommunicationError"/&gt;
 *     &lt;enumeration value="FormatError"/&gt;
 *     &lt;enumeration value="ParsingError"/&gt;
 *     &lt;enumeration value="ValidationError"/&gt;
 *     &lt;enumeration value="MissingMandatoryData"/&gt;
 *     &lt;enumeration value="UnknownCard"/&gt;
 *     &lt;enumeration value="NotSupported"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "RequestResultType")
@XmlEnum
public enum RequestResultType {

    @XmlEnumValue("Success")
    SUCCESS("Success"),
    @XmlEnumValue("PartialFailure")
    PARTIAL_FAILURE("PartialFailure"),
    @XmlEnumValue("Failure")
    FAILURE("Failure"),
    @XmlEnumValue("DeviceUnavailable")
    DEVICE_UNAVAILABLE("DeviceUnavailable"),
    @XmlEnumValue("Busy")
    BUSY("Busy"),
    @XmlEnumValue("LoggedOut")
    LOGGED_OUT("LoggedOut"),
    @XmlEnumValue("Aborted")
    ABORTED("Aborted"),
    @XmlEnumValue("TimedOut")
    TIMED_OUT("TimedOut"),
    @XmlEnumValue("CommunicationError")
    COMMUNICATION_ERROR("CommunicationError"),
    @XmlEnumValue("FormatError")
    FORMAT_ERROR("FormatError"),
    @XmlEnumValue("ParsingError")
    PARSING_ERROR("ParsingError"),
    @XmlEnumValue("ValidationError")
    VALIDATION_ERROR("ValidationError"),
    @XmlEnumValue("MissingMandatoryData")
    MISSING_MANDATORY_DATA("MissingMandatoryData"),
    @XmlEnumValue("UnknownCard")
    UNKNOWN_CARD("UnknownCard"),
    @XmlEnumValue("NotSupported")
    NOT_SUPPORTED("NotSupported");
    private final String value;

    RequestResultType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RequestResultType fromValue(String v) {
        for (RequestResultType c: RequestResultType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
