//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 04:13:46 PM CDT 
//


package com.mastercard.gateway.ats.domain

import org.simpleframework.xml.Attribute
import org.simpleframework.xml.Element
import org.simpleframework.xml.Order
import org.simpleframework.xml.Root

import java.math.BigDecimal
import java.math.BigInteger

/**
 * SaleItem
 *
 *
 *
 * Java class for SaleItemType complex type.
 *
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 *
 * <pre>
 * &lt;complexType name="SaleItemType"&gt;
 * &lt;complexContent&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 * &lt;sequence&gt;
 * &lt;element name="ProductCode" type="{http://www.nrf-arts.org/IXRetail/namespace}ProductGroupType"/&gt;
 * &lt;element name="Amount"&gt;
 * &lt;simpleType&gt;
 * &lt;restriction base="{http://www.nrf-arts.org/IXRetail/namespace}MonetaryAmount"&gt;
 * &lt;minInclusive value="0"/&gt;
 * &lt;maxInclusive value="9999.99"/&gt;
 * &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * &lt;/element&gt;
 * &lt;element name="UnitMeasure" type="{http://www.nrf-arts.org/IXRetail/namespace}UnitOfMeasureCode" minOccurs="0"/&gt;
 * &lt;element name="UnitPrice" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 * &lt;element name="Quantity" minOccurs="0"&gt;
 * &lt;simpleType&gt;
 * &lt;restriction base="{http://www.nrf-arts.org/IXRetail/namespace}Quantity"&gt;
 * &lt;minInclusive value="0"/&gt;
 * &lt;maxInclusive value="9999.999"/&gt;
 * &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * &lt;/element&gt;
 * &lt;element name="TaxCode" minOccurs="0"&gt;
 * &lt;simpleType&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 * &lt;length value="1"/&gt;
 * &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * &lt;/element&gt;
 * &lt;element name="AdditionalProductCode" type="{http://www.nrf-arts.org/IXRetail/namespace}GTIN" minOccurs="0"/&gt;
 * &lt;element name="AdditionalProductInfo" minOccurs="0"&gt;
 * &lt;simpleType&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 * &lt;maxLength value="40"/&gt;
 * &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * &lt;/element&gt;
 * &lt;element name="TypeMovement" minOccurs="0"&gt;
 * &lt;simpleType&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 * &lt;length value="1"/&gt;
 * &lt;enumeration value="0"/&gt;
 * &lt;enumeration value="1"/&gt;
 * &lt;enumeration value="2"/&gt;
 * &lt;enumeration value="3"/&gt;
 * &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * &lt;/element&gt;
 * &lt;element name="SaleChannel" minOccurs="0"&gt;
 * &lt;simpleType&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 * &lt;enumeration value="CompanyOwned"/&gt;
 * &lt;enumeration value="DealerOwned"/&gt;
 * &lt;enumeration value="ThirdPartyOwned"/&gt;
 * &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * &lt;/element&gt;
 * &lt;element name="VATRate" minOccurs="0"&gt;
 * &lt;simpleType&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 * &lt;fractionDigits value="2"/&gt;
 * &lt;minInclusive value="0"/&gt;
 * &lt;maxInclusive value="99.99"/&gt;
 * &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * &lt;/element&gt;
 * &lt;/sequence&gt;
 * &lt;attribute name="ItemID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 * &lt;/restriction&gt;
 * &lt;/complexContent&gt;
 * &lt;/complexType&gt;
</pre> *
 */
@Root(name = "SaleItemType")
@Order(elements = ["productCode", "amount", "unitMeasure", "unitPrice", "quantity", "taxCode", "additionalProductCode", "additionalProductInfo", "typeMovement", "saleChannel", "vatRate"])
data class SaleItemType(
        @field:Element(name = "ProductCode", required = true) protected var productCode: BigInteger,
        @field:Element(name = "Amount", required = true) protected var amount: BigDecimal,
        @field:Element(name = "UnitMeasure") protected var unitMeasure: UnitOfMeasureCode? = null,
        @field:Element(name = "UnitPrice") protected var unitPrice: BigDecimal? = null,
        @field:Element(name = "Quantity") protected var quantity: BigDecimal? = null,
        @field:Element(name = "TaxCode") protected var taxCode: String? = null,
        @field:Element(name = "AdditionalProductCode") protected var additionalProductCode: Long? = null,
        @field:Element(name = "AdditionalProductInfo") protected var additionalProductInfo: String? = null,
        @field:Element(name = "TypeMovement") protected var typeMovement: String? = null,
        @field:Element(name = "SaleChannel") protected var saleChannel: String? = null,
        @field:Element(name = "VATRate") protected var vatRate: BigDecimal? = null,
        @field:Attribute(name = "ItemID", required = true) protected var itemID: String
)


