//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 04:13:46 PM CDT 
//


package com.mastercard.gateway.ats.domain


/**
 *
 * Java class for ServiceRequestType.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 *
 * <pre>
 * &lt;simpleType name="ServiceRequestType"&gt;
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 * &lt;enumeration value="Diagnosis"/&gt;
 * &lt;enumeration value="SendOfflineTransactions"/&gt;
 * &lt;enumeration value="Reconciliation"/&gt;
 * &lt;enumeration value="ReconciliationWithClosure"/&gt;
 * &lt;enumeration value="GlobalReconciliation"/&gt;
 * &lt;enumeration value="GlobalReconciliationWithClosure"/&gt;
 * &lt;enumeration value="Administration"/&gt;
 * &lt;enumeration value="Login"/&gt;
 * &lt;enumeration value="Logoff"/&gt;
 * &lt;enumeration value="OnlineAgent"/&gt;
 * &lt;enumeration value="RepeatLastMessage"/&gt;
 * &lt;enumeration value="GetReference"/&gt;
 * &lt;enumeration value="EncryptionRSAPublicKey"/&gt;
 * &lt;enumeration value="AcquireDevice"/&gt;
 * &lt;enumeration value="ReleaseDevice"/&gt;
 * &lt;enumeration value="RuleLookup"/&gt;
 * &lt;enumeration value="PINPadProgramLoad"/&gt;
 * &lt;enumeration value="QuerySoftwareVersions"/&gt;
 * &lt;enumeration value="MemoryReport"/&gt;
 * &lt;/restriction&gt;
 * &lt;/simpleType&gt;
</pre> *
 *
 */
enum class ServiceRequestType {
    Diagnosis,
    SendOfflineTransactions,
    Reconciliation,
    ReconciliationWithClosure,
    GlobalReconciliation,
    GlobalReconciliationWithClosure,
    Administration,
    Login,
    Logoff,
    OnlineAgent,
    RepeatLastMessage,
    GetReference,
    EncryptionRSAPublicKey,
    AcquireDevice,
    ReleaseDevice,
    RuleLookup,
    PINPadProgramLoad,
    QuerySoftwareVersions,
    MemoryReport
}
