//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 04:13:46 PM CDT 
//


package com.mastercard.gateway.ats.domain;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice minOccurs="0"&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="POSdata"&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name="POSTimeStamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *                     &lt;element name="ShiftNumber" minOccurs="0"&gt;
 *                       &lt;simpleType&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer"&gt;
 *                           &lt;totalDigits value="3"/&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/simpleType&gt;
 *                     &lt;/element&gt;
 *                     &lt;element name="ClerkID" minOccurs="0"&gt;
 *                       &lt;simpleType&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer"&gt;
 *                           &lt;totalDigits value="9"/&gt;
 *                           &lt;minInclusive value="0"/&gt;
 *                           &lt;maxInclusive value="999999999"/&gt;
 *                           &lt;fractionDigits value="0"/&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/simpleType&gt;
 *                     &lt;/element&gt;
 *                     &lt;element name="ClerkPermission" minOccurs="0"&gt;
 *                       &lt;simpleType&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                           &lt;enumeration value="Low"/&gt;
 *                           &lt;enumeration value="Medium"/&gt;
 *                           &lt;enumeration value="High"/&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/simpleType&gt;
 *                     &lt;/element&gt;
 *                     &lt;element name="Reference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                     &lt;element name="DiagnosisMethod" minOccurs="0"&gt;
 *                       &lt;simpleType&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                           &lt;enumeration value="OnLine"/&gt;
 *                           &lt;enumeration value="Local"/&gt;
 *                           &lt;enumeration value="POPInit"/&gt;
 *                           &lt;enumeration value="POPInitAll"/&gt;
 *                           &lt;enumeration value="PrinterStatus"/&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/simpleType&gt;
 *                     &lt;/element&gt;
 *                   &lt;/sequence&gt;
 *                   &lt;attribute name="LanguageCode" type="{http://www.nrf-arts.org/IXRetail/namespace}LanguageCodeType" /&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *           &lt;element name="TotalAmount" minOccurs="0"&gt;
 *             &lt;complexType&gt;
 *               &lt;simpleContent&gt;
 *                 &lt;extension base="&lt;http://www.nrf-arts.org/IXRetail/namespace&gt;MonetaryAmount"&gt;
 *                   &lt;attribute name="Currency" type="{http://www.nrf-arts.org/IXRetail/namespace}CurrencyCode" /&gt;
 *                 &lt;/extension&gt;
 *               &lt;/simpleContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *           &lt;element name="Agent" type="{http://www.nrf-arts.org/IXRetail/namespace}AgentOnlineType" minOccurs="0"/&gt;
 *           &lt;element name="PINPadProgramLoad" minOccurs="0"&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name="ForceApplication" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *                     &lt;element name="ForceContactless" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *                     &lt;element name="ForceFirmware" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *                     &lt;element name="ForceOperatingSystem" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *                     &lt;element name="InstallEncrypt" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *                   &lt;/sequence&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *           &lt;element name="PrivateData" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;element name="EncryptionRSA" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="RequestType" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}ServiceRequestType" /&gt;
 *       &lt;attribute name="ApplicationSender" type="{http://www.nrf-arts.org/IXRetail/namespace}ApplicationType" /&gt;
 *       &lt;attribute name="WorkstationID" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}WorkstationIDType" /&gt;
 *       &lt;attribute name="POPID" type="{http://www.nrf-arts.org/IXRetail/namespace}POPIDType" /&gt;
 *       &lt;attribute name="RequestID" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}RequestIDType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "poSdata",
    "totalAmount",
    "agent",
    "pinPadProgramLoad",
    "privateData",
    "encryptionRSA"
})
@XmlRootElement(name = "ServiceRequest")
public class ServiceRequest {

    @XmlElement(name = "POSdata")
    protected ServiceRequest.POSdata poSdata;
    @XmlElement(name = "TotalAmount")
    protected ServiceRequest.TotalAmount totalAmount;
    @XmlElement(name = "Agent")
    @XmlSchemaType(name = "string")
    protected AgentOnlineType agent;
    @XmlElement(name = "PINPadProgramLoad")
    protected ServiceRequest.PINPadProgramLoad pinPadProgramLoad;
    @XmlElement(name = "PrivateData")
    protected List<Object> privateData;
    @XmlElement(name = "EncryptionRSA")
    protected String encryptionRSA;
    @XmlAttribute(name = "RequestType", required = true)
    protected ServiceRequestType requestType;
    @XmlAttribute(name = "ApplicationSender")
    protected String applicationSender;
    @XmlAttribute(name = "WorkstationID", required = true)
    protected String workstationID;
    @XmlAttribute(name = "POPID")
    protected String popid;
    @XmlAttribute(name = "RequestID", required = true)
    protected String requestID;

    /**
     * Gets the value of the poSdata property.
     * 
     * @return
     *     possible object is
     *     {@link POSdata }
     *     
     */
    public POSdata getPOSdata() {
        return poSdata;
    }

    /**
     * Sets the value of the poSdata property.
     * 
     * @param value
     *     allowed object is
     *     {@link POSdata }
     *     
     */
    public void setPOSdata(POSdata value) {
        this.poSdata = value;
    }

    /**
     * Gets the value of the totalAmount property.
     * 
     * @return
     *     possible object is
     *     {@link TotalAmount }
     *     
     */
    public TotalAmount getTotalAmount() {
        return totalAmount;
    }

    /**
     * Sets the value of the totalAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link TotalAmount }
     *     
     */
    public void setTotalAmount(TotalAmount value) {
        this.totalAmount = value;
    }

    /**
     * Gets the value of the agent property.
     * 
     * @return
     *     possible object is
     *     {@link AgentOnlineType }
     *     
     */
    public AgentOnlineType getAgent() {
        return agent;
    }

    /**
     * Sets the value of the agent property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgentOnlineType }
     *     
     */
    public void setAgent(AgentOnlineType value) {
        this.agent = value;
    }

    /**
     * Gets the value of the pinPadProgramLoad property.
     * 
     * @return
     *     possible object is
     *     {@link PINPadProgramLoad }
     *     
     */
    public PINPadProgramLoad getPINPadProgramLoad() {
        return pinPadProgramLoad;
    }

    /**
     * Sets the value of the pinPadProgramLoad property.
     * 
     * @param value
     *     allowed object is
     *     {@link PINPadProgramLoad }
     *     
     */
    public void setPINPadProgramLoad(PINPadProgramLoad value) {
        this.pinPadProgramLoad = value;
    }

    /**
     * Gets the value of the privateData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the privateData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrivateData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getPrivateData() {
        if (privateData == null) {
            privateData = new ArrayList<Object>();
        }
        return this.privateData;
    }

    /**
     * Gets the value of the encryptionRSA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncryptionRSA() {
        return encryptionRSA;
    }

    /**
     * Sets the value of the encryptionRSA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncryptionRSA(String value) {
        this.encryptionRSA = value;
    }

    /**
     * Gets the value of the requestType property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceRequestType }
     *     
     */
    public ServiceRequestType getRequestType() {
        return requestType;
    }

    /**
     * Sets the value of the requestType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceRequestType }
     *     
     */
    public void setRequestType(ServiceRequestType value) {
        this.requestType = value;
    }

    /**
     * Gets the value of the applicationSender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationSender() {
        return applicationSender;
    }

    /**
     * Sets the value of the applicationSender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationSender(String value) {
        this.applicationSender = value;
    }

    /**
     * Gets the value of the workstationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkstationID() {
        return workstationID;
    }

    /**
     * Sets the value of the workstationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkstationID(String value) {
        this.workstationID = value;
    }

    /**
     * Gets the value of the popid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOPID() {
        return popid;
    }

    /**
     * Sets the value of the popid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOPID(String value) {
        this.popid = value;
    }

    /**
     * Gets the value of the requestID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestID() {
        return requestID;
    }

    /**
     * Sets the value of the requestID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestID(String value) {
        this.requestID = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ForceApplication" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
     *         &lt;element name="ForceContactless" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
     *         &lt;element name="ForceFirmware" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
     *         &lt;element name="ForceOperatingSystem" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
     *         &lt;element name="InstallEncrypt" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "forceApplication",
        "forceContactless",
        "forceFirmware",
        "forceOperatingSystem",
        "installEncrypt"
    })
    public static class PINPadProgramLoad {

        @XmlElement(name = "ForceApplication")
        protected Boolean forceApplication;
        @XmlElement(name = "ForceContactless")
        protected Boolean forceContactless;
        @XmlElement(name = "ForceFirmware")
        protected Boolean forceFirmware;
        @XmlElement(name = "ForceOperatingSystem")
        protected Boolean forceOperatingSystem;
        @XmlElement(name = "InstallEncrypt")
        protected Boolean installEncrypt;

        /**
         * Gets the value of the forceApplication property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isForceApplication() {
            return forceApplication;
        }

        /**
         * Sets the value of the forceApplication property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setForceApplication(Boolean value) {
            this.forceApplication = value;
        }

        /**
         * Gets the value of the forceContactless property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isForceContactless() {
            return forceContactless;
        }

        /**
         * Sets the value of the forceContactless property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setForceContactless(Boolean value) {
            this.forceContactless = value;
        }

        /**
         * Gets the value of the forceFirmware property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isForceFirmware() {
            return forceFirmware;
        }

        /**
         * Sets the value of the forceFirmware property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setForceFirmware(Boolean value) {
            this.forceFirmware = value;
        }

        /**
         * Gets the value of the forceOperatingSystem property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isForceOperatingSystem() {
            return forceOperatingSystem;
        }

        /**
         * Sets the value of the forceOperatingSystem property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setForceOperatingSystem(Boolean value) {
            this.forceOperatingSystem = value;
        }

        /**
         * Gets the value of the installEncrypt property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isInstallEncrypt() {
            return installEncrypt;
        }

        /**
         * Sets the value of the installEncrypt property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setInstallEncrypt(Boolean value) {
            this.installEncrypt = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="POSTimeStamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
     *         &lt;element name="ShiftNumber" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer"&gt;
     *               &lt;totalDigits value="3"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="ClerkID" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer"&gt;
     *               &lt;totalDigits value="9"/&gt;
     *               &lt;minInclusive value="0"/&gt;
     *               &lt;maxInclusive value="999999999"/&gt;
     *               &lt;fractionDigits value="0"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="ClerkPermission" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="Low"/&gt;
     *               &lt;enumeration value="Medium"/&gt;
     *               &lt;enumeration value="High"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Reference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="DiagnosisMethod" minOccurs="0"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="OnLine"/&gt;
     *               &lt;enumeration value="Local"/&gt;
     *               &lt;enumeration value="POPInit"/&gt;
     *               &lt;enumeration value="POPInitAll"/&gt;
     *               &lt;enumeration value="PrinterStatus"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="LanguageCode" type="{http://www.nrf-arts.org/IXRetail/namespace}LanguageCodeType" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "posTimeStamp",
        "shiftNumber",
        "clerkID",
        "clerkPermission",
        "reference",
        "diagnosisMethod"
    })
    public static class POSdata {

        @XmlElement(name = "POSTimeStamp", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar posTimeStamp;
        @XmlElement(name = "ShiftNumber")
        protected BigInteger shiftNumber;
        @XmlElement(name = "ClerkID")
        protected Integer clerkID;
        @XmlElement(name = "ClerkPermission")
        protected String clerkPermission;
        @XmlElement(name = "Reference")
        protected String reference;
        @XmlElement(name = "DiagnosisMethod")
        protected String diagnosisMethod;
        @XmlAttribute(name = "LanguageCode")
        protected LanguageCodeType languageCode;

        /**
         * Gets the value of the posTimeStamp property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getPOSTimeStamp() {
            return posTimeStamp;
        }

        /**
         * Sets the value of the posTimeStamp property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setPOSTimeStamp(XMLGregorianCalendar value) {
            this.posTimeStamp = value;
        }

        /**
         * Gets the value of the shiftNumber property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getShiftNumber() {
            return shiftNumber;
        }

        /**
         * Sets the value of the shiftNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setShiftNumber(BigInteger value) {
            this.shiftNumber = value;
        }

        /**
         * Gets the value of the clerkID property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getClerkID() {
            return clerkID;
        }

        /**
         * Sets the value of the clerkID property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setClerkID(Integer value) {
            this.clerkID = value;
        }

        /**
         * Gets the value of the clerkPermission property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClerkPermission() {
            return clerkPermission;
        }

        /**
         * Sets the value of the clerkPermission property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClerkPermission(String value) {
            this.clerkPermission = value;
        }

        /**
         * Gets the value of the reference property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReference() {
            return reference;
        }

        /**
         * Sets the value of the reference property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReference(String value) {
            this.reference = value;
        }

        /**
         * Gets the value of the diagnosisMethod property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDiagnosisMethod() {
            return diagnosisMethod;
        }

        /**
         * Sets the value of the diagnosisMethod property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDiagnosisMethod(String value) {
            this.diagnosisMethod = value;
        }

        /**
         * Gets the value of the languageCode property.
         * 
         * @return
         *     possible object is
         *     {@link LanguageCodeType }
         *     
         */
        public LanguageCodeType getLanguageCode() {
            return languageCode;
        }

        /**
         * Sets the value of the languageCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link LanguageCodeType }
         *     
         */
        public void setLanguageCode(LanguageCodeType value) {
            this.languageCode = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.nrf-arts.org/IXRetail/namespace&gt;MonetaryAmount"&gt;
     *       &lt;attribute name="Currency" type="{http://www.nrf-arts.org/IXRetail/namespace}CurrencyCode" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class TotalAmount {

        @XmlValue
        protected BigDecimal value;
        @XmlAttribute(name = "Currency")
        protected CurrencyCode currency;

        /**
         * expl: common definition of monetary amount data type
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setValue(BigDecimal value) {
            this.value = value;
        }

        /**
         * Gets the value of the currency property.
         * 
         * @return
         *     possible object is
         *     {@link CurrencyCode }
         *     
         */
        public CurrencyCode getCurrency() {
            return currency;
        }

        /**
         * Sets the value of the currency property.
         * 
         * @param value
         *     allowed object is
         *     {@link CurrencyCode }
         *     
         */
        public void setCurrency(CurrencyCode value) {
            this.currency = value;
        }

    }

}
