//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 04:13:46 PM CDT 
//


package com.mastercard.gateway.ats.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceRequestType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ServiceRequestType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Diagnosis"/&gt;
 *     &lt;enumeration value="SendOfflineTransactions"/&gt;
 *     &lt;enumeration value="Reconciliation"/&gt;
 *     &lt;enumeration value="ReconciliationWithClosure"/&gt;
 *     &lt;enumeration value="GlobalReconciliation"/&gt;
 *     &lt;enumeration value="GlobalReconciliationWithClosure"/&gt;
 *     &lt;enumeration value="Administration"/&gt;
 *     &lt;enumeration value="Login"/&gt;
 *     &lt;enumeration value="Logoff"/&gt;
 *     &lt;enumeration value="OnlineAgent"/&gt;
 *     &lt;enumeration value="RepeatLastMessage"/&gt;
 *     &lt;enumeration value="GetReference"/&gt;
 *     &lt;enumeration value="EncryptionRSAPublicKey"/&gt;
 *     &lt;enumeration value="AcquireDevice"/&gt;
 *     &lt;enumeration value="ReleaseDevice"/&gt;
 *     &lt;enumeration value="RuleLookup"/&gt;
 *     &lt;enumeration value="PINPadProgramLoad"/&gt;
 *     &lt;enumeration value="QuerySoftwareVersions"/&gt;
 *     &lt;enumeration value="MemoryReport"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ServiceRequestType")
@XmlEnum
public enum ServiceRequestType {

    @XmlEnumValue("Diagnosis")
    DIAGNOSIS("Diagnosis"),
    @XmlEnumValue("SendOfflineTransactions")
    SEND_OFFLINE_TRANSACTIONS("SendOfflineTransactions"),
    @XmlEnumValue("Reconciliation")
    RECONCILIATION("Reconciliation"),
    @XmlEnumValue("ReconciliationWithClosure")
    RECONCILIATION_WITH_CLOSURE("ReconciliationWithClosure"),
    @XmlEnumValue("GlobalReconciliation")
    GLOBAL_RECONCILIATION("GlobalReconciliation"),
    @XmlEnumValue("GlobalReconciliationWithClosure")
    GLOBAL_RECONCILIATION_WITH_CLOSURE("GlobalReconciliationWithClosure"),
    @XmlEnumValue("Administration")
    ADMINISTRATION("Administration"),
    @XmlEnumValue("Login")
    LOGIN("Login"),
    @XmlEnumValue("Logoff")
    LOGOFF("Logoff"),
    @XmlEnumValue("OnlineAgent")
    ONLINE_AGENT("OnlineAgent"),
    @XmlEnumValue("RepeatLastMessage")
    REPEAT_LAST_MESSAGE("RepeatLastMessage"),
    @XmlEnumValue("GetReference")
    GET_REFERENCE("GetReference"),
    @XmlEnumValue("EncryptionRSAPublicKey")
    ENCRYPTION_RSA_PUBLIC_KEY("EncryptionRSAPublicKey"),
    @XmlEnumValue("AcquireDevice")
    ACQUIRE_DEVICE("AcquireDevice"),
    @XmlEnumValue("ReleaseDevice")
    RELEASE_DEVICE("ReleaseDevice"),
    @XmlEnumValue("RuleLookup")
    RULE_LOOKUP("RuleLookup"),
    @XmlEnumValue("PINPadProgramLoad")
    PIN_PAD_PROGRAM_LOAD("PINPadProgramLoad"),
    @XmlEnumValue("QuerySoftwareVersions")
    QUERY_SOFTWARE_VERSIONS("QuerySoftwareVersions"),
    @XmlEnumValue("MemoryReport")
    MEMORY_REPORT("MemoryReport");
    private final String value;

    ServiceRequestType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ServiceRequestType fromValue(String v) {
        for (ServiceRequestType c: ServiceRequestType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
