//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 04:13:46 PM CDT 
//


package com.mastercard.gateway.ats.domain;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="Terminal" minOccurs="0"&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                   &lt;attribute name="TerminalID" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}TerminalIDType" /&gt;
 *                   &lt;attribute name="TerminalBatch" type="{http://www.nrf-arts.org/IXRetail/namespace}BatchCodeType" /&gt;
 *                   &lt;attribute name="STAN" type="{http://www.nrf-arts.org/IXRetail/namespace}STANtype" /&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *           &lt;element name="ErrorDetail" type="{http://www.nrf-arts.org/IXRetail/namespace}ATSErrorDetailType" minOccurs="0"/&gt;
 *           &lt;element name="Authorisation" minOccurs="0"&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                   &lt;attribute name="AcquirerID" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}AcquirerType" /&gt;
 *                   &lt;attribute name="TimeStamp" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *                   &lt;attribute name="ApprovalCode" type="{http://www.nrf-arts.org/IXRetail/namespace}AuthorisationCodeType" /&gt;
 *                   &lt;attribute name="AcquirerBatch" type="{http://www.nrf-arts.org/IXRetail/namespace}BatchCodeType" /&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *           &lt;element name="Reconciliation" minOccurs="0"&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name="TotalAmount" maxOccurs="unbounded"&gt;
 *                       &lt;complexType&gt;
 *                         &lt;simpleContent&gt;
 *                           &lt;extension base="&lt;http://www.nrf-arts.org/IXRetail/namespace&gt;MonetaryAmount"&gt;
 *                             &lt;attribute name="NumberPayments" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *                             &lt;attribute name="PaymentType" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}TransactionType" /&gt;
 *                             &lt;attribute name="Currency" type="{http://www.nrf-arts.org/IXRetail/namespace}CurrencyCode" /&gt;
 *                             &lt;attribute name="CardCircuit" type="{http://www.nrf-arts.org/IXRetail/namespace}CardCircuitType" /&gt;
 *                             &lt;attribute name="Acquirer" type="{http://www.nrf-arts.org/IXRetail/namespace}AcquirerType" /&gt;
 *                             &lt;attribute name="NumberHeld" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *                             &lt;attribute name="AmountHeld" type="{http://www.nrf-arts.org/IXRetail/namespace}MonetaryAmount" /&gt;
 *                           &lt;/extension&gt;
 *                         &lt;/simpleContent&gt;
 *                       &lt;/complexType&gt;
 *                     &lt;/element&gt;
 *                   &lt;/sequence&gt;
 *                   &lt;attribute name="LanguageCode" type="{http://www.nrf-arts.org/IXRetail/namespace}LanguageCodeType" /&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *           &lt;element name="Submission" minOccurs="0"&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name="Successful"&gt;
 *                       &lt;complexType&gt;
 *                         &lt;simpleContent&gt;
 *                           &lt;extension base="&lt;http://www.nrf-arts.org/IXRetail/namespace&gt;MonetaryAmount"&gt;
 *                             &lt;attribute name="NumberPayments" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *                           &lt;/extension&gt;
 *                         &lt;/simpleContent&gt;
 *                       &lt;/complexType&gt;
 *                     &lt;/element&gt;
 *                     &lt;element name="Failed"&gt;
 *                       &lt;complexType&gt;
 *                         &lt;simpleContent&gt;
 *                           &lt;extension base="&lt;http://www.nrf-arts.org/IXRetail/namespace&gt;MonetaryAmount"&gt;
 *                             &lt;attribute name="NumberPayments" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *                           &lt;/extension&gt;
 *                         &lt;/simpleContent&gt;
 *                       &lt;/complexType&gt;
 *                     &lt;/element&gt;
 *                   &lt;/sequence&gt;
 *                   &lt;attribute name="LanguageCode" type="{http://www.nrf-arts.org/IXRetail/namespace}LanguageCodeType" /&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *           &lt;element name="DiagnosisResult" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *           &lt;element name="OriginalHeader" minOccurs="0"&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                   &lt;attribute name="RequestType" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}ServiceRequestType" /&gt;
 *                   &lt;attribute name="ApplicationSender" type="{http://www.nrf-arts.org/IXRetail/namespace}ApplicationType" /&gt;
 *                   &lt;attribute name="WorkstationID" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}WorkstationIDType" /&gt;
 *                   &lt;attribute name="POPID" type="{http://www.nrf-arts.org/IXRetail/namespace}POPIDType" /&gt;
 *                   &lt;attribute name="RequestID" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}RequestIDType" /&gt;
 *                   &lt;attribute name="OverallResult" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}RequestResultType" /&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *           &lt;element name="PrivateData" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="EncryptionModulus" type="{http://www.w3.org/2001/XMLSchema}hexBinary"/&gt;
 *           &lt;element name="EncryptionExponent" type="{http://www.w3.org/2001/XMLSchema}hexBinary"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;element name="Reference" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Versions" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Devices" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Device" maxOccurs="unbounded"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="SerialNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                       &lt;element name="TimeStamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *                                       &lt;element name="PTID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                       &lt;element name="Manufacturer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                       &lt;element name="Model" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                       &lt;element name="ApplicationName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                       &lt;element name="ApplicationVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                       &lt;element name="ContactlessKernelName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                       &lt;element name="ContactlessKernelVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                       &lt;element name="FirmwareName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                       &lt;element name="FirmwareVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                       &lt;element name="OSName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                       &lt;element name="OSVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                       &lt;element name="EncryptionModuleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                       &lt;element name="EncryptionModuleVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                       &lt;element name="Product" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                     &lt;/sequence&gt;
 *                                     &lt;attribute name="POPID" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}POPIDType" /&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="RequestType" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}ServiceRequestType" /&gt;
 *       &lt;attribute name="ApplicationSender" type="{http://www.nrf-arts.org/IXRetail/namespace}ApplicationType" /&gt;
 *       &lt;attribute name="WorkstationID" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}WorkstationIDType" /&gt;
 *       &lt;attribute name="POPID" type="{http://www.nrf-arts.org/IXRetail/namespace}POPIDType" /&gt;
 *       &lt;attribute name="RequestID" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}RequestIDType" /&gt;
 *       &lt;attribute name="OverallResult" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}RequestResultType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "terminal",
    "errorDetail",
    "authorisation",
    "reconciliation",
    "submission",
    "diagnosisResult",
    "originalHeader",
    "privateData",
    "encryptionModulus",
    "encryptionExponent",
    "reference",
    "versions"
})
@XmlRootElement(name = "ServiceResponse")
public class ServiceResponse {

    @XmlElement(name = "Terminal")
    protected ServiceResponse.Terminal terminal;
    @XmlElement(name = "ErrorDetail")
    protected ATSErrorDetailType errorDetail;
    @XmlElement(name = "Authorisation")
    protected ServiceResponse.Authorisation authorisation;
    @XmlElement(name = "Reconciliation")
    protected ServiceResponse.Reconciliation reconciliation;
    @XmlElement(name = "Submission")
    protected ServiceResponse.Submission submission;
    @XmlElement(name = "DiagnosisResult")
    protected String diagnosisResult;
    @XmlElement(name = "OriginalHeader")
    protected ServiceResponse.OriginalHeader originalHeader;
    @XmlElement(name = "PrivateData")
    protected List<Object> privateData;
    @XmlElement(name = "EncryptionModulus", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] encryptionModulus;
    @XmlElement(name = "EncryptionExponent", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] encryptionExponent;
    @XmlElement(name = "Reference")
    protected String reference;
    @XmlElement(name = "Versions")
    protected List<Versions> versions;
    @XmlAttribute(name = "RequestType", required = true)
    protected ServiceRequestType requestType;
    @XmlAttribute(name = "ApplicationSender")
    protected String applicationSender;
    @XmlAttribute(name = "WorkstationID", required = true)
    protected String workstationID;
    @XmlAttribute(name = "POPID")
    protected String popid;
    @XmlAttribute(name = "RequestID", required = true)
    protected String requestID;
    @XmlAttribute(name = "OverallResult", required = true)
    protected RequestResultType overallResult;

    /**
     * Gets the value of the terminal property.
     * 
     * @return
     *     possible object is
     *     {@link Terminal }
     *     
     */
    public Terminal getTerminal() {
        return terminal;
    }

    /**
     * Sets the value of the terminal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Terminal }
     *     
     */
    public void setTerminal(Terminal value) {
        this.terminal = value;
    }

    /**
     * Gets the value of the errorDetail property.
     * 
     * @return
     *     possible object is
     *     {@link ATSErrorDetailType }
     *     
     */
    public ATSErrorDetailType getErrorDetail() {
        return errorDetail;
    }

    /**
     * Sets the value of the errorDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link ATSErrorDetailType }
     *     
     */
    public void setErrorDetail(ATSErrorDetailType value) {
        this.errorDetail = value;
    }

    /**
     * Gets the value of the authorisation property.
     * 
     * @return
     *     possible object is
     *     {@link Authorisation }
     *     
     */
    public Authorisation getAuthorisation() {
        return authorisation;
    }

    /**
     * Sets the value of the authorisation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Authorisation }
     *     
     */
    public void setAuthorisation(Authorisation value) {
        this.authorisation = value;
    }

    /**
     * Gets the value of the reconciliation property.
     * 
     * @return
     *     possible object is
     *     {@link Reconciliation }
     *     
     */
    public Reconciliation getReconciliation() {
        return reconciliation;
    }

    /**
     * Sets the value of the reconciliation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reconciliation }
     *     
     */
    public void setReconciliation(Reconciliation value) {
        this.reconciliation = value;
    }

    /**
     * Gets the value of the submission property.
     * 
     * @return
     *     possible object is
     *     {@link Submission }
     *     
     */
    public Submission getSubmission() {
        return submission;
    }

    /**
     * Sets the value of the submission property.
     * 
     * @param value
     *     allowed object is
     *     {@link Submission }
     *     
     */
    public void setSubmission(Submission value) {
        this.submission = value;
    }

    /**
     * Gets the value of the diagnosisResult property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiagnosisResult() {
        return diagnosisResult;
    }

    /**
     * Sets the value of the diagnosisResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiagnosisResult(String value) {
        this.diagnosisResult = value;
    }

    /**
     * Gets the value of the originalHeader property.
     * 
     * @return
     *     possible object is
     *     {@link OriginalHeader }
     *     
     */
    public OriginalHeader getOriginalHeader() {
        return originalHeader;
    }

    /**
     * Sets the value of the originalHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link OriginalHeader }
     *     
     */
    public void setOriginalHeader(OriginalHeader value) {
        this.originalHeader = value;
    }

    /**
     * Gets the value of the privateData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the privateData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrivateData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getPrivateData() {
        if (privateData == null) {
            privateData = new ArrayList<Object>();
        }
        return this.privateData;
    }

    /**
     * Gets the value of the encryptionModulus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getEncryptionModulus() {
        return encryptionModulus;
    }

    /**
     * Sets the value of the encryptionModulus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncryptionModulus(byte[] value) {
        this.encryptionModulus = value;
    }

    /**
     * Gets the value of the encryptionExponent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getEncryptionExponent() {
        return encryptionExponent;
    }

    /**
     * Sets the value of the encryptionExponent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncryptionExponent(byte[] value) {
        this.encryptionExponent = value;
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReference(String value) {
        this.reference = value;
    }

    /**
     * Gets the value of the versions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the versions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVersions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Versions }
     * 
     * 
     */
    public List<Versions> getVersions() {
        if (versions == null) {
            versions = new ArrayList<Versions>();
        }
        return this.versions;
    }

    /**
     * Gets the value of the requestType property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceRequestType }
     *     
     */
    public ServiceRequestType getRequestType() {
        return requestType;
    }

    /**
     * Sets the value of the requestType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceRequestType }
     *     
     */
    public void setRequestType(ServiceRequestType value) {
        this.requestType = value;
    }

    /**
     * Gets the value of the applicationSender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationSender() {
        return applicationSender;
    }

    /**
     * Sets the value of the applicationSender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationSender(String value) {
        this.applicationSender = value;
    }

    /**
     * Gets the value of the workstationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkstationID() {
        return workstationID;
    }

    /**
     * Sets the value of the workstationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkstationID(String value) {
        this.workstationID = value;
    }

    /**
     * Gets the value of the popid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOPID() {
        return popid;
    }

    /**
     * Sets the value of the popid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOPID(String value) {
        this.popid = value;
    }

    /**
     * Gets the value of the requestID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestID() {
        return requestID;
    }

    /**
     * Sets the value of the requestID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestID(String value) {
        this.requestID = value;
    }

    /**
     * Gets the value of the overallResult property.
     * 
     * @return
     *     possible object is
     *     {@link RequestResultType }
     *     
     */
    public RequestResultType getOverallResult() {
        return overallResult;
    }

    /**
     * Sets the value of the overallResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestResultType }
     *     
     */
    public void setOverallResult(RequestResultType value) {
        this.overallResult = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="AcquirerID" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}AcquirerType" /&gt;
     *       &lt;attribute name="TimeStamp" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
     *       &lt;attribute name="ApprovalCode" type="{http://www.nrf-arts.org/IXRetail/namespace}AuthorisationCodeType" /&gt;
     *       &lt;attribute name="AcquirerBatch" type="{http://www.nrf-arts.org/IXRetail/namespace}BatchCodeType" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Authorisation {

        @XmlAttribute(name = "AcquirerID", required = true)
        protected String acquirerID;
        @XmlAttribute(name = "TimeStamp", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar timeStamp;
        @XmlAttribute(name = "ApprovalCode")
        protected String approvalCode;
        @XmlAttribute(name = "AcquirerBatch")
        protected String acquirerBatch;

        /**
         * Gets the value of the acquirerID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAcquirerID() {
            return acquirerID;
        }

        /**
         * Sets the value of the acquirerID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAcquirerID(String value) {
            this.acquirerID = value;
        }

        /**
         * Gets the value of the timeStamp property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTimeStamp() {
            return timeStamp;
        }

        /**
         * Sets the value of the timeStamp property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTimeStamp(XMLGregorianCalendar value) {
            this.timeStamp = value;
        }

        /**
         * Gets the value of the approvalCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApprovalCode() {
            return approvalCode;
        }

        /**
         * Sets the value of the approvalCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApprovalCode(String value) {
            this.approvalCode = value;
        }

        /**
         * Gets the value of the acquirerBatch property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAcquirerBatch() {
            return acquirerBatch;
        }

        /**
         * Sets the value of the acquirerBatch property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAcquirerBatch(String value) {
            this.acquirerBatch = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="RequestType" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}ServiceRequestType" /&gt;
     *       &lt;attribute name="ApplicationSender" type="{http://www.nrf-arts.org/IXRetail/namespace}ApplicationType" /&gt;
     *       &lt;attribute name="WorkstationID" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}WorkstationIDType" /&gt;
     *       &lt;attribute name="POPID" type="{http://www.nrf-arts.org/IXRetail/namespace}POPIDType" /&gt;
     *       &lt;attribute name="RequestID" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}RequestIDType" /&gt;
     *       &lt;attribute name="OverallResult" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}RequestResultType" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class OriginalHeader {

        @XmlAttribute(name = "RequestType", required = true)
        protected ServiceRequestType requestType;
        @XmlAttribute(name = "ApplicationSender")
        protected String applicationSender;
        @XmlAttribute(name = "WorkstationID", required = true)
        protected String workstationID;
        @XmlAttribute(name = "POPID")
        protected String popid;
        @XmlAttribute(name = "RequestID", required = true)
        protected String requestID;
        @XmlAttribute(name = "OverallResult", required = true)
        protected RequestResultType overallResult;

        /**
         * Gets the value of the requestType property.
         * 
         * @return
         *     possible object is
         *     {@link ServiceRequestType }
         *     
         */
        public ServiceRequestType getRequestType() {
            return requestType;
        }

        /**
         * Sets the value of the requestType property.
         * 
         * @param value
         *     allowed object is
         *     {@link ServiceRequestType }
         *     
         */
        public void setRequestType(ServiceRequestType value) {
            this.requestType = value;
        }

        /**
         * Gets the value of the applicationSender property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApplicationSender() {
            return applicationSender;
        }

        /**
         * Sets the value of the applicationSender property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApplicationSender(String value) {
            this.applicationSender = value;
        }

        /**
         * Gets the value of the workstationID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWorkstationID() {
            return workstationID;
        }

        /**
         * Sets the value of the workstationID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWorkstationID(String value) {
            this.workstationID = value;
        }

        /**
         * Gets the value of the popid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPOPID() {
            return popid;
        }

        /**
         * Sets the value of the popid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPOPID(String value) {
            this.popid = value;
        }

        /**
         * Gets the value of the requestID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRequestID() {
            return requestID;
        }

        /**
         * Sets the value of the requestID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRequestID(String value) {
            this.requestID = value;
        }

        /**
         * Gets the value of the overallResult property.
         * 
         * @return
         *     possible object is
         *     {@link RequestResultType }
         *     
         */
        public RequestResultType getOverallResult() {
            return overallResult;
        }

        /**
         * Sets the value of the overallResult property.
         * 
         * @param value
         *     allowed object is
         *     {@link RequestResultType }
         *     
         */
        public void setOverallResult(RequestResultType value) {
            this.overallResult = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="TotalAmount" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.nrf-arts.org/IXRetail/namespace&gt;MonetaryAmount"&gt;
     *                 &lt;attribute name="NumberPayments" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
     *                 &lt;attribute name="PaymentType" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}TransactionType" /&gt;
     *                 &lt;attribute name="Currency" type="{http://www.nrf-arts.org/IXRetail/namespace}CurrencyCode" /&gt;
     *                 &lt;attribute name="CardCircuit" type="{http://www.nrf-arts.org/IXRetail/namespace}CardCircuitType" /&gt;
     *                 &lt;attribute name="Acquirer" type="{http://www.nrf-arts.org/IXRetail/namespace}AcquirerType" /&gt;
     *                 &lt;attribute name="NumberHeld" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
     *                 &lt;attribute name="AmountHeld" type="{http://www.nrf-arts.org/IXRetail/namespace}MonetaryAmount" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="LanguageCode" type="{http://www.nrf-arts.org/IXRetail/namespace}LanguageCodeType" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "totalAmount"
    })
    public static class Reconciliation {

        @XmlElement(name = "TotalAmount", required = true)
        protected List<TotalAmount> totalAmount;
        @XmlAttribute(name = "LanguageCode")
        protected LanguageCodeType languageCode;

        /**
         * Gets the value of the totalAmount property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the totalAmount property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTotalAmount().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TotalAmount }
         * 
         * 
         */
        public List<TotalAmount> getTotalAmount() {
            if (totalAmount == null) {
                totalAmount = new ArrayList<TotalAmount>();
            }
            return this.totalAmount;
        }

        /**
         * Gets the value of the languageCode property.
         * 
         * @return
         *     possible object is
         *     {@link LanguageCodeType }
         *     
         */
        public LanguageCodeType getLanguageCode() {
            return languageCode;
        }

        /**
         * Sets the value of the languageCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link LanguageCodeType }
         *     
         */
        public void setLanguageCode(LanguageCodeType value) {
            this.languageCode = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.nrf-arts.org/IXRetail/namespace&gt;MonetaryAmount"&gt;
         *       &lt;attribute name="NumberPayments" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
         *       &lt;attribute name="PaymentType" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}TransactionType" /&gt;
         *       &lt;attribute name="Currency" type="{http://www.nrf-arts.org/IXRetail/namespace}CurrencyCode" /&gt;
         *       &lt;attribute name="CardCircuit" type="{http://www.nrf-arts.org/IXRetail/namespace}CardCircuitType" /&gt;
         *       &lt;attribute name="Acquirer" type="{http://www.nrf-arts.org/IXRetail/namespace}AcquirerType" /&gt;
         *       &lt;attribute name="NumberHeld" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
         *       &lt;attribute name="AmountHeld" type="{http://www.nrf-arts.org/IXRetail/namespace}MonetaryAmount" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class TotalAmount {

            @XmlValue
            protected BigDecimal value;
            @XmlAttribute(name = "NumberPayments", required = true)
            protected BigInteger numberPayments;
            @XmlAttribute(name = "PaymentType", required = true)
            protected TransactionType paymentType;
            @XmlAttribute(name = "Currency")
            protected CurrencyCode currency;
            @XmlAttribute(name = "CardCircuit")
            protected String cardCircuit;
            @XmlAttribute(name = "Acquirer")
            protected String acquirer;
            @XmlAttribute(name = "NumberHeld")
            protected BigInteger numberHeld;
            @XmlAttribute(name = "AmountHeld")
            protected BigDecimal amountHeld;

            /**
             * expl: common definition of monetary amount data type
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setValue(BigDecimal value) {
                this.value = value;
            }

            /**
             * Gets the value of the numberPayments property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getNumberPayments() {
                return numberPayments;
            }

            /**
             * Sets the value of the numberPayments property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setNumberPayments(BigInteger value) {
                this.numberPayments = value;
            }

            /**
             * Gets the value of the paymentType property.
             * 
             * @return
             *     possible object is
             *     {@link TransactionType }
             *     
             */
            public TransactionType getPaymentType() {
                return paymentType;
            }

            /**
             * Sets the value of the paymentType property.
             * 
             * @param value
             *     allowed object is
             *     {@link TransactionType }
             *     
             */
            public void setPaymentType(TransactionType value) {
                this.paymentType = value;
            }

            /**
             * Gets the value of the currency property.
             * 
             * @return
             *     possible object is
             *     {@link CurrencyCode }
             *     
             */
            public CurrencyCode getCurrency() {
                return currency;
            }

            /**
             * Sets the value of the currency property.
             * 
             * @param value
             *     allowed object is
             *     {@link CurrencyCode }
             *     
             */
            public void setCurrency(CurrencyCode value) {
                this.currency = value;
            }

            /**
             * Gets the value of the cardCircuit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCardCircuit() {
                return cardCircuit;
            }

            /**
             * Sets the value of the cardCircuit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCardCircuit(String value) {
                this.cardCircuit = value;
            }

            /**
             * Gets the value of the acquirer property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAcquirer() {
                return acquirer;
            }

            /**
             * Sets the value of the acquirer property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAcquirer(String value) {
                this.acquirer = value;
            }

            /**
             * Gets the value of the numberHeld property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getNumberHeld() {
                return numberHeld;
            }

            /**
             * Sets the value of the numberHeld property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setNumberHeld(BigInteger value) {
                this.numberHeld = value;
            }

            /**
             * Gets the value of the amountHeld property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getAmountHeld() {
                return amountHeld;
            }

            /**
             * Sets the value of the amountHeld property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setAmountHeld(BigDecimal value) {
                this.amountHeld = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Successful"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.nrf-arts.org/IXRetail/namespace&gt;MonetaryAmount"&gt;
     *                 &lt;attribute name="NumberPayments" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Failed"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.nrf-arts.org/IXRetail/namespace&gt;MonetaryAmount"&gt;
     *                 &lt;attribute name="NumberPayments" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="LanguageCode" type="{http://www.nrf-arts.org/IXRetail/namespace}LanguageCodeType" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "successful",
        "failed"
    })
    public static class Submission {

        @XmlElement(name = "Successful", required = true)
        protected ServiceResponse.Submission.Successful successful;
        @XmlElement(name = "Failed", required = true)
        protected ServiceResponse.Submission.Failed failed;
        @XmlAttribute(name = "LanguageCode")
        protected LanguageCodeType languageCode;

        /**
         * Gets the value of the successful property.
         * 
         * @return
         *     possible object is
         *     {@link Successful }
         *     
         */
        public Successful getSuccessful() {
            return successful;
        }

        /**
         * Sets the value of the successful property.
         * 
         * @param value
         *     allowed object is
         *     {@link Successful }
         *     
         */
        public void setSuccessful(Successful value) {
            this.successful = value;
        }

        /**
         * Gets the value of the failed property.
         * 
         * @return
         *     possible object is
         *     {@link Failed }
         *     
         */
        public Failed getFailed() {
            return failed;
        }

        /**
         * Sets the value of the failed property.
         * 
         * @param value
         *     allowed object is
         *     {@link Failed }
         *     
         */
        public void setFailed(Failed value) {
            this.failed = value;
        }

        /**
         * Gets the value of the languageCode property.
         * 
         * @return
         *     possible object is
         *     {@link LanguageCodeType }
         *     
         */
        public LanguageCodeType getLanguageCode() {
            return languageCode;
        }

        /**
         * Sets the value of the languageCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link LanguageCodeType }
         *     
         */
        public void setLanguageCode(LanguageCodeType value) {
            this.languageCode = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.nrf-arts.org/IXRetail/namespace&gt;MonetaryAmount"&gt;
         *       &lt;attribute name="NumberPayments" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Failed {

            @XmlValue
            protected BigDecimal value;
            @XmlAttribute(name = "NumberPayments", required = true)
            protected BigInteger numberPayments;

            /**
             * expl: common definition of monetary amount data type
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setValue(BigDecimal value) {
                this.value = value;
            }

            /**
             * Gets the value of the numberPayments property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getNumberPayments() {
                return numberPayments;
            }

            /**
             * Sets the value of the numberPayments property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setNumberPayments(BigInteger value) {
                this.numberPayments = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.nrf-arts.org/IXRetail/namespace&gt;MonetaryAmount"&gt;
         *       &lt;attribute name="NumberPayments" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Successful {

            @XmlValue
            protected BigDecimal value;
            @XmlAttribute(name = "NumberPayments", required = true)
            protected BigInteger numberPayments;

            /**
             * expl: common definition of monetary amount data type
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setValue(BigDecimal value) {
                this.value = value;
            }

            /**
             * Gets the value of the numberPayments property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getNumberPayments() {
                return numberPayments;
            }

            /**
             * Sets the value of the numberPayments property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setNumberPayments(BigInteger value) {
                this.numberPayments = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="TerminalID" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}TerminalIDType" /&gt;
     *       &lt;attribute name="TerminalBatch" type="{http://www.nrf-arts.org/IXRetail/namespace}BatchCodeType" /&gt;
     *       &lt;attribute name="STAN" type="{http://www.nrf-arts.org/IXRetail/namespace}STANtype" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Terminal {

        @XmlAttribute(name = "TerminalID", required = true)
        protected String terminalID;
        @XmlAttribute(name = "TerminalBatch")
        protected String terminalBatch;
        @XmlAttribute(name = "STAN")
        protected Long stan;

        /**
         * Gets the value of the terminalID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTerminalID() {
            return terminalID;
        }

        /**
         * Sets the value of the terminalID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTerminalID(String value) {
            this.terminalID = value;
        }

        /**
         * Gets the value of the terminalBatch property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTerminalBatch() {
            return terminalBatch;
        }

        /**
         * Sets the value of the terminalBatch property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTerminalBatch(String value) {
            this.terminalBatch = value;
        }

        /**
         * Gets the value of the stan property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getSTAN() {
            return stan;
        }

        /**
         * Sets the value of the stan property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setSTAN(Long value) {
            this.stan = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Devices" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Device" maxOccurs="unbounded"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="SerialNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                             &lt;element name="TimeStamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
     *                             &lt;element name="PTID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                             &lt;element name="Manufacturer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                             &lt;element name="Model" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                             &lt;element name="ApplicationName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                             &lt;element name="ApplicationVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                             &lt;element name="ContactlessKernelName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                             &lt;element name="ContactlessKernelVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                             &lt;element name="FirmwareName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                             &lt;element name="FirmwareVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                             &lt;element name="OSName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                             &lt;element name="OSVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                             &lt;element name="EncryptionModuleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                             &lt;element name="EncryptionModuleVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                             &lt;element name="Product" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                           &lt;/sequence&gt;
     *                           &lt;attribute name="POPID" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}POPIDType" /&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "devices"
    })
    public static class Versions {

        @XmlElement(name = "Devices", required = true)
        protected List<Devices> devices;

        /**
         * Gets the value of the devices property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the devices property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDevices().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Devices }
         * 
         * 
         */
        public List<Devices> getDevices() {
            if (devices == null) {
                devices = new ArrayList<Devices>();
            }
            return this.devices;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Device" maxOccurs="unbounded"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="SerialNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                   &lt;element name="TimeStamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
         *                   &lt;element name="PTID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                   &lt;element name="Manufacturer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                   &lt;element name="Model" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                   &lt;element name="ApplicationName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                   &lt;element name="ApplicationVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                   &lt;element name="ContactlessKernelName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                   &lt;element name="ContactlessKernelVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                   &lt;element name="FirmwareName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                   &lt;element name="FirmwareVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                   &lt;element name="OSName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                   &lt;element name="OSVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                   &lt;element name="EncryptionModuleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                   &lt;element name="EncryptionModuleVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                   &lt;element name="Product" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                 &lt;/sequence&gt;
         *                 &lt;attribute name="POPID" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}POPIDType" /&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "device"
        })
        public static class Devices {

            @XmlElement(name = "Device", required = true)
            protected List<Device> device;

            /**
             * Gets the value of the device property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the device property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDevice().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Device }
             * 
             * 
             */
            public List<Device> getDevice() {
                if (device == null) {
                    device = new ArrayList<Device>();
                }
                return this.device;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="SerialNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *         &lt;element name="TimeStamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
             *         &lt;element name="PTID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *         &lt;element name="Manufacturer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *         &lt;element name="Model" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *         &lt;element name="ApplicationName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *         &lt;element name="ApplicationVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *         &lt;element name="ContactlessKernelName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *         &lt;element name="ContactlessKernelVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *         &lt;element name="FirmwareName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *         &lt;element name="FirmwareVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *         &lt;element name="OSName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *         &lt;element name="OSVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *         &lt;element name="EncryptionModuleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *         &lt;element name="EncryptionModuleVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *         &lt;element name="Product" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *       &lt;/sequence&gt;
             *       &lt;attribute name="POPID" use="required" type="{http://www.nrf-arts.org/IXRetail/namespace}POPIDType" /&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "serialNumber",
                "timeStamp",
                "ptid",
                "manufacturer",
                "model",
                "applicationName",
                "applicationVersion",
                "contactlessKernelName",
                "contactlessKernelVersion",
                "firmwareName",
                "firmwareVersion",
                "osName",
                "osVersion",
                "encryptionModuleName",
                "encryptionModuleVersion",
                "product"
            })
            public static class Device {

                @XmlElement(name = "SerialNumber")
                protected String serialNumber;
                @XmlElement(name = "TimeStamp")
                @XmlSchemaType(name = "dateTime")
                protected XMLGregorianCalendar timeStamp;
                @XmlElement(name = "PTID")
                protected String ptid;
                @XmlElement(name = "Manufacturer")
                protected String manufacturer;
                @XmlElement(name = "Model")
                protected String model;
                @XmlElement(name = "ApplicationName")
                protected String applicationName;
                @XmlElement(name = "ApplicationVersion")
                protected String applicationVersion;
                @XmlElement(name = "ContactlessKernelName")
                protected String contactlessKernelName;
                @XmlElement(name = "ContactlessKernelVersion")
                protected String contactlessKernelVersion;
                @XmlElement(name = "FirmwareName")
                protected String firmwareName;
                @XmlElement(name = "FirmwareVersion")
                protected String firmwareVersion;
                @XmlElement(name = "OSName")
                protected String osName;
                @XmlElement(name = "OSVersion")
                protected String osVersion;
                @XmlElement(name = "EncryptionModuleName")
                protected String encryptionModuleName;
                @XmlElement(name = "EncryptionModuleVersion")
                protected String encryptionModuleVersion;
                @XmlElement(name = "Product")
                protected String product;
                @XmlAttribute(name = "POPID", required = true)
                protected String popid;

                /**
                 * Gets the value of the serialNumber property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSerialNumber() {
                    return serialNumber;
                }

                /**
                 * Sets the value of the serialNumber property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSerialNumber(String value) {
                    this.serialNumber = value;
                }

                /**
                 * Gets the value of the timeStamp property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getTimeStamp() {
                    return timeStamp;
                }

                /**
                 * Sets the value of the timeStamp property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setTimeStamp(XMLGregorianCalendar value) {
                    this.timeStamp = value;
                }

                /**
                 * Gets the value of the ptid property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPTID() {
                    return ptid;
                }

                /**
                 * Sets the value of the ptid property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPTID(String value) {
                    this.ptid = value;
                }

                /**
                 * Gets the value of the manufacturer property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getManufacturer() {
                    return manufacturer;
                }

                /**
                 * Sets the value of the manufacturer property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setManufacturer(String value) {
                    this.manufacturer = value;
                }

                /**
                 * Gets the value of the model property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getModel() {
                    return model;
                }

                /**
                 * Sets the value of the model property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setModel(String value) {
                    this.model = value;
                }

                /**
                 * Gets the value of the applicationName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getApplicationName() {
                    return applicationName;
                }

                /**
                 * Sets the value of the applicationName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setApplicationName(String value) {
                    this.applicationName = value;
                }

                /**
                 * Gets the value of the applicationVersion property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getApplicationVersion() {
                    return applicationVersion;
                }

                /**
                 * Sets the value of the applicationVersion property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setApplicationVersion(String value) {
                    this.applicationVersion = value;
                }

                /**
                 * Gets the value of the contactlessKernelName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getContactlessKernelName() {
                    return contactlessKernelName;
                }

                /**
                 * Sets the value of the contactlessKernelName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setContactlessKernelName(String value) {
                    this.contactlessKernelName = value;
                }

                /**
                 * Gets the value of the contactlessKernelVersion property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getContactlessKernelVersion() {
                    return contactlessKernelVersion;
                }

                /**
                 * Sets the value of the contactlessKernelVersion property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setContactlessKernelVersion(String value) {
                    this.contactlessKernelVersion = value;
                }

                /**
                 * Gets the value of the firmwareName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFirmwareName() {
                    return firmwareName;
                }

                /**
                 * Sets the value of the firmwareName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFirmwareName(String value) {
                    this.firmwareName = value;
                }

                /**
                 * Gets the value of the firmwareVersion property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFirmwareVersion() {
                    return firmwareVersion;
                }

                /**
                 * Sets the value of the firmwareVersion property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFirmwareVersion(String value) {
                    this.firmwareVersion = value;
                }

                /**
                 * Gets the value of the osName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOSName() {
                    return osName;
                }

                /**
                 * Sets the value of the osName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOSName(String value) {
                    this.osName = value;
                }

                /**
                 * Gets the value of the osVersion property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOSVersion() {
                    return osVersion;
                }

                /**
                 * Sets the value of the osVersion property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOSVersion(String value) {
                    this.osVersion = value;
                }

                /**
                 * Gets the value of the encryptionModuleName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEncryptionModuleName() {
                    return encryptionModuleName;
                }

                /**
                 * Sets the value of the encryptionModuleName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEncryptionModuleName(String value) {
                    this.encryptionModuleName = value;
                }

                /**
                 * Gets the value of the encryptionModuleVersion property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEncryptionModuleVersion() {
                    return encryptionModuleVersion;
                }

                /**
                 * Sets the value of the encryptionModuleVersion property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEncryptionModuleVersion(String value) {
                    this.encryptionModuleVersion = value;
                }

                /**
                 * Gets the value of the product property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getProduct() {
                    return product;
                }

                /**
                 * Sets the value of the product property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setProduct(String value) {
                    this.product = value;
                }

                /**
                 * Gets the value of the popid property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPOPID() {
                    return popid;
                }

                /**
                 * Sets the value of the popid property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPOPID(String value) {
                    this.popid = value;
                }

            }

        }

    }

}
