//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 04:13:46 PM CDT 
//


package com.mastercard.gateway.ats.domain

import org.simpleframework.xml.Root


/**
 * expl:  textual description for rendering document
 *
 *
 * Java class for Text complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Text"&gt;
 * &lt;simpleContent&gt;
 * &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 * &lt;/extension&gt;
 * &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
</pre> *
 *
 *
 */
@Root(name = "Text")
data class Text(var value: String? = null)
