//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 04:13:46 PM CDT 
//


package com.mastercard.gateway.ats.domain

import org.simpleframework.xml.Attribute
import org.simpleframework.xml.Root
import java.math.BigDecimal


/**
 *
 * Java class for TotalAmountType complex type.
 *
 *
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TotalAmountType"&gt;
 * &lt;simpleContent&gt;
 * &lt;extension base="&lt;http://www.nrf-arts.org/IXRetail/namespace&gt;MonetaryAmount"&gt;
 * &lt;attribute name="Currency" type="{http://www.nrf-arts.org/IXRetail/namespace}CurrencyCode" /&gt;
 * &lt;attribute name="PaymentAmount" type="{http://www.nrf-arts.org/IXRetail/namespace}MonetaryAmount" /&gt;
 * &lt;attribute name="CashBackAmount" type="{http://www.nrf-arts.org/IXRetail/namespace}MonetaryAmount" /&gt;
 * &lt;attribute name="GratuityAmount" type="{http://www.nrf-arts.org/IXRetail/namespace}MonetaryAmount" /&gt;
 * &lt;attribute name="DonationAmount" type="{http://www.nrf-arts.org/IXRetail/namespace}MonetaryAmount" /&gt;
 * &lt;attribute name="Changeable" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 * &lt;attribute name="OriginalAmount" type="{http://www.nrf-arts.org/IXRetail/namespace}MonetaryAmount" /&gt;
 * &lt;attribute name="AvailableAmount" type="{http://www.nrf-arts.org/IXRetail/namespace}MonetaryAmount" /&gt;
 * &lt;/extension&gt;
 * &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
</pre> *
 *
 *
 */
@Root(name = "TotalAmountType")
data class TotalAmountType(var value: BigDecimal,
                           @field:Attribute(name = "Currency") var currency: CurrencyCode,
                           @field:Attribute(name = "PaymentAmount") var paymentAmount: BigDecimal,
                           @field:Attribute(name = "CashBackAmount") var cashBackAmount: BigDecimal,
                           @field:Attribute(name = "GratuityAmount") var gratuityAmount: BigDecimal,
                           @field:Attribute(name = "DonationAmount") var donationAmount: BigDecimal,
                           @field:Attribute(name = "Changeable") var changeable: Boolean?,
                           @field:Attribute(name = "OriginalAmount") var originalAmount: BigDecimal,
                           @field:Attribute(name = "AvailableAmount") var availableAmount: BigDecimal)
